### ISSUE TITLE
PicoTorrent crashes if I try to add column "Label"

### ISSUE THREAD

**Issue by alexantr** [picotorrent/picotorrent#1011]
PicoTorrent crashes if I try to add column "Label"
Versions 0.22 & 0.23 have same bug.
<img width="371" alt="PicoTorrent_2020-11-12_23-22-46" src="https://user-images.githubusercontent.com/4941848/98992558-65bcbc80-253e-11eb-9fd5-2d7f40ba4f8a.png">

**Comment by vktr** [comment]
I cannot report this myself, but I have seen some crashes reported in Sentry which might be related. I'll put up a PR for those and then maybe you can verify.

**Comment by vktr** [comment]
When the CI build for #1012 finishes, perhaps you can give it a spin and see if it fixes the issue 😃
