### ISSUE TITLE
PicoTorrrent doesn't start

### ISSUE THREAD

**Issue by birkoffe** [picotorrent/picotorrent#1013]
Last two releases starting with crashing, e.g try ci build #1012.

[2f97bfce-88ce-436a-b863-b0af0e819bd2.zip](https://github.com/picotorrent/picotorrent/files/5534769/2f97bfce-88ce-436a-b863-b0af0e819bd2.zip)

**Comment by vktr** [comment]
Can you check the log file for errors? It's in `AppData\PicoTorrent\logs`

**Comment by birkoffe** [comment]
All log-files after update have zero size.

**Comment by vktr** [comment]
I see. Can you move the PicoTorrent.sqlite file somewhere safe and see if it starts?

**Comment by birkoffe** [comment]
Starting without problem.

At the time of 0.21 I tried 0.22 from CI to testing lables, Maybe not compatible structure of DB between 0.22-ci and releases versions?

**Comment by vktr** [comment]
Could be... Running CI builds may contain half-finished migrations and would leave the database in an invalid state. I’d recommend only running the portable CI builds or at least backing up the sqlite file before installing. 

Happy to hear you got it running! :)

**Comment by birkoffe** [comment]
oh, i do it.

drop filters and label tables, delete new settings and columns added in dbmigration of filters and labels... and  I can run 0.23 with my PicoTorrent.sqlite file.

Thanks for help.
