### ISSUE TITLE
[Request] Add Support For Hybrid Torrent Creation

### ISSUE THREAD

**Issue by zero77** [picotorrent/picotorrent#1014]
Can you please add support for hybrid torrent creation and ideally set it to the default.
So that users can take advantages of the new functionality and security of v2 torrents while still supporting legacy torrents.

https://blog.libtorrent.org/2020/09/bittorrent-v2/

**Comment by vktr** [comment]
Hi @zero77! This is already the default if you open the *Create torrent* dialog,

![image](https://user-images.githubusercontent.com/1491824/99050683-7863df80-2598-11eb-9a11-dcdf921b20c4.png)

**Comment by zero77** [comment]
@vktr 
Thanks
