### ISSUE TITLE
Missing translations fallback

### ISSUE THREAD

**Issue by StoyanDimitrov** [picotorrent/picotorrent#1020]
We need graceful translation fallback when the translation is missing. Right now the UI shows the ID/key of the string. What's the least useful is to fallback to the English string instead.

Edit: The most prominent examples are the `eta_*` strings.

**Comment by StoyanDimitrov** [comment]
One way of doing it is to:
* `INSERT` the English locale in the empty table;
* `UPDATE` the `locale` field with the target locale value (say `en-GB`);
* `UPDATE` the available in the target locale `value` fields matched by `key`;
* repeat for all locales;
* `INSERT` the English locale last.

**Comment by vktr** [comment]
I think the easiest way to default to 'en-US' is to just set it in code - I think I did something like that, and when I look in the code I see this; https://github.com/picotorrent/picotorrent/blob/master/src/picotorrent/ui/translator.cpp#L116. So, I made a bad assumption but the fix is easy 😃

**Comment by StoyanDimitrov** [comment]
Isn't line [119](https://github.com/picotorrent/picotorrent/blob/master/src/picotorrent/ui/translator.cpp#L119) the right place?

**Comment by vktr** [comment]
No, that is what should happen if we don't find the English translation using the default key - which is misspelled as 'en' when it should be 'en-US' 🙄

**Comment by StoyanDimitrov** [comment]
I tried your suggestion in #1051 but is not what it should be. Since I can't wrap my head around the code I'm leaving it to you for now.
