### ISSUE TITLE
Crash related to labels

### ISSUE THREAD

**Issue by StoyanDimitrov** [picotorrent/picotorrent#1023]
When there are no labels created yet and one try to show the `Labels` column in the torrents list the application crashes.

**Comment by vktr** [comment]
I think I fixed this in #1012 - could you try that build and see if it fixes things? I haven't been able to reproduce this...

**Comment by StoyanDimitrov** [comment]
It turned out I have a created label. The issue can not be reproduced with the clean DB. I'll try to find STR.

**Comment by StoyanDimitrov** [comment]
Fixed in #1012
