### ISSUE TITLE
Move completed downloads feature doesn't work

### ISSUE THREAD

**Issue by Dyras** [picotorrent/picotorrent#1033]
Greetings! A feature I'm really missing is the ability to choose a download folder. Basically, the files are downloaded to this folder and then moved to the standard folder (Or whatever other folder it's set to download in) upon completion.

**Comment by vktr** [comment]
If I'm not misinterpreting, I think we already have this with *Move completed downloads* in the preferences.

![image](https://user-images.githubusercontent.com/1491824/100071935-e7182700-2e3b-11eb-87b5-a4920e8a8e40.png)

**Comment by Dyras** [comment]
I suspected that feature might be for that, but it's not working for me so I figured I just misunderstood something:
![image](https://user-images.githubusercontent.com/12563436/100073193-7d008180-2e3d-11eb-94cb-7cfb8680a733.png)
![image](https://user-images.githubusercontent.com/12563436/100073233-8b4e9d80-2e3d-11eb-8a6a-8d41f59d72c7.png)
![image](https://user-images.githubusercontent.com/12563436/100073301-a4574e80-2e3d-11eb-8d68-36feeab64edd.png)

**Comment by vktr** [comment]
Torrents will be downloaded to the path in *Save path*. Upon completion, they will be moved to the path in *Move completed downloads*. Is that not the case?

**Comment by Dyras** [comment]
Files aren't moved at all, in either direction. I tried making a new folder without a space because I figured that might be what breaks it, but my new folder named "DL" is empty even after downloading a torrent. I also tried switching to English because why the hell not

![image](https://user-images.githubusercontent.com/12563436/100073810-3fe8bf00-2e3e-11eb-8147-f7a4104bf8fd.png)

**Comment by vktr** [comment]
I can confirm it doesn't work as advertised.. 🤔

**Comment by vktr** [comment]
I can't reproduce this issue anymore - would you mind trying again with the latest CI builds?

**Comment by Dyras** [comment]
Completely forgot to respond to this over new years etc.

Seems to work just fine with the latest release! 👍

**Comment by afkjm** [comment]
I actually can't get this to work; active torrents remain seeding and in my "incomplete" folder... I wish this would work... (windows 10
![pico torrent](https://user-images.githubusercontent.com/41496161/185546747-27178388-1b11-43b2-981a-d749823bf885.PNG)
)
