### ISSUE TITLE
Error: The system detected an invalid pointer address in attempting to use a pointer argument in a call

### ISSUE THREAD

**Issue by Ninjasr** [picotorrent/picotorrent#1075]
No matter what I do, the status field shows this error. 
I've tried to resume the download, force resume, force recheck, force reannounce, restarting PicoTorrent and deleting and readding the torrent.

**Comment by Ninjasr** [comment]
Yeah, I realised what the problem was

**Comment by vktr** [comment]
I've seen this before but haven't been able to reproduce it. What was your solution?

**Comment by Ninjasr** [comment]
Well, I noticed I ran out of disk space.
