### ISSUE TITLE
strange amp_ prefixes in UI portable version of 0.23 

### ISSUE THREAD

**Issue by Dratas** [picotorrent/picotorrent#1078]
Other bug is that releated with translations why i see in LT-lt translation some strange amp_ prefix,for example in meniu where is create torrent torrent file it write "Pridėti naują .torrent failą"after this below "amp_create_new torrent"i got feeling that its not fully translated version,but in english no these prefixes.

**Comment by nero-0** [comment]
See #975 #1069

**Comment by vktr** [comment]
As @nero-0 mentioned, this has been fixed in #1069 where we instead fall back to English.
