### ISSUE TITLE
"Download missing dependencies" dead link in installer

### ISSUE THREAD

**Issue by mattnovelli** [picotorrent/picotorrent#1094]
dead link in windows 0.24.0 installer 😢: https://docs.picotorrent.org/en/master/installing.html#download-missing-dependencies
![TM5f7dEWrE](https://user-images.githubusercontent.com/5261716/103724021-fe991280-4f98-11eb-8430-9c86db6edde7.png)
![DBwup6VXJs](https://user-images.githubusercontent.com/5261716/103724116-3acc7300-4f99-11eb-8690-965e3ff7687d.png)

**Comment by wft44maqb** [comment]
https://github.com/picotorrent/picotorrent/blob/f32318996d0286c658bf5212457a39bef2d608a5/src/installer/Views/InstallWaitingView.xaml#L43
