### ISSUE TITLE
[Ask] Filter in Labels preferences

### ISSUE THREAD

**Issue by lshaf** [picotorrent/picotorrent#1096]
Can someone explain how it works?
Somehow I can't found any explanation about it on documentation.

Thanks

**Comment by StoyanDimitrov** [comment]
The filter is a string matched against the torrent name. If match is found then the label is applied.

**Comment by lshaf** [comment]
so it's regex filter or something?
Can you provide me with an example?

**Comment by vktr** [comment]
Yes, its a regex. For example ^debian.* will match all torrents that starts with debian.

It's ECMAScript flavor if you need to check syntax.

A few more examples,

^debian.*\.iso$ - will match a torrent whose name starts with debian and ends with .iso

**Comment by lshaf** [comment]
ohh okay, thanks mate.
