### ISSUE TITLE
feature request: save .torrent options

### ISSUE THREAD

**Issue by artyfox** [picotorrent/picotorrent#1145]
Currently there is the ability to copy the info hash of a download task, but no option to save its associated torrent file. It would be nice to have an additional context menu option to "save .torrent file" .

For convenience under Preferences, there could be an option to automatically save the .torrent file of each task to its individual download folder (or to a common torrents folder).

This would make file organization and integrity checking much easier. Thanks! 🦊

**Comment by vktr** [comment]
I think at least the option to save the torrent file from the torrent context menu has been requested before and it is a good idea. Thanks for suggesting!
