### ISSUE TITLE
"Move completed downloads" doesn't

### ISSUE THREAD

**Issue by rreiner** [picotorrent/picotorrent#1152]
The preference `Move completed downloads` does nothing... completed downloads remain in the `Save path` folder.
Using 0.24.0 but this hasn't changed since I started using PicoTorrent several releases ago.

In case it matters, I have the settings as follows:

`Save path` = `D:\Temp\BT_Working`
`Move completed downloads` = selected, `D:\Downloads`
`Only move from default save path` = unselected

**Comment by vktr** [comment]
Thanks for the report! I think there is some existing issue for this as well, but I can keep this in case there isn't.

**Comment by annomatik** [comment]
That's the one: https://github.com/picotorrent/picotorrent/issues/1108

**Comment by vktr** [comment]
Closing this in favor of the original 😃
