### ISSUE TITLE
Q: I see plenty of incoming connection when starting seeding but failed to connect.

### ISSUE THREAD

**Issue by escape0707** [picotorrent/picotorrent#1157]
As titled. When I start to seed a not very popular torrent. I see many peers in the peer list with `I` flag and sometimes `X` and `H` flags, but the client won't establish a transmission with them. When using qBittorrent, I got some peers at torrent start and won't always connect, too, but those peers aren't flagged incoming.

Are those peers really incoming connections? Or they are just cached peers that BT client will try to connection when starting and be placed an `I` flag by mistake?

**Comment by escape0707** [comment]
After looking at qB and pico's code difference, I believe that pico is flagging incoming connection and local connection the opposite way.

https://github.com/qbittorrent/qBittorrent/blob/2e30ed17bd6adeb35033769615128a98be21fb1f/src/base/bittorrent/peerinfo.cpp#L311-L315

https://github.com/picotorrent/picotorrent/blob/f32318996d0286c658bf5212457a39bef2d608a5/src/picotorrent/ui/models/peerlistmodel.cpp#L130-L133

**Comment by vktr** [comment]
Hi! Sorry for the late-ish answer. I think the peer flags was based on uTorrent back when I implemented it, and not qBittorrent 🤔 Or at least that's my recollection, it's been a few years 😃 Anyways, it makes sense to align the flags with qBittorrent to make transition easier.

**Comment by escape0707** [comment]
I was only looking into qB for verifying my conjecture. I actually draw the conclusion of "opposite" from [libtorrent's reference](https://libtorrent.org/reference-Core.html):

> <dl>
> <dt>outgoing_connection</dt>
> <dd>The connection was initiated by us, the peer has a
> listen port open, and that port is the same as in the
> address of this peer. If this flag is not set, this
> peer connection was opened by this peer connecting to
> us.</dd>
> </dl>
> <dl>
> <dt>local_connection</dt>
> <dd>deprecated synonym for outgoing_connection</dd>
> </dl>
