### ISSUE TITLE
Question: Filtering Torrentlist

### ISSUE THREAD

**Issue by annomatik** [picotorrent/picotorrent#1161]
Not sure, if this is possible or not. But in Soulseek, Jackett, Hydra and a lot of other clients, I can simply enter a word and the list shown is reduced to showing only items containing that word. Is that also possible somehow in PicoTorrent 0.24? How can I do that? I haven't found a filter-bar. Thanks!

**Comment by vktr** [comment]
You can use PQL for this. Click `View -> Console` and you can use something like `name ~ "debian"` to filter on torrents containing debian in its name. It is more powerful than that - docs here, https://docs.picotorrent.org/en/master/pql.html

**Comment by annomatik** [comment]
Works great, thanks!
