### ISSUE TITLE
Feature Request: PQL support for "label"

### ISSUE THREAD

**Issue by annomatik** [picotorrent/picotorrent#1162]
Hi! I'd like to be able to filter by label. E.g. by entering "label ~ "distro"" in the Console. Also, it would be very nice to have a "console history", for example a down-pointing arrow ("v") on the very right part of the console bar, that enables me to repeat the pql queries I did earlier. Maybe the last 10 ones?

Thanks!

**Comment by vktr** [comment]
Yeah, label filtering in PQL should be added. Until it has been, I think you can combine a PQL filter with the regular label filter from `View -> Labels`.
