### ISSUE TITLE
Losing torrents on upgrade

### ISSUE THREAD

**Issue by mica** [picotorrent/picotorrent#119]
Whenever I upgrade with Chocolatey, the torrents I was seeding are gone.

**Comment by vktr** [comment]
Strange - which version did you upgrade from? Did all torrents disappear, or just the ones added that session?

**Comment by mica** [comment]
It happened when upgrading from .3 to .4 and .4 to .5. They were torrents I had been seeding for awhile. I'll test it out soon on another machine soon, see if it's happening there too.

**Comment by mica** [comment]
I've determined that this happens whenever picotorrent crashes. Any torrents added that session are lost. Quitting the app properly, everything's fine, but end the task (something that must've happened while upgrading), and downloads/seeds get wiped out.

**Comment by vktr** [comment]
Thanks for the investigation! I'll make sure PicoTorrent saves its state whenever a torrent is added, that way if it crashes it should be able to resume the transfers at least.

**Comment by mica** [comment]
Just lost some torrents again when the power went out and crashed the computer. Really hope you can get this one fixed.

**Comment by vktr** [comment]
Sorry about that, I'll add a fix for this in the next version.
