### ISSUE TITLE
Windows 11/WinUi redesign ?

### ISSUE THREAD

**Issue by aayushbhatia06** [picotorrent/picotorrent#1199]
Hi, 
First of all, thanks for this awesome project.
This is the only actively developed native torrent app for Windows (That isnt Qt or others) and that's a big thing!
Now, with Windows 11 on the horizon and WinUi nearing maturity, are there any plans for a redesign to make it look more modern?
It will be a really good undertaking, and will make PicoTorrent unquestionably the best torrent client for Windows.
And although programming is not my strongest suite, If you need any help with design mockups or even XAML mockups, I will be more than happy to help!

**Comment by vktr** [comment]
Hey @aayushbhatia06! There's been some talk about WinUI on our Discord - feel free to join at https://discord.gg/tV3dFrv :smiley:

The roadmap (although delayed) is that we'll fix Linux and macOS support based on wxWidgets, then move on from there!

**Comment by scriptBoris** [comment]
We need dark theme!

**Comment by endlessempathy** [comment]
It will be POG to have torrent client that will not remind times of dial-up modems. Would be great to see WinUI in Picotorrent

**Comment by ChungZH** [comment]
WinUI, YES!

**Comment by vktr** [comment]
Hi all! There are still some concerns with packaging for WinUI 3 applications that I'm not too fond of.. I also have plans on making PicoTorrent cross-platform which WinUI 3 would prevent. We'll see in the future, but there's been lots of voices raised for WinUI 😄 I'm closing this for now, but feel free to hop in to Discord (https://discord.gg/tV3dFrv) if you want to discuss further!
