### ISSUE TITLE
Autostart the app after boot of Windows & Feature "Check new updates"

### ISSUE THREAD

**Issue by AnonimusRus** [picotorrent/picotorrent#123]
Can you do it?

**Comment by vktr** [comment]
Great suggestion :smile: Starting PicoTorrent on boot is just a registry key away, so should be no problem.

What do you mean with autostarting after Check new updates?

**Comment by AnonimusRus** [comment]
When you click "Check new updates", the program checks number of the last version of the app on the server. If installed app on your computer older than the last version on the server, app offers a link to download latest version of the program. 
Another variant. After clicking "Check new updates", the app downloads on the PC latest install package, then occur autoupdate of the picotorrent. This variant better, but harder to do)

**Comment by vktr** [comment]
It should be relatively easy to download the latest release automatically (if the user want) and then starting the installation. Not as automatic as you describe, but still better than the current behavior. What do you think?

**Comment by AnonimusRus** [comment]
It's nice to see it.
