### ISSUE TITLE
Weblate is dead

### ISSUE THREAD

**Issue by BRGustavoRibeiro** [picotorrent/picotorrent#1253]
PicoTorrent's Weblate URL is broken.

**Comment by PriitUring** [comment]
**This should be closed and marked as duplicate of:**
* https://github.com/picotorrent/picotorrent/issues/1230
* https://github.com/picotorrent/picotorrent/issues/1217

**Comment by BRGustavoRibeiro** [comment]
Closed as duplicate. Thanks @PriitUring
