### ISSUE TITLE
Choose location or storage provider in PicoTorrent

### ISSUE THREAD

**Issue by ghost** [picotorrent/picotorrent#1257]
Hi everyone.

#### Idea
Whenever I open picotorrent, the torrent locally downloads the file on my machine. An interesting idea is to offer options like ipfs, hypercore or ftp - or even synchronizations like google drive, meganzco, dropbox, trezorit etc. That way, when the file for download, a copy is sent to another server or another location, and with that I have a backup copy or storage(for security)

#### why?
Could be an alternative to [bitport-io](https://bitport.io/welcome) for picotorrent

#### question/feedback
*What do you all  think about this feature?*

**Comment by cyberhardt** [comment]
that's quite interesting to be honest
