### ISSUE TITLE
Global UL/DL limits

### ISSUE THREAD

**Issue by VoodaGod** [picotorrent/picotorrent#136]
Have an option to set global UL/DL limits, so for example if I know I can use the internet comfortably while seeding at 50kb/s I'll just set this globally and PicoTorrent will make sure the total UL of all torrents stays below 50kb/s.
Currently you can only set these limits per torrent, which is unfortunate since you have to manually balance them when seeding multiple torrents, since setting them each to 50kb/s will not keep the total bandwidth at this level

**Comment by vktr** [comment]
It's a great idea, and should be easy to implement!

**Comment by VoodaGod** [comment]
that's what i like to hear ;)
