### ISSUE TITLE
Crash when opening a bad file path

### ISSUE THREAD

**Issue by Robo210** [picotorrent/picotorrent#142]
If I paste a URL to a torrent in the Add Torrent dialog and hit Open, PicoTorrent crashes [on this line](https://github.com/picotorrent/picotorrent/blob/develop/src/client/ui/open_file_dialog.cpp#L48).

fs::path p(path) throws an exception because it appears path is NULL, and then that exception gets caught when it leaves the callback and turns into this hard-to-debug-from-a-dmp exception:

> EXCEPTION_RECORD:  (.exr -1)
> ExceptionAddress: 00007fff487d72cb (user32!DefDlgProcW+0x0000000000000053)
>    ExceptionCode: c000041d
>   ExceptionFlags: 00000001
> NumberParameters: 0
> 
> DEFAULT_BUCKET_ID:  APPLICATION_FAULT
> 
> PROCESS_NAME:  PicoTorrent.exe
> 
> ERROR_CODE: (NTSTATUS) 0xc000041d - An unhandled exception was encountered during a user callback.
> 
> EXCEPTION_CODE: (NTSTATUS) 0xc000041d - An unhandled exception was encountered during a user callback.

Checking the return code from IShellItem::GetDisplayName might help skip over bad items, or catching  the exception and returning false from the [open_torrent_dialog::on_file_ok](https://github.com/picotorrent/picotorrent/blob/0ae9f5b15faa6618b276d9591bcbc662ff9e5b74/src/client/ui/open_torrent_dialog.cpp#L12) might be sufficient to stop it from crashing.

**Comment by vktr** [comment]
Thanks @Robo210!
