### ISSUE TITLE
Make PicoTorrentCore cross-platform

### ISSUE THREAD

**Issue by vktr** [picotorrent/picotorrent#149]
The PicoTorrentCore project should be made cross-platform so we can start building Linux and OSX clients.

- [x] Remove `timer` class from PicoTorrentCore. (#181)
- [ ] Write platform-specific implementations of the file system classes.
- [ ] Write platform-specific implementations of the `environment` class.
- [x] Do not rely on a `HWND` in `session::load`. (#216)

**Comment by timofonic** [comment]
@vktr Why did you close this? What happened? I'm very interesting about seeing it supported in Linux too.

**Comment by olivierchatry** [comment]
I guess you can probably use Wine if you really want it to run on linux,
but a port of picotorrent is more like a complete rewritte of it ( it is
using WTL for GUI which is a C++ wrapper around win32 API). I think it is
clearly not the goal of this project to support any other platform.
