### ISSUE TITLE
msvcp140.dll

### ISSUE THREAD

**Issue by smaragdus** [picotorrent/picotorrent#153]
PicoTorrent requires msvcp140.dll in order to run, which is not included in the portable (archived) packages. For more information please have a look at this forum thread:
http://www.portablefreeware.com/forums/viewtopic.php?f=4&t=22517

**Comment by vktr** [comment]
Hi! Yeah, it should definitely be included in the zip archive to have a true portable package. Labelling this as a feature request and will include it in the next version (0.7). Thanks!

**Comment by smaragdus** [comment]
Thanks for the immediate response. I am glad you released a portable version which is a big advantage. I am still testing PicoTorrent (I discovered it yesterday) and if it happens that I come across any other probems I will report them here. One more request- in the portable version I didn't find a way to add a magnet link- I suggest that in 'File' menu you may add 'Add magnet link' below 'Add torrent'. Regards.

**Comment by vktr** [comment]
Thanks! Feel free to report any issues as you find them! Adding magnet links is already planned with the issue opened at #121.

**Comment by smaragdus** [comment]
If you implement adding magnet links you may also add 'Add magnet link' to system tray menu.
You may also add Show/Hide commands to system tray menu.

**Comment by vktr** [comment]
After some investigation, it seems non-trivial to distribute the correct DLL files alongside PicoTorrent for the portable package. I think it's better to not distribute the runtime and instead have the user install it, just as it is now. Perhaps in the future we can link statically against the runtime, but that has downsides as well...

**Comment by zp** [comment]
I had started on this with the intention of getting it done before 0.7 went out, but I got side-tracked and never finished testing it.

I've opened PR #165 which should be what this issue is looking for, but I'll leave it up to vktr

**Comment by zp** [comment]
@smaragdus 

I've decided to revisit making a fully portable package, including support for Windows versions prior to 10, since it seems to be requested quite a bit.

You can acquire the packages [on this github issue](https://github.com/picotorrent/picotorrent/issues/195#issuecomment-191867598)
