### ISSUE TITLE
Add storage mode option

### ISSUE THREAD

**Issue by vktr** [picotorrent/picotorrent#174]
Add an option to the add torrent dialog which lets the user switch between sparse and full file allocation.

**Comment by jsieler** [comment]
Would be really nice option, cause by downloading >200GB Torrent, don't really want to allocate all space for nothing.

**Comment by vktr** [comment]
The current behavior is to use sparse allocation, so your use case is the supported one. This feature request is for adding support to select full file allocation instead. Sorry for the confusion :smile:
