### ISSUE TITLE
Separate PDB symbols from installer bundle

### ISSUE THREAD

**Issue by vktr** [picotorrent/picotorrent#177]
By putting the PDB symbols in a separate package (ie. a zip file) we can reduce the size of the installer bundle from 7.66MB to about 2.5MB (for x64).

**Comment by zp** [comment]
Do you want to remove the symbols from the portable zip packages as well?

**Comment by vktr** [comment]
Yes, and have the symbol package named `PicoTorrent-x.y.z-x[64|86].symbols.zip`, or something like that :smile: We should also set `CompressionLevel="high"` on the `<Media />` element in `PicoTorrent.wxs` as a bonus fix for this.
