### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by vktr** [picotorrent/picotorrent#182]
We should implement support for IPv6 - which in practice means that we should remove the IP and port inputs and replace them with a multiline textbox where each line is a IP/port pair, like this,

```
0.0.0.0:6881
[::]:6881
```

This means we can fully utilize IPv6 for those that have it enabled.

**Comment by ringoz** [comment]
But how to enable IPv6?
Why isn't it enabled by default?

**Comment by vktr** [comment]
You can add the IPv6 network adapter in the Connections page in preferences
