### ISSUE TITLE
Add save location for complete/incomplete torrents.

### ISSUE THREAD

**Issue by jsieler** [picotorrent/picotorrent#184]
That would be nice to have an option to store complete and incomplete torrents into different folders.

**Comment by vktr** [comment]
Agreed. We should probably add an optional configured path where incomplete downloads should be stored, and if not set PicoTorrent would download directly to the target (save path). If set, PicoTorrent would download to the temporary path first and then move all files when the download completes.

**Comment by Prefinem** [comment]
+1  I always have an incomplete download path on my SSD and then move to a HD once it's completed.

**Comment by vdias** [comment]
+1... I really miss this setting
