### ISSUE TITLE
UL not displayed if speed is under 1kb/s.

### ISSUE THREAD

**Issue by jsieler** [picotorrent/picotorrent#186]
Strange, but details view shows it, but not within the main window.

**Comment by vktr** [comment]
This is by design, I think speeds under 1KB/s are mostly useless since they're almost stalled anyway. If you really want to show speeds less than 1KB/s, perhaps a configuration option for this could be implemented.

**Comment by jsieler** [comment]
Sorry, can't upload image here (something went wrong... ooops), so look here:
http://share.pride-it.net/v/73dc0b14
What is then the reason to display "low" speed in detailed view?

**Comment by vktr** [comment]
The details view shows the rates *per peer*, which shows the actual DL/UL rates to help with troubleshooting issues, eg. "Am I actually uploading anything?". The main window shows speeds based on the premise "show rates that are actually useful to know".

**Comment by zp** [comment]
I recently changed the details view to also not show speeds under 1KB/s, I can change it to not show speeds that are actually 0 (so users can see if they're actually dl/ul anything)

**Comment by vktr** [comment]
@zp That's true, forgot about that :smile: Let's keep it as is.
