### ISSUE TITLE
Setting torrent to pause set status as "completed".

### ISSUE THREAD

**Issue by jsieler** [picotorrent/picotorrent#188]
I think it's better to set is as "paused" since "completed" sounds more like "download completed", but as paused you are not seeding or downloading anything more.

**Comment by DoumanAsh** [comment]
I think you should be able to distinguish 100% downloaded torrents and the one that are incomplete. In that regard not-complete torrents should be Paused, while 100% completely downloaded should have status "Completed".

But i suppose it is up to @vktr

**Comment by jsieler** [comment]
Statuses from other torrent clients:

Downloading - you are downloading and seeding also
Seeding - your download is complete and you are seeding now
Paused - you are not downloading and not seeding anything

**Comment by vktr** [comment]
I think we need to discuss how this should be handled. We could, for example, add icons to the list view to enhance the current status even more - i.e a torrent with an upwards-pointing arrow and a status that says Finished would imply that the transfer is finished and still active, while a pause icon would imply that the transfer is finished and paused.

**Comment by vktr** [comment]
Fixed in #324.
