### ISSUE TITLE
Crashes on first launch

### ISSUE THREAD

**Issue by vavavr00m** [picotorrent/picotorrent#191]
Version: PicoTorrent x86 portable

OS: Windows 7 x86

Settings:
{
  "default_save_path": "D:\\Torrent",
  "global_dl_rate_limit": 0,
  "global_ul_rate_limit": 0,
  "prompt_for_save_path": true,
  "start_position": 0,
  "wnd_main": [
    0,
    -1,
    -1,
    -1,
    -1,
    225,
    25,
    825,
    25,
    1
  ]
}

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	PicoTorrent.exe
  Application Version:	0.0.0.0
  Application Timestamp:	56c9eb49
  Fault Module Name:	ucrtbase.DLL
  Fault Module Version:	10.0.10240.16390
  Fault Module Timestamp:	55a5bf73
  Exception Code:	40000015
  Exception Offset:	0007d85a
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0970
  Additional Information 2:	09703b007ae608b48350586a57f60025
  Additional Information 3:	fefb
  Additional Information 4:	fefb0a823d596baab71da29ce0a24ba5

**Comment by vktr** [comment]
Have you installed the Visual C++ 2015 runtime? Found here, https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by srinath-v** [comment]
Yup it is installed and the crash still happens.

**Comment by jsieler** [comment]
The problem might happen if your "ucrtbase.dll" is damaged. Had similar problem. Just copy one from another PC and that should work.

@DEV's
is local deployment of "ucrtbase.dll" supported (copying it into app folder)?

**Comment by vktr** [comment]
@jsieler I haven't tried it, but see no reason it shouldn't work. If you do try it, please let me know the result :smile:

**Comment by jsieler** [comment]
@vktr going to try that tomorrow. If it gonna work, no one will need to install VC++ :D

**Comment by vktr** [comment]
@jsieler, we (me and @zp) did a spike at distributing an app local runtime along with PicoTorrent however there are alot of files needed when you run anything other than W10.

**Comment by vktr** [comment]
@vavavr00m Did you manually edit the `PicoTorrent.json` file? That save path is not valid JSON, it should be `D:\\Torrents`.

**Comment by vavavr00m** [comment]
@vktr 
1. 2 Microsoft Visual C++ 2015 installed:
RC Redistributable (x86) - 14.0.22816
Redistributable (x86) - 14.0.23026
Do I need to install the one you linked?
2. Yes I did but it reverted to D:\\Torrents anyway.

@jsieler 
Where do I copy ucrtbase.dll? 
If it works, can you please upload a clean copy of ucrtbase.dll

**Comment by jsieler** [comment]
@vavavr00m see my howto here: https://github.com/picotorrent/picotorrent/issues/195

**Comment by vktr** [comment]
@vavavr00m Try the portable packages from here, https://github.com/picotorrent/picotorrent/issues/195#issuecomment-191926772. If it doesn't work then, you can re-open this issue or open another one.
