### ISSUE TITLE
Picotorrent without installing VC++

### ISSUE THREAD

**Issue by jsieler** [picotorrent/picotorrent#195]
Not real issue, but small how-to.

So, as i've told before here https://github.com/picotorrent/picotorrent/issues/191#issuecomment-190254621, there seems to be a way to run Picotorrent without need of installing VC++. Sure you can do the same, it Picotorrent says that some of your DLL's are damaged or missing. Copying already installed files from other system working well.

Tested on Fresh-Installed Windows 7 64bit.

Following files from existing VC++ are required:
```
api-ms-win-core-file-l1-2-0.dll
api-ms-win-core-file-l2-1-0.dll
api-ms-win-core-localization-l1-2-0.dll
api-ms-win-core-processthreads-l1-1-1.dll
api-ms-win-core-synch-l1-2-0.dll
api-ms-win-core-timezone-l1-1-0.dll
api-ms-win-crt-conio-l1-1-0.dll
api-ms-win-crt-convert-l1-1-0.dll
api-ms-win-crt-environment-l1-1-0.dll
api-ms-win-crt-filesystem-l1-1-0.dll
api-ms-win-crt-heap-l1-1-0.dll
api-ms-win-crt-locale-l1-1-0.dll
api-ms-win-crt-math-l1-1-0.dll
api-ms-win-crt-multibyte-l1-1-0.dll
api-ms-win-crt-runtime-l1-1-0.dll
api-ms-win-crt-stdio-l1-1-0.dll
api-ms-win-crt-string-l1-1-0.dll
api-ms-win-crt-time-l1-1-0.dll
api-ms-win-crt-utility-l1-1-0.dll
msvcp140.dll
ucrtbase.dll
vcruntime140.dll
```
All you need, just to copy all this files into Picotorrent root directory (where .exe file is) and enjoy this tiny and nice client.

I'm not able to upload files here, so they are right on my server. Scanned with Avast, you can re-scan it also too:
http://sieler.im/PicoTorrent.zip
http://sieler.im/PicoTorrent.md5

@DEVS:
Feel free to redistribute and share this info as well!

**Comment by vavavr00m** [comment]
Is this for x86? I'm getting an error: 
> PicoTorrent\MSVCP140.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support.

**Comment by jsieler** [comment]
Which version of windows you have?

Mine libraries are from Win7 64bit, but from system32 folder, not from
syswow64.
2 марта 2016 г. 22:26 пользователь "vavavr00m" <notifications@github.com>
написал:

**Comment by zp** [comment]
I'll get around to writing a script that will package all the required files for each platform (x86, x64) from the AppVeyor build machine PicoTorrent is built on, and post the links here. So users can get a 'true portable' if they so desire.

I doubt @vktr will want it added to the main repo, so it will be an 'unofficial' fork that I do it on.

**Comment by vavavr00m** [comment]
@jsieler Win7 32bit.

@zp Please keep us posted.

**Comment by vktr** [comment]
@zp I'd be happy to add it to the main repo seeing as it's been requested a few times :smile: If you add it, name it something like `PicoTorrent-0.7.0-x86.portable.zip`.

**Comment by zp** [comment]
x86 (32bit): https://ci.appveyor.com/api/projects/picotorrent/picotorrent/artifacts/build-x86/Release/PicoTorrent-0.7.0-x86.runtime.zip?job=Environment%3A%20platform%3Dx86

x64 (64bit): https://ci.appveyor.com/api/projects/picotorrent/picotorrent/artifacts/build-x64/Release/PicoTorrent-0.7.0-x64.runtime.zip?job=Environment%3A%20platform%3Dx64

Extract the files to where `PicoTorrent.exe` is located.

**Comment by zp** [comment]
x86 (32bit): https://ci.appveyor.com/api/projects/picotorrent/picotorrent/artifacts/build-x86/Release/PicoTorrent-0.7.0-x86.portable.zip?job=Environment%3A%20platform%3Dx86

x64 (64bit): https://ci.appveyor.com/api/projects/picotorrent/picotorrent/artifacts/build-x64/Release/PicoTorrent-0.7.0-x64.portable.zip?job=Environment%3A%20platform%3Dx64

The updated links bundle everything in the same zip. Just extract to desired location and you'll have a fully portable PicoTorrent bundle. 

You'll probably notice some changes, as these zips are based on a more recent development version of PicoTorrent.

**Comment by vktr** [comment]
Thanks to @zp we can close this one, as from now on all releases and AppVeyor builds will have a true portable package as well.

**Comment by vavavr00m** [comment]
No crash since using the bundle. Thank you very much @zp and @jsieler

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/issues/339

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/issues/43

**Comment by svnpenn** [comment]
@vktr the current release does not have these files
