### ISSUE TITLE
Crash again

### ISSUE THREAD

**Issue by vavavr00m** [picotorrent/picotorrent#198]
Celebrated too soon.

PicoTorrent crashed with the following stack trace; https://gist.githubusercontent.com/anonymous/6d863daeb7dc15c8d9b4/raw/e5aa10f5605f1855f5164de2f167551aa44e4970/PicoTorrent_crash_report.txt

**Comment by vktr** [comment]
Would you mind downloading the symbol package and extract the PDB files to your PicoTorrent directory, then try to recreate the issue again. This gives us line numbers in the stack trace which would help a lot!

**Comment by vktr** [comment]
Seems to have gone stale - feel free to re-open this issue if the crash perists.

**Comment by vavavr00m** [comment]
Sorry for the very late response. I still experience the MSVCP140.dll missing with the latest version. Do I have to extract anything other than the symbols package?

**Comment by vktr** [comment]
Hi, did you install the latest C++ redistributable as linked from the release notes?

**Comment by vavavr00m** [comment]
Which package might that be?

**Comment by vktr** [comment]
This one, https://www.microsoft.com/en-us/download/details.aspx?id=49984
