### ISSUE TITLE
Link statically against the MSVC runtime

### ISSUE THREAD

**Issue by vktr** [picotorrent/picotorrent#202]
I'm opening this to start a discussion on whether we should link statically against the MSVC runtime. Doing so would remove the requirement of having the MSVC redistributable installed and would make it easier to have a true portable package. However, we won't get security updates and other stuff when the redistributable is updated, but would have to recompile and release a new version. It would also increase file size, but I'm unsure of how much.

What do you think?

**Comment by DoumanAsh** [comment]
Generally i think static linkage is not a problem in especially when size is not such a big deal.
For updates... i don't really remember: were there any critical updates?
Besides new version would be released from time to time so eventually new MSVC runtime would get into for user.
So no problem with static linking, but it is nice to have no dependency on Windows as it is always bothersome...

**Comment by vktr** [comment]
Closed in #224

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/issues/43
