### ISSUE TITLE
Portuguese (Brazil) Translation 

### ISSUE THREAD

**Issue by joaolgs** [picotorrent/picotorrent#204]
Lang_id: 1046
Lang_name: Portuguese - Brazil

[1046.json - compressed.zip](https://github.com/picotorrent/picotorrent/files/167719/1046.json.-.compressed.zip)

**Comment by vktr** [comment]
Would you mind to try and open this as a pull request instead? [Here's a handy guide on how to do it from the browser](https://help.github.com/articles/github-flow-in-the-browser/).

**Comment by vktr** [comment]
Closing this since #205 was merged.
