### ISSUE TITLE
Add statistics for total upload, and share ratio

### ISSUE THREAD

**Issue by VoodaGod** [picotorrent/picotorrent#210]
One thing i miss from picotorrent is being able to see how much i have seeded a torrent

**Comment by vktr** [comment]
Perhaps this would fit in a statistics tab in the torrent details?

**Comment by VoodaGod** [comment]
that's exactly where i would expect it to be ;)

**Comment by zp** [comment]
Maybe something similar to Transmission's Qt client, change the `Overview` tab to have a rundown of the torrent's info, and then move the 'limits' options on the current overpage to a new `Options` tab

Transmission example

![](http://i.imgur.com/SSLUJjf.png)

**Comment by svnpenn** [comment]
:+1:

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/pull/239

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/issues/242

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/issues/243

**Comment by wefalltomorrow** [comment]
> Perhaps this would fit in a statistics tab in the torrent details?

Any chance for total uploaded to be added as a column as well?
