### ISSUE TITLE
Only 15 torrents "stalled (seeding)", others Queued?

### ISSUE THREAD

**Issue by Wyall** [picotorrent/picotorrent#226]
It would be nice to change how many torrents are actively trying to seed. At the moment this numbers seems to be 15

**Comment by vktr** [comment]
Hi! Great suggestion :smile:

**Comment by Wyall** [comment]
A "workaround" seems to be to use "Resume (force)", then everything is seeding

**Comment by vktr** [comment]
Yeah, that takes to torrent out of the libtorrent queue manager.

**Comment by vktr** [comment]
@Wyall See here for information on how to change the limits, http://docs.picotorrent.org/en/latest/configuration.html (only available in v0.10)

**Comment by Wyall** [comment]
@vtr thanks!

**Comment by ImAnnoying** [comment]
Would be nice to be in Preferences though - if I hadn't found this thread, I probably would never have found where to change it...
