### ISSUE TITLE
Percentage in torrent list hard to see

### ISSUE THREAD

**Issue by vktr** [picotorrent/picotorrent#228]
The percentage text overlay on the progress bar in the torrent list can be hard to see - we should see if there's a possibility to make this easier, such as showing white text on the green and black on white.

**Comment by Blahenzi** [comment]
There's also the issue of the text not being aligned properly on Windows 8.1.
![percentage](https://cloud.githubusercontent.com/assets/18188292/14173435/2179c014-f73e-11e5-94ac-9881914a6296.PNG)

**Comment by vktr** [comment]
Odd, it doesn't have that alignment issue when running on a high DPI display. Will have to investigate, thanks!

**Comment by vktr** [comment]
Closing this since the alignment issue was fixed in #229 and changing colors based on progress background may be more work than its worth.
