### ISSUE TITLE
Peer id policy

### ISSUE THREAD

**Issue by spaghetti2514** [picotorrent/picotorrent#233]
Most private trackers have a client whitelist that helps to dissuade people from using known bad clients. In order to be placed on the whitelist however, a client needs to uniquely identify itself in its peer id. From a brief glance at the source code, it appears that picotorrent by default presents itself using libtorrent's client ID, and only presents itself as picotorrent if an option is changed.

The ideal case here would be for picotorrent to only ever present itself as picotorrent, so staff of private trackers can whitelist it. Otherwise, picotorrent's client ID is likely to not be whitelisted, which would discourage some potential users from switching to it.

Additionally, it would be nice if the client ID was listed in the readme or the docs so that staff searching for the ID for whitelisting purposes can find it without pouring through the code.

**Comment by vktr** [comment]
Hi! Yes, I agree that we should permanently change to always use the PicoTorrent peer ID. However, in doing so, the trackers that actually whitelist the libtorrent default ID will not be accessible.

Perhaps we need to do it anyway - I have no problem with doing so, but others might.

Looking for input on this one, @zp, @patriksvensson, @enr00ted, @VoodaGod, @DoumanAsh, @kosmodrey, and many others.

**Comment by spaghetti2514** [comment]
As far as I'm aware, most private trackers do not whitelist libtorrent's ID, as it's a library and not a client per say.
Getting tracker staff to add the ID of a compliant client is very simple and common, while getting them to add libtorrent's ID will probably be met in outright refusal.

I don't think you'll actually run into any instances of dropping libtorrent's ID leading to you no longer being whitelisted, but if you're still concerned about that, a good compromise might be setting picotorrent's ID as the default for a while, and then remove the option to switch to libtorrent's ID later. This would allow staff to start whitelisting the client and allow your users to switch to a fallback ID during the transition if necessary.

**Comment by DoumanAsh** [comment]
I believe user should have right to hide its client's id.

>I don't think you'll actually run into any instances of dropping libtorrent's ID leading to you no longer being whitelisted,

I don't believe getting unique ID will have any effects too ;)

Regardless it seems t be a minor thing to me as long as user is able to retain control of its client ID

**Comment by spaghetti2514** [comment]
>I believe user should have right to hide its client's id.
They do so long as the client remains open source. Hard coding IDs at build time is just a general policy that goes hand in hand with whitelisting that discourages non-savvy users from using clients meant for cheating or that are a danger to the swarm.
>I don't believe getting unique ID will have any effects too ;)
You believe incorrectly. Defaulting to libtorrent's ID and allowing a switch to picotorrent's ID will result in neither being whitelisted and the client being unusable on most private trackers. Defaulting and sticking to picotorrent's ID allows for that ID to be whitelisted, making the client actually usable.

Additionally, if "retaining control over its client ID" refers to setting it arbitrarily at runtime, then picotorrent is already incapable of this as far as I can tell. If it refers to setting it arbitrarily at build time, then nothing will be different after this change. If your definition of "retaining control of its client ID" refers very specifically to having an option of picking between exactly two predetermined IDs at runtime, then I think you should justify why that's at all significant a little further.

**Comment by DoumanAsh** [comment]
Is peer ID set at compile time? I didin't look much into code but i thought it has been done during initialization and because of that i believe it could be part of settings?
But if i'm wrong then sorry

>You believe incorrectly. Defaulting to libtorrent's ID and allowing a switch to picotorrent's ID will result in neither being whitelisted and the client being unusable on most private trackers. Defaulting and sticking to picotorrent's ID allows for that ID to be whitelisted, making the client actually usable.

And why do you need whitelist?
It is not like they would ban you if you is not in it?

**Comment by vktr** [comment]
@DoumanAsh There is an option in libtorrent to use anonymous mode, which randomizes the peer ID and other things.

Trackers wouldn't ban a client not in the whitelist, but we wouldn't be able to announce to them which means no peers, which in turn means no downloading 😄 

I'll let this issue sit here for a few days to let people voice their opinions, but I'm leaning towards changing the peer ID to our own and removing the libtorrent one.

**Comment by spaghetti2514** [comment]
@DoumanAsh
>And why do you need whitelist?

I'm not sure if you're asking why trackers need whitelists, or why users' clients need to be on the whitelist. Private trackers use them because they've been shown to significantly decrease stat cheating, even if they aren't a perfect solution. Clients need to be on the whitelist because the tracker will refuse to communicate with them if they aren't, and the user will switch to a different client.
>It is not like they would ban you if you is not in it?

Your account won't be banned, but not being on the whitelist is effectively a ban on the use of the client.

@vktr 
>There is an option in libtorrent to use anonymous mode, which randomizes the peer ID and other things.

Does picotorrent use this? I have not delved deeply into the code, but I thought picotorrent defaults to libtorrent's normal ```-LT-*``` ID, and has a single toggleable option to switch to picotorrent's ```-PI-*``` ID

**Comment by vktr** [comment]
@spaghetti2514 Yes, that is correct.

We do not use the anonymous flag, but it's something I would want to add to the configuration.
