### ISSUE TITLE
Convert PicoTorrent to a Universal Windows Platform (UWP) app?

### ISSUE THREAD

**Issue by MadSpindel** [picotorrent/picotorrent#240]
I believe it should be possible to convert PicoTorrent to a UWP app:
https://msdn.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root

It could then be distributed in the Windows Store and use automatic update facilities.

**Comment by vktr** [comment]
It's probably doable and would be quite cool to do, however by doing so we leave those who don't run Windows 10 (I'd rather not maintain two code bases). We should investigate this however, and see what would be required.

**Comment by vktr** [comment]
Closing this since I don't think there's enough interest in a single UWP application.
