### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by svnpenn** [picotorrent/picotorrent#242]
Please consider a new release. Currently I am using http://github.com/Eoinocal/Halite, but now that
#210 is fixed I might switch over

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/pull/239

**Comment by vktr** [comment]
Hi! Yes, a new release is planned and will arrive in the coming days.

**Comment by vktr** [comment]
@svnpenn Also, we have a Gitter channel (https://gitter.im/picotorrent/picotorrent) if you have any questions about closed issues or pull requests (I see you've made a lot of cross-issue references).

**Comment by svnpenn** [comment]
@vktr please reopen this issue, as it is not resolved at this time?

**Comment by vktr** [comment]
Hi! If you want to use the fix you mentioned, you can download the latest
develop-build from the AppVeyor artifacts. Just follow the green build icon
on the readme page.

**Comment by svnpenn** [comment]
Aha, thanks! http://ci.appveyor.com/project/picotorrent/picotorrent/build/job/f3s5d15gt59vjx29/artifacts
