### ISSUE TITLE
Add WebTorrent support

### ISSUE THREAD

**Issue by milkey-mouse** [picotorrent/picotorrent#255]
[WebTorrent](https://webtorrent.io) is a version of the BitTorrent protocol that works over WebRTC. They already have a beta of [a desktop client](https://webtorrent.io/desktop) for it. By adding support for WebTorrent, you could seed on there too.

**Comment by smaragdus** [comment]
WebRTC is a privacy disaster. No browser with WebRTC enabled is safe.

**Comment by vktr** [comment]
@milkey-mouse The actual BitTorrent protocol is handled by Rasterbar-libtorrent, and they have an open issue for WebTorrent support here, https://github.com/arvidn/libtorrent/issues/223. When that issue is merged, I'll make sure to do the necessary work in PicoTorrent.

Putting this on hold for now.

**Comment by yuri-sevatz** [comment]
@smaragdus I agree with your stance on privacy.  Though, strictly speaking from a protocol perspective, WebRTC is a sound protocol for NAT-T among other things **_when implemented securely_**, even though that's something that the IETF and W3C are absolutely butchering.

That said, webtorrent on top of WebRTC is a protocol like any other.  Implementing it in things that are not web browsers can be made more secure given that we're dealing with a protocol library and not another $%&'d W3C ui! :+1: 

rb_libtorrent already have options for things like UPnP on/off and it's always been very respective of people's privacy concerns.  We can do things like WebRTC ICE, or sticking to the default routes' external IPs only just like some browsers have in their more hidden settings.

Easily good options to have.  Once rb_libtorrent starts getting reviews up I can see this being a good thing to critique.
