### ISSUE TITLE
Did you change anything?

### ISSUE THREAD

**Issue by 4nderss** [picotorrent/picotorrent#258]
After 0.8 I have issues downloading to an encrypted share. The archive gets corrupted and I have to download to a non encrypted drive and copy to the encrypted share by hand. This started with the 0.9 update. To be honest I haven't tried any other torrent client (why would I now that I use the best?:)). But just wondering if anything has changed so I have to change :( 

Props on the work, really love the work!

**Comment by vktr** [comment]
Hi, the only thing changed with regards to file writing is that we updated Rasterbar-libtorrent (which is the library we use for the BitTorrent parts). Can you reliably reproduce this error?

**Comment by 4nderss** [comment]
How do you mean reproduce? It happends every download since after 0.8 when I download directly to my encrypted share.

**Comment by vktr** [comment]
I see. Is it a BitLocker encrypted drive?

**Comment by 4nderss** [comment]
Its an AES encrypted NAS share (Synology DS415+)

**Comment by 4nderss** [comment]
I just tried another torrent client and I got the same problem there, sonology must have done something in an update to my NAS. I think you can close this one.
