### ISSUE TITLE
Need to be able to enforce encryption and support blocklist

### ISSUE THREAD

**Issue by diwu1989** [picotorrent/picotorrent#259]
Two features are must haves to run safely on Comcast internet:
- encrypted packets
- loading auto-updated blocklist

both features are available in transmission right now
![image](https://cloud.githubusercontent.com/assets/380950/14941075/01a777b8-0f44-11e6-88f3-e922f73c5641.png)

**Comment by vdias** [comment]
+1... This is a essential feature this days...

**Comment by stepshal** [comment]
What about blocklist?

**Comment by vktr** [comment]
Blocklists hasn't made it into PicoTorrent yet, sorry.
