### ISSUE TITLE
Unhandled exception with some torrent files

### ISSUE THREAD

**Issue by jlneder** [picotorrent/picotorrent#270]
I am getting an unhandled exception when i try to open the torrent file attached to this issue. The torrent file is possible malformed, but this shouldn't happen even if it is so.
Some more data:
Unhandled exception at 0x00007FFDDDEC98FE (ucrtbase.dll) in PicoTorrent.exe: Fatal program exit requested.
[Outlander.S02E02.HDTV.x264-KILLERS[rartv].zip](https://github.com/picotorrent/picotorrent/files/256525/Outlander.S02E02.HDTV.x264-KILLERS.rartv.zip)

**Comment by vktr** [comment]
Thanks for reporting! Torrent files shouldn't be able to crash PicoTorrent.
