### ISSUE TITLE
Picotorrent crashes when changing DL speed settings while downloading

### ISSUE THREAD

**Issue by JeffreyH1989** [picotorrent/picotorrent#271]
Situation:

Downloading 1 or more torrent files. While downloading, you change the global limits (through preferences > downloads) and click ok.

Picotorrent then crashes. When you start picotorrent again, all the torrents you were downloading are gone and you have to re-add them.

Also, when you run Picotorrent in UAC mode, it looks like it's making another settings folders (I'm getting questions asked as it's running for the first time)

**Comment by JeffreyH1989** [comment]
To add, the crash only happens if you leave the dl or ul box EMPTY and then press ok. Looks like it's expecting a value and doesn't automaticly add a 0 when empty.

**Comment by vktr** [comment]
Would you mind opening another issue for the UAC part?
