### ISSUE TITLE
Different settings when using UAC

### ISSUE THREAD

**Issue by JeffreyH1989** [picotorrent/picotorrent#272]
When you start Picotorrent in UAC (WIndows 10, 1511), you get questions asked as if you are starting it for the first time.

I cannot repeat this since I do not have another Windows copy lying around

**Comment by vktr** [comment]
Do you mean the dialog which asks if you want to allow it in the firewall? Or the dialog asking if you are sure you want to run the application?

**Comment by vktr** [comment]
Also, if you are using a version of PicoTorrent from AppVeyor, these are not signed. Only the official binary releases on GitHub are signed.

**Comment by JeffreyH1989** [comment]
The dialog which asks if you want to run it the application. I'm using the official 0.10 and I tried running it as admin to see if the crash with speed settings still occurs.

**Comment by vktr** [comment]
The crash that occured for the DL/UL limits has been fixed, but not released.

I'm unsure if the UAC prompt is a problem or not. It seems as it is just Windows working as intended.

**Comment by vktr** [comment]
Closing this since I don't think the problem is with PicoTorrent - or at least, there's nothing we can do about UAC prompts.
