### ISSUE TITLE
Torrents added via magnet link will disappear from download list if PicoTorrent is exited before meta data was downloaded

### ISSUE THREAD

**Issue by warhuhn** [picotorrent/picotorrent#280]
If i add a torrent via magnet link and close PicoTorrent before the meta data information was downloaded, the torrent will be missing from the download list the next time i start PicoTorrent.

Steps to reproduce:

1. Add Magnet link torrent
2. Immediately close PicoTorrent
3. Start PicoTorrent again
4. Torrent added in Step 1 is missing from the download list.

**Comment by vktr** [comment]
Do you add magnet links from the menu or by clicking a magnet link in the browser?

**Comment by warhuhn** [comment]
I add them via the browser.

**Comment by warhuhn** [comment]
The problem won't occur when adding them via the menu.

**Comment by vktr** [comment]
I see, thanks! I'll have a look.
