### ISSUE TITLE
Number of magnet links via menu is limited

### ISSUE THREAD

**Issue by vBm** [picotorrent/picotorrent#282]
At the moment you can paste up to 7 magnet links into field but only 5 will be parsed and added into queue.

![2016-05-13_01-48-12](https://cloud.githubusercontent.com/assets/80596/15233940/eccc5422-18ac-11e6-9133-07b35acb8918.png)

![2016-05-13_01-52-28](https://cloud.githubusercontent.com/assets/80596/15234000/8158f136-18ad-11e6-9e5d-f83759fb7374.png)

Can this limit be lifted? Unlimited would be nice for times when you want to import whole season of some show or even multi seasons.

**Comment by vktr** [comment]
Hm, I can't reproduce this... If a magnet link is invalid, PicoTorrent will not try to load it. So it seems two of the links you're trying to add are invalid, or there's a bug in the magnet link handling.

Would you mind pasting the above magnet links?

**Comment by vBm** [comment]
Ok, I've tried it again with [another set of magnet links](https://gist.github.com/vBm/5ccbe0fde350cd4ba43d40217a6a4e9c) and similar thing happened.

Upon first adding, parser shows 0/7 and quickly finishes up to 6/7 and then it hangs it seems (passed more than 5 minutes and still didn't finished). So i've terminated it via clicking close button. Ended up with no magnet links added to the list at all.
After that i've tried again to add the same set of links and it finished adding all of them under 5 seconds. 

Using [3rd set of links](https://gist.github.com/vBm/7854259921be35957d42032508351d43) shows issue that was initially reported (only 5 magnets are parsed and again it hangs at 4/5).

Since i've noticed that there's 3 announce url's available for links here, i've decided to cut down to just two. This resulted in being able to parse 6 links, so i've cut down to just one announce url and now PT can parse all 7 links.
I've also tried removing just `&dt` and leaving all 3 of `&tr` and that resulted in being able to parse only 6 links.

To me this seems like a limitation in magnet parser.

Hope i was able to explain the problem correctly.

**Comment by vktr** [comment]
I've identified the issue with losing links - I used a hard limit on the length when reading from the text field.

The reason it might take a while is because PicoTorrent searches the DHT for the torrent files before showing the add torrent dialog. I don't know why it takes so long and then works instantly if trying again though... 

I'll open a PR for the length issue.

**Comment by vBm** [comment]
Nice, thanks.
It's really nice to be able to import complete seasons via magnets.
