### ISSUE TITLE
DHT, Local Peer Discovery, Peer Exchange manipulation.

### ISSUE THREAD

**Issue by mutt3x** [picotorrent/picotorrent#293]
A client wide option to enable/disable such.
When a new torrent is added it will have thouse set settings.

A torrent only option to enable/disable such.
This is a individual torrent only setting for such.

This feature is highly usefull for privtrackers since they dont like thouse.

Off-topic
manually update tracker thingy... button...
also something to re-check the torrent and better add torrent file checking.

Overall a very amazing project you have going on. Do not deviate from your path. I am planning to use this over the ancient artifact that is uTorrent 2.2.1 someday in the near future. Hopefully the private trackers are going to allow it.

May i also say that it works amazing with largeee torrents (2TB, 5k filelist). Almost instant open.
Hope anything of this helps.

**Comment by vktr** [comment]
I've been in contact with a few private trackers and what they say is that when users start to request a client to whitelist, they will look into it. So if you're a member of a private tracker where PicoTorrent is not allowed, please make a request and point them in our general direction (Gitter, e-mail, Twitter, etc) :smile:

**Comment by vBm** [comment]
Pretty much all clients should respect "[private](http://bittorrent.org/beps/bep_0027.html)" flag from torrent itself. If that's the case, even when DHT is enabled globally it will have no effect on that particular .torrent

**Comment by vdias** [comment]
+1... I'm using public trackers this days and this feature is essential.
