### ISSUE TITLE
Add parsed magnets as soon as meta is downloaded

### ISSUE THREAD

**Issue by vBm** [picotorrent/picotorrent#296]
This is somewhat related to #280. 

I've tried to add 4 torrents via magnet links, 3/4 were parsed instantly while 4th one is stalled (been like that for last 5 mins or so, could be that there are connection issues or something else). If I click on X to terminate the parsing, even those 3, successful ones are lost as well.

![2016-05-31_13-39-02](https://cloud.githubusercontent.com/assets/80596/15673219/84c229fa-2735-11e6-90b2-3f509ffd72f5.png)

Magnet parser shouldn't wait for all of the magnet links to parse and download metadata before adding them to the list of 'active' torrents. IMHO it should add 'em as soon as metadata is received. That way we'll prevent loss of already viable torrents for download. It's easier to re-add just that one instead of all of 'em.

edit: forgot to mention that i'm using latest available artifact from AppVeyor.

**Comment by vktr** [comment]
Agreed - the easiest way to fix it would be to show the add torrent dialog for the magnet links that were actually downloaded and perhaps show an alert for the ones which weren't. This lets the user add the successful ones with the option to retry the failed ones later.

**Comment by vBm** [comment]
Yes, that would be great if it's doable.
Thanks :)

**Comment by vktr** [comment]
Fixed in #324.
