### ISSUE TITLE
Migrating seeded torrents

### ISSUE THREAD

**Issue by kilves76** [picotorrent/picotorrent#308]
Easiest way to migrate seeded torrents to Pico when .torrent files are in folder A and torrent datas in folder B, possible without recheck or popup windows etc?

Made this an issue since couldn't find anything in the documentation.

**Comment by vktr** [comment]
You'd need a recheck at least, and I don't think there's an easy way to do this for multiple torrents. Perhaps if you change the default download directory to where your downloaded data is, then add all your torrents. This should add them with the default save path to where their data is.
