### ISSUE TITLE
crash when opening torrent file

### ISSUE THREAD

**Issue by jlneder** [picotorrent/picotorrent#310]
Picotorrent crash when opening this torrent file.
[318912e5f0dd3bb20649935a71cf68676da86b08.zip](https://github.com/picotorrent/picotorrent/files/312328/318912e5f0dd3bb20649935a71cf68676da86b08.zip)

**Comment by vktr** [comment]
Sorry for the late answer, been on vacation :smile: I'll have a look as soon as possible.

**Comment by vktr** [comment]
I've tried it on the latest sources and PicoTorrent shows an error dialog saying there's an incorrect number of piece hashes. No crash, though.

Also, I tried opening it in qBittorrent and while it shows the dialog where you can prioritize files, it crashes when trying to add the torrent to the session.

I'd say PicoTorrent does the correct thing here.
