### ISSUE TITLE
Dr. Memory reports memory leaks

### ISSUE THREAD

**Issue by DoumanAsh** [picotorrent/picotorrent#312]
Been investigating valgrind's alternative for Windows and decide to try out Dr. Memory.
Seems to be very like valgrind(look into DrMemory-PicoTorrent.exe.1064.000):
https://drive.google.com/open?id=0B7w3ZGc8CTgqenBFSEpUQldQd28

There are several definite leak of memory so it might be worth looking into

**Comment by vktr** [comment]
Cool! :smile: Tagging this as a refactor since that fits the best I think.

Thanks for the report!

**Comment by DoumanAsh** [comment]
Np, there are multiple issues and i'll might too look into it myself if there will be time for me

**Comment by DoumanAsh** [comment]
Hello, i'm back with memory leaks for PicoTorrent 0.12

https://gist.github.com/DoumanAsh/588a09c05a7c88bb66808e6ab22068a4

Lots of stuff...
I tried to perform as much actions as possible

**Comment by vktr** [comment]
I'm closing this - can't find any obvious leaks in the latest version. Feel free to open another issue if you think there's something tangible to work on 😄
