### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by birkoffe** [PicoTorrent/PicoTorrent#317]
Picotorrent crash on download multiple files in .torrent (more 5 files).
It's looks like download speed drop to zero and application crashed.
With .torrent contain less 5 files crash don't reproduce. 
[appcrash.zip](https://github.com/picotorrent/picotorrent/files/407129/appcrash.zip)

**Comment by vktr** [comment]
Thanks for the report! I'll have a look.

**Comment by vktr** [comment]
I can't reproduce this issue. If you encounter this again, feel free to open another issue.
