### ISSUE TITLE
Losing the ongoing torrent on PicoTorrent crash

### ISSUE THREAD

**Issue by rilut** [picotorrent/picotorrent#318]
When my PicoTorrent crashes, the ongoing torrent is also lost. Happened two times on me with the same torrent. The crash reasons:

1. not sure
2. after opening the ongoing file with Media Player Classic

Because the torrent is lost. I need to reopen the .torrent again and the progress is restarted from 0% again

**Comment by vktr** [comment]
I've done a few fixes to keep torrents even if PicoTorrent crashes, however I may have missed one or more cases 😄 Sorry about that.

Does the torrent restart from 0% even if you add it and choose to download it to the same location as before? In that case it should check the existing files.

**Comment by rilut** [comment]
@vktr no that's totally fine, you're a one-man army after all :smile:  I see that it's hard to diagnose a random error. I wish there was some relevant log that I can send.

Eh I'm sorry it's a magnet link rather than a .torrent file. Oh no **you're right, it's continuing itself**. At the first crash, maybe I didn't notice it because it was < 10% completed. Sorry. You have a nice day
