### ISSUE TITLE
Unable to install the Visual C++ redistributable

### ISSUE THREAD

**Issue by Tieria-Shirin** [picotorrent/picotorrent#320]
One or more issues caused this set up to fail, Please fix the issues and try the set up again. Error code 0x80070002 the system can not find the file specified

**Comment by vktr** [comment]
It is the C++ redistributable which fails - Microsoft  has removed the old file for some reason.

You can install it manually from here (https://www.microsoft.com/en-us/download/details.aspx?id=52982), then reinstall PicoTorrent 😄

**Comment by vktr** [comment]
Fixed in #324.
