### ISSUE TITLE
Details dialog

### ISSUE THREAD

**Issue by steelunicorn** [picotorrent/picotorrent#323]
Not sure what happened, but after some time of using picotorrent i got this view of torrent details window. And it looks very funny when I move this window >_<

![image](https://cloud.githubusercontent.com/assets/20414473/18036499/6f13a2a2-6d74-11e6-896c-c331cf726726.png)

**Comment by vktr** [comment]
Very strange - does the problem persist if you restart PicoTorrent?

**Comment by steelunicorn** [comment]
Nope,  after restart problem gone, and I can't reproduce it yet.

**Comment by zp** [comment]
I had something like this happen when I opened the files tab on a torrent with a lot of files on it (varies, but over 5000 will always trigger it), I narrowed it down to the file extension icons that was causing it (I built a copy with it disabled, and the problem stopped)

From what I've seen, the newest build after the WTL refactor doesn't have the icons at the moment, so you could try that build and see if it keeps happening.

**Comment by vktr** [comment]
Strange - as @zp said the WTL refactor removed the icons in the files tab so you shouldn't have an issue there. I'll remember to test with +5k files when adding back the file icon feature :smile: 

Thanks everyone! Considering this closed for now.
