### ISSUE TITLE
After system crash, all torrents gone

### ISSUE THREAD

**Issue by mica** [picotorrent/picotorrent#329]
Looks like this issue is still with us. When my power went out, Picotorrent lost all its torrents.

**Comment by vktr** [comment]
Can you check `C:\Users\<username>\AppData\Local\PicoTorrent\Torrents` and see if it contains both `.torrent` and `.dat` files.

**Comment by mica** [comment]
Yes, it does.

**Comment by vktr** [comment]
Hmm, PicoTorrent should load the torrents from that directory. Are you running the portable or installed version?

**Comment by mica** [comment]
Installed version, via Chocolatey.

**Comment by vktr** [comment]
I'll need to run some tests. It should load the torrents in that directory, though.

**Comment by vktr** [comment]
I tried ending the process in a few different apocalyptic ways but PicoTorrent still loaded the torrents in the `Torrents` directory. This is for the latest `develop` version, though.

Considering this fixed in the next version, but I'm sorry you have issues with the current one.
