### ISSUE TITLE
French translation show non supported caracters

### ISSUE THREAD

**Issue by TechnoGreg** [picotorrent/picotorrent#331]
I found the French language file on Github, I did copy and paste it on a blank *.txt file and save it with "1036.json" name, and ANSI encoding.
When setting language to "French", interface is showing up "non supported caracters".
![french](https://cloud.githubusercontent.com/assets/22304655/18646592/97065fb2-7eb2-11e6-8e35-befc4f0c9cb9.png)
Did I missed something ?

**Comment by vktr** [comment]
It needs to be saved as UTF-8.

**Comment by TechnoGreg** [comment]
I tried it 'cause I have some basics on coding and things, but the software don't show up anymore.
Not even process is running.

**Comment by vktr** [comment]
The easiest way is to download the file directly from the repository, https://raw.githubusercontent.com/picotorrent/picotorrent/develop/lang/1036.json.

**Comment by TechnoGreg** [comment]
It worked that way, thx, but when i'm opening the file, specials chars are strangely displayed in LibreOffice, don't understand why.
But the most important, it's working fine, thx vtkr
