### ISSUE TITLE
Install Visual C++ only when needed

### ISSUE THREAD

**Issue by svnpenn** [picotorrent/picotorrent#339]
I have noticed that the PicoTorrent installer will also install
*Microsoft Visual C++ 2015 Redistributable* if it is not already installed.

This is helpful, but not always necessary. As long as MSVCP140.dll and friends
are available on the PATH, Visual C++ does not need to be installed.

I found this out because Firefox now bundles these like so:

    C:\Program Files\Mozilla Firefox\msvcp140.dll

so if you have Firefox installed and on the PATH, PicoTorrent will use these
shared libraries. Please only install Visual C++ if it is not installed, AND not
on the PATH, thank you.

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/issues/43

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/issues/195

**Comment by vktr** [comment]
Hi! First of all, *please* stop resurrecting closed issues.

Regarding this issue - this will not be fixed. PicoTorrent installs the Visual C++ runtime as recommended by Microsoft and will continue to do so. In your example, PicoTorrent would rely on the user keeping Firefox installed just to keep PicoTorrent running - if the user uninstalls Firefox then PicoTorrent would break.
