### ISSUE TITLE
Exit command does not terminate program

### ISSUE THREAD

**Issue by svnpenn** [picotorrent/picotorrent#340]
I ran a Git Bisect and came up with this:

~~~
3ccea84e3fe413ca4f3e4047cc5ea1a9863a6c04 is the first bad commit
commit 3ccea84e3fe413ca4f3e4047cc5ea1a9863a6c04
Author: Viktor Elofsson <viktor@viktorelofsson.se>
Date: Thu, 15 Sep 2016 15:34:57 +0200

    Major WTL refactor (#324)
~~~

http://github.com/picotorrent/picotorrent/commit/3ccea84e (warning 7 MB page)

Author @vktr, all builds from this one on do not respond to the Exit command.
The GUI disappears, tray icon disappears, but process is still running.

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/pull/324

**Comment by vktr** [comment]
I cannot reproduce this. PicoTorrent exits gracefully both with and without torrents.

Sometimes it takes a few seconds for the process to exit when you have active torrents, though. This is normal.

**Comment by svnpenn** [comment]
@vktr this is in fact a problem. I reproduced this on a pristine virtual machine

**Comment by svnpenn** [comment]
@vktr hm it seems to be working for me now, I will do more testing

**Comment by svnpenn** [comment]
@vktr I have found the culprit. Somehow this registry value was getting set:

    Windows Registry Editor Version 5.00
    [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers]
    "C:\\Program Files\\PicoTorrent\\PicoTorrent.exe"="DISABLEUSERCALLBACKEXCEPTION"

Deleting this value fixes the issue.
