### ISSUE TITLE
Empty torrent list

### ISSUE THREAD

**Issue by birkoffe** [PicoTorrent/PicoTorrent#344]
After update 0.10x64 to 0.11x64 I got empty torrent list.

**Comment by disfated** [comment]
The same...

**Comment by vktr** [comment]
That's odd. I'll have a look. Do you have any files in the `Torrents` directory? Located at `C:\Users\<username>\AppData\Local\PicoTorrent`?

**Comment by birkoffe** [comment]
Yes, I have.
If back install 0.10 everything ok.

**Comment by vktr** [comment]
Sorry for this - I've released v0.11.1 which fixes this issue.
