### ISSUE TITLE
Weird naming of Labels

### ISSUE THREAD

**Issue by detrophy** [PicoTorrent/PicoTorrent#345]
- "amp_extensions" - _Main window_
- "move_completed_downloads" and "only_move_from_default_save_path" - _Download tab_
- "require_encryption_incoming" and "require_encryption_outgoing"  _Privacy tab_
- "privacy"-tab - _First letter is lowercase, which should be uppercase_

**Comment by vktr** [comment]
Sorry, these are missing translations. I'll add them to the next version 😃

**Comment by vktr** [comment]
Which language are you seeing this?

**Comment by detrophy** [comment]
German. Thanks for fixing this!

**Comment by vktr** [comment]
Ping @VoodaGod 😄 German is not my strong suit.

**Comment by VoodaGod** [comment]
i'll check the now strings out ;)
