### ISSUE TITLE
Numerous initial connections

### ISSUE THREAD

**Issue by rodboev** [PicoTorrent/PicoTorrent#346]
Why does PicoTorrent make about 50-75 outgoing connections on initial startup without any torrents loaded? uTorrent makes none

**Comment by vktr** [comment]
It could be the DHT and LSD doing their thing. I'll have a look :)

**Comment by vktr** [comment]
Seems like the DHT and LSD doing their thing. If you want, you can disable the DHT and LSD functionality.

http://docs.picotorrent.org/en/latest/configuration.html#advanced-settings
