### ISSUE TITLE
"Pin to taskbar" is gone

### ISSUE THREAD

**Issue by dertuxmalwieder** [PicoTorrent/PicoTorrent#348]
In PicoTorrent 0.11.1 on Windows 10 x64, the application doesn't have a "Pin to taskbar" menu item anymore. :(

**Comment by vktr** [comment]
Sounds odd - we don't do anything special to have it there. Let me check.

**Comment by vktr** [comment]
<img width="294" alt="screenshot 2016-11-06 14 17 20" src="https://cloud.githubusercontent.com/assets/1491824/20038012/dd96d6e8-a42b-11e6-80bf-5363c2ba64c7.png">

I cannot reproduce this in v0.11.1 - would you mind reinstalling and check again?

**Comment by dertuxmalwieder** [comment]
Gone after a reboot. Weird. Thanks!
