### ISSUE TITLE
Opt-in/Opt-out User-agent

### ISSUE THREAD

**Issue by rain2reign** [PicoTorrent/PicoTorrent#353]
Is there a way to opt-in and/or opt-out the masking of a user-agent, peer-id and/or general fingerprinting? 

This to reduce the peer-id and general torrent fingerprinting. More and more companies and (just) trackers are more interested in tracking your fingerprint, rather than just the essentials. More of a luxury feature! I used to use qBittorrent and it's a feature within it i really like for one owns privacy. Might be a tiny bit, but a gain is a gain, nonetheless i do realize, however that ip is still given out. In qBittorrent it's called 'Anonymous mode' (https://github.com/qbittorrent/qBittorrent/wiki/Anonymous-Mode). 

And maybe a gui(extra tab) for the advanced settings. Makes the client more user-friendly, rather than editing the Picotorrent.json file. I can imagine that, even though it's an incredible clear documentation on your website about, there might still be users whom are not (completely) comfortable editing files, they have no knowledge of. :) 

I stepped over from qBittorrent to Picotorrent and never looked back! Great job! 👍

**Comment by vktr** [comment]
I thought we had that already, but seems like I'm mistaken 😄 I'll add a setting to the `PicoTorrent.json` file for the next release. Anonymous mode would then work the same as qBittorrent since we both build upon Rasterbar-libtorrent.

A GUI for the advanced settings may be added in a future release, but it is not a priority right now.

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/issues/79

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/pull/355

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/issues/513
