### ISSUE TITLE
Torrents and magnets not loading when proxy enabled

### ISSUE THREAD

**Issue by rain2reign** [PicoTorrent/PicoTorrent#360]
Whenever i use a proxy server, doesn't matter which type in which used SOCKS5 (with credentials), all torrents or magnets added to PicoTorrent doesn't seem to load. At first i thought it might be my proxy settings, so i disabled them, as expected the torrents work (more or less; see explanation below). Then i tried adding them manually through the PicoTorrent interface itself, no success. Lastly i tried qBittorrent with the same proxy settings filled and enabled, the problem doesn't seem to exist with that client.

The only way i am able to convert back to a working PicoTorrent is by...:
              1. ... emptying the credentials, type and uncheck all boxes in preferences (related to proxy).
              2. ... close and go to "C:\Users\\[username]\AppData\Local\PicoTorrent" and delete 'session.dat'.

I use the servers from NordVPN for my proxy (with credentials) over SOCKS5, in case it might make a difference. I added the log files, just in case.
[Logs.zip](https://github.com/PicoTorrent/PicoTorrent/files/595912/Logs.zip)

**Comment by vktr** [comment]
Thanks for the report - I'll have a look!

**Comment by Tieria-Shirin** [comment]
please stop emailing me notification.s

**Comment by vktr** [comment]
@Tieria-Shirin If you do not want to be notified, change your 'Follow' settings for the repository,

![image](https://cloud.githubusercontent.com/assets/1491824/20382547/a2cd1ec6-acac-11e6-9615-599e062de5ae.png)
