### ISSUE TITLE
Add little useful tweaks to app

### ISSUE THREAD

**Issue by duke4e** [picotorrent/picotorrent#364]
- ~~remove torrent from list with DEL key~~
- add option to automatically add torrent (without the prompt window)
- add full/sparse allocation as an option in preferences
- ~~add option to start maximized~~ (#365)

I'll edit this post if I remember anything else.

edit:
- ~~ctrl-a to select all torrents~~

**Comment by vktr** [comment]
Removing torrents with the `Delete` key was actually fixed an hour or so ago, see #363 😄 

I'll see what I can do about the others!

**Comment by duke4e** [comment]
Thanks for a quick response, and than you for your awesome torrent client!

**Comment by vktr** [comment]
I see the edit, and Ctrl+A was also fixed in the PR I mentioned! I'll put up some documentation on keyboard shortcuts.
