### ISSUE TITLE
Improve torrent add dialog

### ISSUE THREAD

**Issue by persona5** [PicoTorrent/PicoTorrent#366]
Would love to be able to include/exclude folders in torrent.

Also, clicking on "Name", "Size", and "Priority" column headings does not sort items, as I expected. Same problem is in "Details->Files" window.

UX things: 
If you add torrent and deselect all files, it still adds it into the DL list, showing that it has downloaded 100%. Accidently did this, took me a few minutes to figure out why it says 100% and files are not present. 
Maybe it should warn user to select at least one file, as downloading no files does not make sense.

Similar issue with add magnet link dialog - if you do not paste magnet and click "Add", dialog will never complete. Probably shoud warn user if no vaild magnets found.

Regexps: are they pcre compatible? Do they apply to only the name of file, or to full path with dirs and subdirs? Do they work with non-english filenames? 
So far I only got them to work for file extensions, probably doing something wrong?

**Comment by vktr** [comment]
Hi!

Great suggestions. I'll definitely fix sorting, as well as add a warning if no files are selected.

The regular expression is ECMAScript compatible, and should work on the complete path of the file within the torrent, eg. `some/path/debian.iso`. I'll add some more documentation on that as well.

**Comment by vktr** [comment]
Closing this as most of these are fixed now, except for the one where you deselect all files.
