### ISSUE TITLE
Name in Tabs messed up after restart

### ISSUE THREAD

**Issue by h4aLkon** [picotorrent/picotorrent#371]
Hello, using the last version (PicoTorrent 0.11.1) on Windows 8.1, 32-bit on a 64-bit processor. I noticed that after PicoTorrent  restart, the labels on tabs (Name, Size, Status, Progress, ETA...etc..) are reordering by themselves no matter what. If the default order is from left to right ---> Name, Size, Status, Progress, ETA, DL, UL.., if I close PicoTorrent and restart it, the tabs start from the right to left side like this:

- UL, DL, Progress, Status, Size and Name.

Thanks for PicoTorrent and keep up the good work!

**Comment by vktr** [comment]
Is it just the column header labels that have changed, or also the content of each column?

**Comment by h4aLkon** [comment]
Is the content together with its column:

**Before:**
http://i.imgur.com/aPOe8Ok.png

**After restart:**
http://i.imgur.com/Pn37khl.png
