### ISSUE TITLE
"Add torrent(s)" window files table selecting+sorting trouble

### ISSUE THREAD

**Issue by gck43851** [picotorrent/picotorrent#375]
In the "Add torrent(s)" window, especially for multiple files torrents, when we select file/multiple files in the table with Shift+click or Ctrl+click, and then change the table sorting, Pico don't keep the selection of files but selection of table positions.
PicoTorrent v0.12.0.

**Comment by zp** [comment]
This also happens on the main torrent list, and on the file list on the details dialog. (I assume it's happening on any sortable list)

**Comment by khagaroth** [comment]
This also breaks other functionality, like checking/unchecking files, changing priority etc., where the changes are applied to the files based on the original order.

**Comment by vktr** [comment]
@zp I couldn't reproduce it in the main torrent list, however I do have a fix for the torrent file list in the Details dialog as well as the Add torrent dialog.

**Comment by 239** [comment]
> This also breaks other functionality, like checking/unchecking files, changing priority etc., where the changes are applied to the files based on the original order.

This is still broken, checking and changing priority applies to the original order after sorting the list of the "Add torrent" and "Files" dialogs.
