### ISSUE TITLE
PicoTorrent & Windows XP

### ISSUE THREAD

**Issue by c-sanchez** [PicoTorrent/PicoTorrent#379]
PicoTorrent don't works on Windows XP :(
this say "PicoTorrent.exe is not a valid Win32 application".
Can you fix this?

**Comment by vktr** [comment]
Hi! Awesome that you still run XP 😄 There is some work behind supporting XP since alot of the Windows APIs we build on came with Vista. I can't see us supporting XP right now, but perhaps in the future if we move to a client/server model and have the server support XP.
