### ISSUE TITLE
Save destination path

### ISSUE THREAD

**Issue by matjos** [picotorrent/picotorrent#39]
Would be nice if the choosen destination path would be saved for future torrents.

[edited]
With browse button.

**Comment by vktr** [comment]
You can change the default save path in `View -> Preferences`. This path is set as default path when choosing save path.

**Comment by matjos** [comment]
Nice, would be nice with a browse button there :)

**Comment by vktr** [comment]
:+1:

**Comment by patriksvensson** [comment]
Would also be nice if magnetic links just started to download without asking for a destination path.

**Comment by vktr** [comment]
@patriksvensson This should probably be a configuration option, but I agree that the behavior would be nice.

**Comment by matjos** [comment]
@patriksvensson that seems like a nother issue to me ;)

**Comment by patriksvensson** [comment]
@matjos Wasn't sure if it was this that you meant or not. My mistake :smile:

**Comment by matjos** [comment]
@patriksvensson its okey i forgive you. :dancers:
