### ISSUE TITLE
Open same torrent files multiple times

### ISSUE THREAD

**Issue by jsieler** [picotorrent/picotorrent#393]
You can open same file multiple times and it will appear there that much in the list. As far as you delete one, all will disappear an PicoTorrent crashes.

**Comment by vktr** [comment]
Thanks for the report! 😄

**Comment by DoumanAsh** [comment]
I reproduced this error, but got strange stack trace.

https://drive.google.com/drive/folders/0B7w3ZGc8CTgqTEg5a0hHdEdHcVk?usp=sharing
