### ISSUE TITLE
Adding magnet links can be really slow.

### ISSUE THREAD

**Issue by dertuxmalwieder** [picotorrent/picotorrent#395]
I noticed that, when directly comparing PicoTorrent to Tixati, it seems to take a very long time to add `magnet:` links to PicoTorrent. I haven't investigated what it does yet but sometimes it seems to be stuck at "0/1...".

**Comment by vktr** [comment]
I see - I'll take a look.

**Comment by dertuxmalwieder** [comment]
I found out that it only happens for torrents with "dead" trackers. Maybe a status label would already do the trick.

**Comment by vktr** [comment]
Is the progress bar not enough?

**Comment by dertuxmalwieder** [comment]
The progress bar does not tell my why there is no visible progress. ;-)

**Comment by vktr** [comment]
Which progress bar are we talking about? The one in the *Add magnet link* dialog, or the one in the torrent list view?

**Comment by dertuxmalwieder** [comment]
The one in the *Add magnet link* dialog where it says "0/1" most of the time.

**Comment by vktr** [comment]
Yeah, I don't know if we can put any more progress there... Rasterbar-libtorrent doesn't expose any progress for metadata downloads.

**Comment by vktr** [comment]
I think the only sensible thing we can do is to remove the add magnet link dialog and just let the magnet links show up as "Downloading metadata" in the torrent list view. 

That way we don't lock the UI while we wait for the metadata files to download.

What do you think?

**Comment by dertuxmalwieder** [comment]
Good idea. PicoTorrent should not have a wasted UI IMO.
