### ISSUE TITLE
Tray icon context menu incorrect position

### ISSUE THREAD

**Issue by lihas** [picotorrent/picotorrent#398]
**Operating system** : Windows 10

![150](https://cloud.githubusercontent.com/assets/1687568/21815105/831933e4-d781-11e6-87dc-67fe28981ab2.png)
![125](https://cloud.githubusercontent.com/assets/1687568/21815111/87ad9e04-d781-11e6-8b49-36d6a2f99ba6.png)

### Problem Description.

The context menu of the tray icon of Pico torrent gets improperly rendered when **DPI scaling** is done on **Windows 10**. Initially I though it is because Pico torrent is System-DPI aware, and no per-monitor-aware, but the truth is that there are various other programs which are systesm DPI aware, as pico torrent but still show the context menu correctly. One such example is BOINC (https://boinc.berkeley.edu/). In BOINC application the context menu is shown correctly no matter what the DPI scaling. See the attached screenshots.

### Reproduction steps.
1. Set an initial DPI scaling value (say 150%)  using using display settings on Windows 10.
2. Log-off, and log back in again. -> state of my running system when I first used pico torrent.
3.  Run Pico torrent.
4. Right click on the tray icon, and observe that the context menu will be shown at correct position.
5. Change DPI scaling to say 125%.
6. Right click on Pico torrent's tray icon again, and see that it will be displayed at incorrect location.
This does not happen in majority of other applications which are system DPI aware (BOINC being one example.)

side-note: I was following a tutorial on code project on how to create system tray icon, and display context menu using it, when I stumbled upon this problem. I then started looking for other projects which have a context menu icon, and the I stumbled upon your awesome project. I have spent several days in trying to understand the problem, both for learning, and for finding a fix. 
If people do a brainstorming on this thread, and we come up with a fix, I will be happy to fix the BUG in Pico torrent.

**Comment by vktr** [comment]
Thanks for the great report 😄 The relevant code is here https://github.com/picotorrent/picotorrent/blob/develop/src/Controllers/NotifyIconController.cpp#L32 if you want to take a closer look.

**Comment by lihas** [comment]
Yes, I am aware of that, as I have already tried few approaches for solving this bug. Including setting the application to be per-monitor DPI aware. As expected at per-monitor awareness level, the bug is not seen, but this will then require handling scaling of all the UI elements in the code, when DPI scaling is done, or the application is moved to a different monitor (with a different DPI). There is another Microsoft Windows API which can help. It is called **SetThreadDpiAwarenessContext()**. Using this some Top level windows of the UI can be made per-monitor DPI aware while others can be left System aware. This means that we can keep some windows as is, so that their scaling is handled by windows, while for some windows (like the tray icon) we can make them per-monitor aware. Sadly this API is only available in OS >= Windows 10 Anniversary Update. 

I happen to use BOINC on my computer, and I have noticed that although the application is system-level DPI ware, the issue is not seen on it. This means that there surely exists some way using which applications which are system-level DPI aware can be made to display their tray icon's context menu correctly in case of DPI scaling.

**Comment by vktr** [comment]
Yeah, we can't use that API (`SetThreadDpiAwarenessContext`) since we support Windows 7 and up. I can take a look at this tonight.

**Comment by lihas** [comment]
I have noticed one thing. If while adding tray icon if **NOTIFYICON_VERSION** is used, instead of **NOTIFYICON_VERSION_4**, then whenever context menu is invoked, Windows positions the mouse pointer at the tray icon, in which case **GetCursorPos()** can be used. Note that this will work even if the invocation is done by using keyboard. No matter where the mouse pointer is, when context menu will be invoked, it will move to the tray icon. This behaviour of Windows to position mouse pointer at cursor seems expected since unlike NOTIFYICON_VERSION_4, where wParam contains X, and Y coordinates of the click, in case of NOTIFYICON_VERSION neither of wParam, and lParam contain the mouse coordinates(check attached image for difference between NOTIFYICON_VERSION and NOTIFYICON_VERSION_4). I feel that this is how other applications are able to show context menu correctly, even after not being per monitor DPI aware.

Please test the **patch file**, included with this message. The patch is contained in [pico.zip](https://github.com/picotorrent/picotorrent/files/704258/pico.zip) attached with this message.
I have tested the code with the patch, and the context menu seems to be displaying correctly.

![notifyicon_versionvsnotifyicon_version_4](https://cloud.githubusercontent.com/assets/1687568/21931355/fc37ea22-d9c0-11e6-87b4-3b6a6d87d439.png)

[pico.zip](https://github.com/picotorrent/picotorrent/files/704258/pico.zip)

**Comment by vktr** [comment]
Thanks! I'll run a test 😄

**Comment by lihas** [comment]
I have tried to summarize, and share what I learnt from this BUG on [Stackoverflow ](http://stackoverflow.com/questions/41649303/difference-between-notifyicon-version-and-notifyicon-version-4-used-in-notifyico)[(http://stackoverflow.com/questions/41649303/difference-between-notifyicon-version-and-notifyicon-version-4-used-in-notifyico)](http://stackoverflow.com/questions/41649303/difference-between-notifyicon-version-and-notifyicon-version-4-used-in-notifyico)
You can have a look, if you want to.
