### ISSUE TITLE
Hide statusbar/menu

### ISSUE THREAD

**Issue by LeBaux** [picotorrent/picotorrent#399]
After switching to picotorrent from [transmission](https://transmissionbt.com/), I am missing compact view, or in other words, ability to hide statusbar. Hell, I wouldn't even miss the whole menu, if there was a shortcut to bring it up/hide it. These changes cloud make pico... even more pico.

![ivevy0a](https://cloud.githubusercontent.com/assets/5657511/21864823/d4795bf2-d843-11e6-9400-176e4ff193f1.png)

If it was up to me, I would hate pico like this:
![pico](https://cloud.githubusercontent.com/assets/5657511/21865497/a0207734-d846-11e6-8062-81b9d1ef11f2.png)
But I might went too far on this one.

**Comment by vktr** [comment]
Sure, sounds reasonable 😄

**Comment by LeBaux** [comment]
Obviously I took it too far, but common - do we REALLY need the statusbar (at the very bottom)? I was never apple fanboy, but one of their design mantra is true even today - if you do not need it, remove it.

**Comment by vktr** [comment]
Well, the status bar shows a few things not available anywhere else - like the global download/upload speed, a count of all torrents, and will in the future show some other metrics as well such as DHT information.

I won't remove it, but I can add a compact mode which hides it as well as the main menu.

**Comment by LeBaux** [comment]
That actually makes sense - in the hindsight, I should've probably use PT a little more before spamming github. I got overexcited over software, because apparently, I am huge f**ng nerd.

**Comment by vktr** [comment]
Closing this since I don't think a compact mode would benefit PicoTorrent. It is already quite compact.
