### ISSUE TITLE
Doubleclick the torrent shoud open folder/file

### ISSUE THREAD

**Issue by LeBaux** [picotorrent/picotorrent#400]
Pretty much what title said, I am not sure why double clicking on torrent does nothing. It should either open the folder or file (maybe configurable in settings).

**Comment by vktr** [comment]
I think we actually had this in a previous version. Must've forgotten it when rewriting it a few versions back.

It's a good suggestion and should probably be configurable as well to allow either opening the torrent in Explorer or showing the torrent details dialog.
