### ISSUE TITLE
Rightclick menu - add delete option

### ISSUE THREAD

**Issue by LeBaux** [picotorrent/picotorrent#401]
One of my most used function of torrent clients is deleting files from them - no only from the client itself, but also from the system. I am not really sure how hard this would be to implement but **Right click -> Delete torrent + files would be huge help**.

(PS: I hope it is not a big deal that I split my initial feedback to separate issues - I did it because they are pretty much all unrelated feature requests and you might choose different course of action in each case)

**Comment by vktr** [comment]
Hello! We already have this menu,

![capture](https://cloud.githubusercontent.com/assets/1491824/21866461/a92d1ac2-d84a-11e6-8ee7-f0f905426110.PNG)

Are you talking about something else?

**Comment by LeBaux** [comment]
That is it. I know why I missed it - I was using transmission for so long, that I was looking for those menu times in top level menu. You choose to have it in submenu. If you ask me, I think i have _do more work_ to delete torrent/data from PT, compared to transmission. 

![capture](https://cloud.githubusercontent.com/assets/5657511/21886654/12b2fee0-d8bd-11e6-81a6-544c5bec0d08.PNG)

Current deleting process:
1. Right click torrent
2. Mouse-over menu item
3. Go to submenu
4. Click

Proposed way:
1. Rightclick
2. Delete either torrent or torrent with data

This is not an actual problem, more of a preference. However I believe PT is designed to be minimal in design, but it should also be minimal in interaction. Less steps the better. Take Tinder for example, they become vastly more popular because compared to other dating sites they require minimum interaction. 

Lastly, maybe you don't really feel this way about PT and I am indeed trying to have it _too minimal_. But from my experience, people love the least interaction possible.
