### ISSUE TITLE
Torrents lost after updating PicoTorrent 0.11 -> 0.12

### ISSUE THREAD

**Issue by rilut** [picotorrent/picotorrent#415]
...but can be resumed by re-adding each torrents

**Comment by vktr** [comment]
Hm, that is odd. Did you add all torrents in one session?

**Comment by rilut** [comment]
No, those torrents are accumulated from my usage

**Comment by vktr** [comment]
I see. I'll see if I can reproduce it.

**Comment by vktr** [comment]
I can't reproduce this, but you may have been bitten by the bug mentioned in https://github.com/picotorrent/picotorrent/releases/tag/v0.11.1 (since you had 0.11 and moved to 0.12).

Sorry about that!
