### ISSUE TITLE
Any way to use in GNU/Linux

### ISSUE THREAD

**Issue by m-ajiao** [picotorrent/picotorrent#418]
Hello!

I really appreciate that PicoTorrent is a free as in freedom software that is designed to enhance torrent security and privacy by building native proxy and I2P support. Developers of other popular torrent clients are either reluctant to improve torrent privacy or trained to stick with proprietary runtime environments.

Is there any way for PicoTorrent, a free open source software, to be build on GNU/Linux?

**Comment by vktr** [comment]
Hi!

Sorry, there's no official GNU/Linux support, but you may or may not be able to run it in Wine. If you do - please report back with some results 😄

**Comment by DoumanAsh** [comment]
To expand on @vktr picotorrent heavily relies on WinAPI so there is no way to run it on native linux.

**Comment by vktr** [comment]
Closing this since GNU/Linux is not a priority.

**Comment by TechAdvancedCyborg** [comment]
It works on Wine, for those interested!

**Comment by TechAdvancedCyborg** [comment]
but yeah soon:tm: 
![image](https://user-images.githubusercontent.com/17462236/92998362-b7829f80-f519-11ea-8742-0cdf9cf35141.png)
