### ISSUE TITLE
Unhandled exception occured

### ISSUE THREAD

**Issue by Anonikat** [picotorrent/picotorrent#425]
[PicoTorrentDump.zip](https://github.com/picotorrent/picotorrent/files/923971/PicoTorrentDump.zip)
![2017-04-15_16-12-32](https://cloud.githubusercontent.com/assets/27587696/25067379/adb9d5e4-21f6-11e7-8691-315453e53e79.png)

**Comment by vktr** [comment]
Could you try again with the symbols installed? They are available from the release page where you downloaded PicoTorrent, and should be extracted to the same path as `PicoTorrent.exe`.

**Comment by olivierchatry** [comment]
This was for version 0.12. Downloaded symbols and dump, and crash did not find the location of the crash. Maybe it would be OK to close this one ? and reopen in case of need ?

**Comment by vktr** [comment]
Yes, closing this for now.
