### ISSUE TITLE
msvcp140.dll missing

### ISSUE THREAD

**Issue by ValdasK** [picotorrent/picotorrent#43]
Cannot run this program, as dlls are missing. Include them into compiled binary.

**Comment by vktr** [comment]
Hi, you are missing the [Visual C++ 2015 runtime](https://www.microsoft.com/en-us/download/details.aspx?id=48145). Microsoft recommends against linking statically against the runtime.

I will include them in the installer in an upcoming version :)

**Comment by ValdasK** [comment]
Casual users do not install Visual Studio to their PCs, therefore they will get this error and are most likely to quit instead of having to go through hassle of installing run-time. If MS does not recommend to link it, then what is the standard practice with those?

**Comment by vktr** [comment]
One way is to include the Visual C++ runtime merge module in the installer, which would install the runtime alongside the application. I've just not gotten there yet.

**Comment by ValdasK** [comment]
Great job on the application, you can close this issue if needed. Thanks!

**Comment by vktr** [comment]
I'll keep it open until the installer is distributing the runtime, thanks for reporting it.

**Comment by svnpenn** [comment]
@vktr does PicoTorrent actually use some of the newer APIs for this to really be a dependency? For example the Golang compiler builds EXEs that rely on Visual C++ 6, so that they will work with out of the box Windows 7+:

http://github.com/svnpenn/sage/tree/6f0fd05/go

Compiling PicoTorrent with Visual C++ 14/2015 should only be done if you are utilizing some new WINAPI methods, otherwise you are putting out your users for no reason

**Comment by vktr** [comment]
Hi @svnpenn! The choice to use MSVC14 comes from the fact that it supports much of the C++14 standard, and has generally better support for C++11 as well. The MSVC version does mot mandate which WINAPI version you use, that us up to the developer and depends in part on what defines you use - i.e you can target Windows XP by defining `_WIN32_WINNT=0x0501`, and still use MSVC14.

What I think you're getting at is that Windows 7 already bundles the VC++6 runtime which would make a dependency less for PicoTorrent - but then we cannot use the new features in C++14.

Running the PicoTorrent installer will download and install the required MSVC14 runtime at install time, and that makes PicoTorrent work out of the box on Windows 7 as well. Windows 7 (both x86 and x64) is the platform I test all releases on before putting them on GitHub.

Hope that clarifies it a bit! :smile:

**Comment by svnpenn** [comment]
@vktr yes, thanks. I just wanted to be sure the extra dep was there for a good reason as @ValdasK is right, it will push away some users

**Comment by svnpenn** [comment]
@vktr note there is a new version

http://microsoft.com/download/details.aspx?id=49984

**Comment by vktr** [comment]
@svnpenn We've been using it since it was released :smile:

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/issues/202

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/pull/224

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/issues/339

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/issues/195
