### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ElegantMonkey** [picotorrent/picotorrent#431]
Hi, I'd like first to thank you for writing this software, as it's one of the only sane torrent clients on the shitfest that's Windows.

That being said, it has been around 8 months since the last release, and there are some kinda annoying bugs that have already been fixed upstream. Seeing as the code seems to be pretty much frozen right now, wouldn't this be a good time for a new release?

**Comment by vktr** [comment]
Yeah, I know there's been some time since the last release - sorry for that!

I'll see if I can release something this week 😄 Hopefully that will be satisfying enough until the 1.0 version hits the floor later this summer.

**Comment by ElegantMonkey** [comment]
Neat, thanks! Looking forward to it!

**Comment by vktr** [comment]
v0.13 has been released.
