### ISSUE TITLE
UI.dat continues to behave weirdly, even after the update

### ISSUE THREAD

**Issue by fidelc** [picotorrent/picotorrent#443]
So, it doesn't matter how I arrange the column tab, whenever I close and open the client not only the tabs are not saved but sometimes they are completely scrambled.

Here's a video to help understand

https://gfycat.com/RaggedShoddyAlligatorsnappingturtle

At this point I would've just given up but this is by far the best torrent client there is

**Comment by vktr** [comment]
That is odd... Sorry for that.

Which OS are you running? x86 or x64?

**Comment by fidelc** [comment]
10 x64

**Comment by vktr** [comment]
Oh, what a strange issue. I can reproduce it as well, but only in the Release builds. Sorry for this!

**Comment by fidelc** [comment]
No problem, it's still usable but a little bit annoying.

I wonder if you could arrange it exactly like [this](http://i.imgur.com/kGZ5oEM.png) (make sure it shows the newer torrents first) and then upload the UI.dat file for me to see if it works
