### ISSUE TITLE
Where is the french language ?

### ISSUE THREAD

**Issue by Gladorme** [picotorrent/picotorrent#450]
Hello, I can't find the french language in Preferences. ([https://github.com/picotorrent/picotorrent/blob/develop/lang/1036.json](https://github.com/picotorrent/picotorrent/blob/develop/lang/1036.json))

<img width="329" alt="screenshot_5" src="https://user-images.githubusercontent.com/5657041/27642632-ac3f0f6e-5c1f-11e7-8d77-c400dce7d0f4.png">

**Comment by vktr** [comment]
Sorry, I must've missed adding it to the release. I'll fix it for the v0.14 release.

**Comment by olivierchatry** [comment]
I suspect there is another problem, the language file is there (1036), and should be scanned as all the other. I'm wondering if there not an error while parsing it ( maybe because of the accented characters ? ).

**Comment by olivierchatry** [comment]
Made a quick hack ( log to a file ) I can confirm there is problem in loading two of the lang file : French ( 1036 ) and Russian ( 1049 ).
The error is a bit cryptic : 
```
syntax error at line 1 near: ﻿{
﻿```

Wonder if it because of some unicode marker or something.

**Comment by olivierchatry** [comment]
Yep, file is encoded with BOM, saving as plain UTF-8 and crossing finger.
