### ISSUE TITLE
Show 'Availability' of torrents being downloaded

### ISSUE THREAD

**Issue by Eldaw** [picotorrent/picotorrent#451]
It would be nice if PicoTorrent could show the 'Availability' (number of unique copies available from peers currently connected to) for each torrent being downloaded, like what you can see in uTorrent.

**Comment by olivierchatry** [comment]
Availibity in vuze : 
* https://wiki.vuze.com/w/Availability
In uTorrent 
* http://help.utorrent.com/customer/portal/articles/164808

Which make more sense ? I would go for vuze one, because I like floating points :)

**Comment by Eldaw** [comment]
In practice I believe the way uTorrent shows it is the same as Vuze, i.e. as a floating point number as well. Especially for when the number is below 1, that's the only way you can get an exact idea about how much of the file is available from the current peers.
