### ISSUE TITLE
Differentiate between peers and seeds in list of Peers

### ISSUE THREAD

**Issue by Eldaw** [picotorrent/picotorrent#452]
When viewing the list of peers, it would be nice if there was some kind of way to see which ones are seeds and which ones are just peers with incomplete copies.

**Comment by olivierchatry** [comment]
Isn't the progress bar in the peer list what you are looking for ? Or do you want another way of displaying it ?

**Comment by Eldaw** [comment]
I created this issue just prior to upgrading to v0.13. I now see that the new progress bar introduced in v0.13 gives me much of what I'm looking for, yet I think there could still be some improvement. Perhaps have the list could automatically sort the seeds to the top or allow them to be visible in a different colour.

Also, I see that the Details window cannot be resized so the progress bar is always off to the right, out of view unless I scroll to it (at which point I can't see the first column anymore) -- I'll create a separate issue for that...

**Comment by olivierchatry** [comment]
Nice ! There is already an issue for that #455

**Comment by Eldaw** [comment]
Yes... you've linked to the one I just created?

**Comment by olivierchatry** [comment]
Yes, I edited to put both task, went a bit trigger happy on the completion.

**Comment by VideoPlayerCode** [comment]
@vktr I think you can close this ticket. :-)
