### ISSUE TITLE
Remember column sizes in Details window and main application window

### ISSUE THREAD

**Issue by Eldaw** [picotorrent/picotorrent#458]
It would be nice if the sizes of the columns in the Details window, and the main application window, were remembered.

**Comment by ConSeannery** [comment]
Also save the column ordering. My picotorrent is starting with the "Name" column always at the far right...really annoying.

**Comment by Dyras** [comment]
I have the same problem as Con, name keeps jumping to the far right and it's super annoying. I'd be fine with it jumping to the far left though.
![2017-08-25_11-12-49](https://user-images.githubusercontent.com/12563436/29711873-54e03be4-8997-11e7-9dfa-44e2e75e0084.png)

**Comment by vktr** [comment]
Fixed in #486
