### ISSUE TITLE
Copyright notice

### ISSUE THREAD

**Issue by anewuser** [picotorrent/picotorrent#461]
You should remove the year from the copyright notice, so that it never gets outdated. Right now it still says 2015.

https://github.com/picotorrent/picotorrent#license

**Comment by thebigmunch** [comment]
This is a misunderstanding. [This}(http://www.copyrightlaws.com/international/copyright-notice-year/) gives you information on what year you should be using for a copyright notice. While leaving out the year altogether is technically fine (though, possibly not in all countries), it's best to include it.

**Comment by anewuser** [comment]
@thebigmunch Your link is pretty irrelevant. Anyway, the date has already been removed.

**Comment by thebigmunch** [comment]
Please don't use a phrase to demean someone, especially when it's actually going against Copyright best practice to do so. At least the year remains in the license file
