### ISSUE TITLE
Mouse Jumps When Selecting + Wrong Item Order

### ISSUE THREAD

**Issue by duke4e** [picotorrent/picotorrent#465]
Hi,

When trying to select torrents with mouse, the mouse instantly jumps to the bottom right corner. I've drawn how much and where I moved the mouse, but you can see what happens.

Also, the "Name" row doen't remember the position. I want it to be next to # row, but every time I close the app, it resets to this unwanted position.

![bug](https://user-images.githubusercontent.com/288641/28620902-3a1fb464-720f-11e7-85c2-7f37f6330457.png)

**Comment by vktr** [comment]
I thought I fixed the column reordering issue in the latest version. Which version are you running?

**Comment by duke4e** [comment]
0.13.0

**Comment by vktr** [comment]
Should be fixed in #486
