### ISSUE TITLE
Windows 10 UWP edition doesn't show the Swedish translation properly

### ISSUE THREAD

**Issue by Dyras** [picotorrent/picotorrent#466]
Ahoy! Please look at these pictures!
![2017-08-05_22-09-06](https://user-images.githubusercontent.com/12563436/28999107-c4824fa2-7a3b-11e7-8bcf-a80e2a682374.png)
![2017-08-05_22-09-16](https://user-images.githubusercontent.com/12563436/28999109-c488ddcc-7a3b-11e7-92bc-8756953804ba.png)
![2017-08-05_22-09-30](https://user-images.githubusercontent.com/12563436/28999108-c483d0d4-7a3b-11e7-8f46-097845ff4c79.png)

Note how instead of the translation, it just shows a generic "show_picotorrent_in_notification_area". Feel free pushing a fix ASAP.

Aside from this minor problem this app is worth every penny.

**Comment by vktr** [comment]
Hi! This is due to missing translations for those items in the Swedish translation file. There's a few languages that has missing translation keys, Swedish being one of the worst offenders.

**Comment by Dyras** [comment]
I'd happily translate it!
https://github.com/picotorrent/picotorrent/blob/develop/lang/1053.json
That's the file, right?

**Comment by vktr** [comment]
That's it 😄

**Comment by vktr** [comment]
Closing this since it's not really a bug - it's an outdated translation.
