### ISSUE TITLE
Customize the double-click action

### ISSUE THREAD

**Issue by Keith94** [picotorrent/picotorrent#468]
By default, double-clicking on a torrent transfer opens the details/preferences window. You should add the ability to change the action, e.g. pause/unpause the torrent, open the containing folder in explorer, etc.

**Comment by vktr** [comment]
Sure, this sounds reasonable 😄

**Comment by vonder2** [comment]
The same for double-clicking on file in the files tab below - it should open the file in associated program, not just open folder in explorer.
