### ISSUE TITLE
Single-click tray icon to toggle

### ISSUE THREAD

**Issue by Keith94** [picotorrent/picotorrent#469]
I wish to toggle/show the PicoTorrent main window via single-click on the tray icon. Most applications can be interacted via single-click, but it currently does nothing for PicoTorrent's icon.

**Comment by vktr** [comment]
If you double click the tray icon you will get the behaviour you mention. Perhaps a single click would be better - I'd have to check if Microsoft has any guidelines on this.

**Comment by Dyras** [comment]
I definitely prefer single-click. Here are some programs that use single-click:
GOG Galaxy
qBittorrent
Wire

However it seems like Microsoft prefers a double-click, since that's what Windows Defender uses.
