### ISSUE TITLE
Drag & drop missing

### ISSUE THREAD

**Issue by JonasNo** [picotorrent/picotorrent#475]
Implement drag and drop so dragging and dropping torrent / magnet link will get caught.

**Comment by randomeer** [comment]
Has this been implemented yet or is it planned for the next version?

Obviously an awesome feature that would make Pico even better :)

**Comment by vktr** [comment]
Hi @randomeer!

It was implemented at first, then we lost it. Now it will be back for the rewrite which you can follow in #486

**Comment by vktr** [comment]
Fixed in #486
