### ISSUE TITLE
Show estimated time until downloaded, next to download speed.

### ISSUE THREAD

**Issue by matjos** [picotorrent/picotorrent#48]

**Comment by patriksvensson** [comment]
I was actually thinking about adding this :smile: 

@vktr Assign this to me if you want to.

**Comment by vktr** [comment]
Go nuts :)

**Comment by patriksvensson** [comment]
@vktr Looks like I won't have any time to work on this for a couple of weeks, so if someone else want to take this then go ahead :smile:
