### ISSUE TITLE
The code execution cannot proceed because MSVCR120.dll was not found.

### ISSUE THREAD

**Issue by BoQsc** [picotorrent/picotorrent#487]
## Reinstalling the program may fix this problem.
![msvcr120_error_picotorrent](https://user-images.githubusercontent.com/21064622/31045400-8274fc0a-a5eb-11e7-9561-5a6799dc3cdf.png)
No, reinstalling the PicoTorrent is not going to help, no matter the personal luck you own.
This happens in either portable and setup version of the PicoTorrent, 
after first launch of the exe execution file.

## Solution to the missing library called MSVCR120.dll:
So, what we can do about this? Well simply include [Visual C++ Redistributable Packages for Visual Studio 2013](https://www.microsoft.com/en-GB/download/details.aspx?id=40784)
Both vcredist packages are needed to be included, however, both are not needed to be installed, only the one for the needed architecture.
- vcredist_x86 
- vcredist_x64

## Visual C++ Redistributable for Visual Studio 2015
2015 do not include the needed MSVCR120.dll, 
that means only recent Visual C++ Redistributable Packages for Visual Studio 2013 has capability to fix this error.

**Comment by bittaurus** [comment]
Issue confirmed on win7.  The best solution may be to add a check in picotorrent for the dependency then error out with a link to microsoft's installer download page.  This would be the least footprint for a good solution, as it doesnt involve needing to package the redists into the installer and you dont need to add a downloader into picotorrent.

**Comment by vktr** [comment]
Did you use the installer or the zip package? If you run the portable zip-package you would install the redistributable yourself, but the installer should download the correct C++ runtime at install time.

**Comment by bittaurus** [comment]
I used the installer, but I think the download timed out and after an hour I clicked cancel and it still finished setup without it.

**Comment by vktr** [comment]
Oh ok, that shouldn't happen. Sorry!

However, it's non-trivial to add a runtime check in PicoTorrent since we rely quite heavily on the runtime and its existance. I'll see if I can add something to the 1.0 release :smile:

**Comment by bittaurus** [comment]
Maybe a note on http://www.picotorrent.org/download/ about the dependency might be a good idea.

**Comment by vktr** [comment]
Fixed in #486
