### ISSUE TITLE
Issues with setting the UL limit

### ISSUE THREAD

**Issue by F0RCE** [picotorrent/picotorrent#491]
Setting the UL limit to anything beside 0 will cause the download speed to drop a lot or even stops the download https://i.imgur.com/SRBiazo.png

Is this an intended "feature"?

Otherwise, this is a really nice BitTorrent Client

**Comment by vktr** [comment]
Hi @F0RCE! Sorry for the late answer. This sounds odd, indeed. I'll have to look deeper, but it's definitely not an intended feature 😄 Thanks for your patience, and for your kind words!

**Comment by vktr** [comment]
Should be fixed in #486
