### ISSUE TITLE
[Feature Echantement\bug] Torrent preferences, setting priority for seperate files to Maximum

### ISSUE THREAD

**Issue by BoQsc** [picotorrent/picotorrent#493]
Setting file's priority does not download file fully and waits for other files to finish.
1. Select any torrent you try to download 
2. Right-click selected torrent.
3. Select Details from a drop-down menu.
4. Select Files tab.
5. Set any of the downloading file's priority to Maximum.
6. Watch how the file is downloading and reaches 90-99 % of progress.
7. Maximum file priority file keeps waiting for other normal priority files to download, before finishing.

**Comment by CatTheHacker** [comment]
Works fine for me. Are you sure it is waiting for lower priority files?  
¬ Windows 10 x64 | PicoTorrent x64 0.13.0

**Comment by vktr** [comment]
Would you mind trying again? I've rewritten most of PicoTorrent in #486 so you could perhaps try the latest CI builds from AppVeyor.

https://ci.appveyor.com/project/picotorrent/picotorrent/build/622/job/tj7pjjbxsy7w8d1m/artifacts
