### ISSUE TITLE
Tree View

### ISSUE THREAD

**Issue by ArtexJay** [picotorrent/picotorrent#494]
Please add the ability to view files in tree view  when selecting what files to download

**Comment by vktr** [comment]
Hello!

Yes, this is planned for the rewrite I'm currently doing in PR #486 :smile:

**Comment by ArtexJay** [comment]
I can't wait for it to be released then haha

**Comment by vktr** [comment]
Thanks! Yeah, there's a lot of features that will get implemented once 1.0 is released!

**Comment by vktr** [comment]
Fixed in #486
