### ISSUE TITLE
Dark Theme/Fluent Design

### ISSUE THREAD

**Issue by ArtexJay** [picotorrent/picotorrent#495]
Would it be possible to have the option for a dark theme for picotorrent?

**Comment by vktr** [comment]
I'm unsure on how to accomplish this in a maintainable way, but I'll definitely take a look at it.

**Comment by ArtexJay** [comment]
Another idea came to me today will i was looking on youtube there was a MS video showing how Devs could implement the new fluent design into their applications.
I realize this is purely cosmetic stuff but i think it would be nice to have it blend into OS

**Comment by vktr** [comment]
Closing this since it's not really feasible. Cool idea, though! 😄

**Comment by ArtexJay** [comment]
Too bad this is not feasible. Would look great on this Torrent program.

**Comment by Rakleed** [comment]
>Closing this since it's not really feasible. Cool idea, though! 😄

@vktr, does your post relate to Fluent Design or a dark theme?

**Comment by vktr** [comment]
@Rakleed It was aimed mostly at Fluent Design, since if we use the UWP components we'll need a hard dependency on Windows 10.

**Comment by Rakleed** [comment]
@vktr, can I then create a dark theme feature request?

**Comment by vktr** [comment]
Yes, sure! It might be doable with the Qt rewrite since we can style using CSS then.

**Comment by make-42** [comment]
For those who are interested, this PR brings PicoTorrent very close to a dark theme: #1269
