### ISSUE TITLE
Details Panel

### ISSUE THREAD

**Issue by ArtexJay** [picotorrent/picotorrent#498]
Picotorrent already has the option to view the details of the torrent, but i think it would be better to have details have its own panel. So you just click on the torrent and it immediately shows you the details of that torrent in the bottom of the application, similar that found in Qbittorrent or Utorrent.

**Comment by vktr** [comment]
Hi! This is already implemented in the wxWidgets rewrite which you can track in PR #486 😄

**Comment by ArtexJay** [comment]
ohh :P well can't wait for the release of the rewrite

**Comment by vktr** [comment]
![image](https://user-images.githubusercontent.com/1491824/32290191-8b21c74a-bf39-11e7-8a03-2b025728d232.png)

Here's how it looks 😄

**Comment by ArtexJay** [comment]
OMG it looks so beautiful *wipes away a tear*
Caaaaaan't waaaaaaait XD

**Comment by mutt3x** [comment]
It does not look anything that impressive honestly. We have this type of design in many other clients and im not a fan of it. What i like to see is something different/better. Look at rTorrent as an example. 

Side note: Make it go away with F5 just like in uT. Just so you can keep the things that matter in a minimalist box.

**Comment by vktr** [comment]
@mutt3x I hear you, and no, it's not that impressive. But it's something that most users expect, and something I can build on later when the plugin API comes (ie. let plugins add tabs and stuff).

And yes, you will be able to toggle it easily 😄
