### ISSUE TITLE
Force torrent check option

### ISSUE THREAD

**Issue by ownmaster** [picotorrent/picotorrent#499]
I noticed that after Windows (7) shutdown and start PicoTorrent started automatic check of some torrents (not all).
I wonder if there is an option to force check of particular torrent? Part of the torrent has been downloaded by uTorrent, but import option is not a way for me, since I have too many torrents in uTorrent and going to transfer them one by one.
Maybe using some command line magic?

**Comment by jamesaepp** [comment]
I noticed for myself (IIRC) that I could force a re-check when the torrent was not at 100%, but now my torrent is downloaded at 100% and I cannot force a re-check. Win7 sp1 x64 client.

**Comment by vktr** [comment]
Hi! There's no command line trick, sorry. I'll add a permanent option to force recheck in the next version. Thanks for your patience!

**Comment by vktr** [comment]
Fixed in #522
