### ISSUE TITLE
Problem with the 1049 language

### ISSUE THREAD

**Issue by nxrighthere** [picotorrent/picotorrent#502]
For some reason the Russian language is not displayed in preferences, even if I manually set the language id in a settings file to the 1049, it doesn't work.

By the way, PicoTorrent is the best torrent client on the earth!

**Comment by vktr** [comment]
Hi @nxrighthere! This is strange indeed, I'll have to look deeper. Thanks for reporting, and thanks for the kind words!

**Comment by vktr** [comment]
Fixed in #486 (or before) 😄
