### ISSUE TITLE
Remember column ordering

### ISSUE THREAD

**Issue by nxrighthere** [picotorrent/picotorrent#503]
Column ordering is messed up after every restart of the application.

I'm using the 0.13 version.

**Comment by 726a67** [comment]
Same, using 64-bit 0.13.

**Comment by vktr** [comment]
Hi! Yeah, there's been some issues with column reordering which I've failed to track down completely, sorry about that. I'll definitely fix it for the rewrite I'm doing in #486. Thanks for you patience!

**Comment by vktr** [comment]
I haven't been able to reproduce any column ordering issues in #672 so I'm closing this for now. Please reopen if necessary after v0.16 has been released.
