### ISSUE TITLE
Moving a torrent won't prevent PicoTorrent from downloading the torrents again in their old location

### ISSUE THREAD

**Issue by Dyras** [picotorrent/picotorrent#504]
So I just discovered that if you move a torrent (In the UWP version at least) and then you restart the program, PicoTorrent will attempt to download the torrent from scratch again in the old location.

Super annoying.

**Comment by vktr** [comment]
Hi! Do you move the file on disk or are you using the context menu in PicoTorrent?

**Comment by Dyras** [comment]
Context menu in PicoTorrent
Right click a torrent -> move

**Comment by vktr** [comment]
Odd, that's a bug indeed. I'll definitely have a fix for it in the next version. Thanks for you patience!

**Comment by vktr** [comment]
Should be fixed in #486
