### ISSUE TITLE
Strange behavior when unmarking a file for download

### ISSUE THREAD

**Issue by Dyras** [picotorrent/picotorrent#505]
If you click on a file in the download list and you then click on the box [x] of another file, both files are unmarked [ ]. IMO they shouldn't do that. Only the file you click on should be unmarked.
![spiritedregularbronco-size_restricted](https://user-images.githubusercontent.com/12563436/33243707-73cb9434-d2eb-11e7-9fb8-79fa32be843e.gif)

Also something I just noticed while recording is that for whatever reason, the files keep reverting back to being marked.

**Comment by vktr** [comment]
Yeah, that's a bug I've noticed as well but forgot to file an issue for 😄 It will be resolved in the refactoring I'm doing in #486

**Comment by vktr** [comment]
Fixed in #486
