### ISSUE TITLE
why am I limited to seeding 15 torrents in total at once?

### ISSUE THREAD

**Issue by akoslp** [picotorrent/picotorrent#514]
I mean, really? This is a great slim app, why ruin it with this? There is no way to even force seed more than 15 at a time. I paid $5 for it and would like to seed more than 15 torrents. A place to see your downloaded and uploaded amount of data would also be nice.

**Comment by vktr** [comment]
Hi!

You should be able to adjust the limit, see here:
http://docs.picotorrent.org/en/master/configuration.html#advanced-settings

If that doesn’t work, let me know!

**Comment by akoslp** [comment]
Thanks, I was able to make more than 15 torrents active at a time. However, I now have another problem. WIth Pico the DHT nodes always shows 0 for me and thus not getting connections properly. With other torrent clients, I get over hundreds of DHT nodes and have steady seeding. Any idea of the cause of this?

**Comment by vktr** [comment]
Not sure, I'll have a look.
