### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by wkoncki** [picotorrent/picotorrent#515]
Just a quick report. Installers from your site seem to not be working. They display generic error during installation. After going into log for details I've found information that they failed to fetch library installer from remote URL. This happened on windows x64 installer.

`[07F0:2A14][2017-12-26T21:01:49]e000: Error 0x80072ee7: Failed to send request to URL: https://picotorrent.blob.core.windows.net/public/vcredist/14.0.24123.0/vc_redist.x64.exe, trying to process HTTP status code anyway.
[07F0:2A14][2017-12-26T21:01:49]e000: Error 0x80072ee7: Unknown HTTP status code 0, returned from URL: https://picotorrent.blob.core.windows.net/public/vcredist/14.0.24123.0/vc_redist.x64.exe`

**Comment by Urgarth** [comment]
Same issue. Could you fix this please? Win10 x64

**Comment by vktr** [comment]
Fixed in #486
