### ISSUE TITLE
PicoTorrent.json reverting to default and no DHT

### ISSUE THREAD

**Issue by AFaustini** [picotorrent/picotorrent#516]
I made some advanced configurations as shown in http://docs.picotorrent.org/en/master/configuration.html#advanced-settings
to enable DHT (which appear to have 0 nodes in my picotorrent install and 383 nodes in qbittorrent)
but this config has none effects and everytime that i close PicoTorrent the picotorrent.json reverts to previous state with none of advanced settings. There is a way to prevent this and enable DHT?

**Comment by Yuubari** [comment]
If you edit the configuration file with PicoTorrent running, it seems it will overwrite it on exit. I have just tried adding enable_dht to mine and it stays there between restarts no problems.

However the 0 DHT nodes issue is present for me as well. The torrent I am downloading does not have trackers listed and it seems like I am only getting incoming connexions with no outgoing ones being established.

**Comment by AFaustini** [comment]
I had edited this file with PT not running and when i opened PT the file reseted to default.

**Comment by AFaustini** [comment]
The json reverting to default bug is over. I had put a comma over the last switch in file. That make the file revert to default.
