### ISSUE TITLE
Consider changing the keybind for Exit to X instead of E

### ISSUE THREAD

**Issue by rctgamer3** [picotorrent/picotorrent#520]
On most, if not all Windows programs, the Exit option under File is labeled as ![Firefox](https://user-images.githubusercontent.com/607379/35182944-e433f4ce-fddd-11e7-81a1-4b28a3ad389e.png) (Alt+F+X). In PicoTorrent it's set to ![exit_pico](https://user-images.githubusercontent.com/607379/35182952-fb785cce-fddd-11e7-9d1d-27d480035997.png) (Alt+F+E).

**Comment by vktr** [comment]
Fixed in #486
