### ISSUE TITLE
Is project abandoned?

### ISSUE THREAD

**Issue by ownmaster** [picotorrent/picotorrent#521]
Actually, the title is pretty much self-explanatory. :)

**Comment by vktr** [comment]
Not at all - there’s a major refactor going on in #486 which will really
push PicoTorrent forward :) As soon as that is finished I will focus more
on new features and requests.

**Comment by vktr** [comment]
I've merged #486 now and will focus on adding features that have been outstanding for a while 😄 I'll see if I can do a release quite soon.
