### ISSUE TITLE
Failed to download VC_redist on Win10

### ISSUE THREAD

**Issue by lament** [picotorrent/picotorrent#523]
Hi.. installation is failing as it's trying to install a file that doesn't exist.

```
[41B0:3A20][2018-02-26T21:26:48]i338: Acquiring package: VC_redist.x64.exe, payload: VC_redist.x64.exe, download from: https://picotorrent.blob.core.windows.net/public/vcredist/14.0.24123.0/vc_redist.x64.exe
[41B0:3A20][2018-02-26T21:26:49]e000: Error 0x80070002: Failed attempt to download URL: 'https://picotorrent.blob.core.windows.net/public/vcredist/14.0.24123.0/vc_redist.x64.exe'
```

**Comment by vktr** [comment]
Hi!

Yeah, I messed up the blob storage. I’m pushing a new release quite soon
which you can preview at
https://ci.appveyor.com/project/picotorrent/picotorrent/build/job/tj7pjjbxsy7w8d1m/artifacts

Let me know if it works!

Viktor

**Comment by lament** [comment]
It just kinda sat there halfway when trying to install VC_redist.x64.ext. :/

**Comment by vktr** [comment]
For the beta?

**Comment by lament** [comment]
@vktr yes for this version:

https://ci.appveyor.com/project/picotorrent/picotorrent/build/job/tj7pjjbxsy7w8d1m/artifacts

**Comment by vktr** [comment]
Odd. I’ll take a look tonight! Sorry for the inconvenience.

**Comment by vktr** [comment]
I can't reproduce the issue - the link I sent previously in this thread works as expected. The installer points to a different `VC_redist.x64.exe` as well (https://picotorrent.blob.core.windows.net/public/vcredist/14.12.25810.0/VC_redist.x64.exe).

I know the URL you mentioned was used by an older installer for PicoTorrent.

Are you sure you started the correct installer? They are named the same (PicoTorrent-0.13.0-x64.exe).

**Comment by armed** [comment]
Same for me, `v0.13.0-x64`

**Comment by vktr** [comment]
This is a known issue with the current installer. Please try the latest one from here: https://ci.appveyor.com/project/picotorrent/picotorrent (choose your environment then click the Artifacts tab).

**Comment by lament** [comment]
@vktr working well. Thanks!
