### ISSUE TITLE
Four Ideas: Labels, ideally respecting directories, plus .torrent path, and dates

### ISSUE THREAD

**Issue by PixelEater** [picotorrent/picotorrent#531]
Here's four ideas I think are good on their own but also work well together if all are implemented.

Labels
I would like to propose a labels feature, at the very minimum. Even if it did little more than bring us a Labels column and context or Preferences menu, that would be great. If there was a way to view the contents of one label at a time, that would be a huge bonus.

Added On, Finished On Columns
I tend to really favor sorting my torrents by the added on date. Being able to sort by this would compliment the above request well, but even on its own would be helpful. If you like, these columns don't really have to be enabled by default.

File Paths Based on Labels
Although less important than the labels feature itself, it would be incredible if transfer paths were set on a label by label basis.

Location of .torrents
And this definitely isn't a must, but too few clients seem to offer the freedom to specify how .torrents are stored. I think the concept is fairly simple, like at least a choice to 'Store .torrents in', and optionally you could also have a completed download .torrent path. What would go above and beyond is if this could also be defined by label.

**Comment by mutt3x** [comment]
Potencially all of this. Sometimes you see a person with the same taste in... torrenting. Minimal, pure and organised.

**Comment by vktr** [comment]
*Added on* and *Completed on* columns are now in `develop`.

**Comment by droidberg** [comment]
this is something that i have been begging the transmission devs to add. this would be amazing in pico!
