### ISSUE TITLE
Private flags

### ISSUE THREAD

**Issue by PixelEater** [picotorrent/picotorrent#532]
This client currently isn't whitelisted on any private trackers that I know of. But I bet actually they would love it since it's based on libtorrent. One of the only issues that stands out is the lack of the all important private options, like a toggle for disabling DHT, PEX, etc. It is important the client also understands private torrent markers in the event it downloads one. Those basically firmly disable those very same things. There aren't too many lightweight desktop clients out there, so I'd be enthusiastic if we got this addressed so I can petition my favorite sites to support this. People are looking for interesting alternatives to uTorrent, given its latest issues. Believe me, these quality driven private communities are a good fanbase to have!

**Comment by mutt3x** [comment]
Hard +1

I did suggest these things several PRs ago and some got implemented but not fully. Private trackers are mostly populated by powerusers who want good and advanced software for their needs.

Regarding the uTorrent thing, i think Pico can collect some users from the recent incident. But with more users come more work...

**Comment by vktr** [comment]
Hi @PixelEater and @mutt3x! 

PicoTorrent (or rather libtorrent) correctly respects the `private` flag in a torrent, and private torrents are not distributed on the DHT or to uTorrent PEX peers. I'll add an option to disable DHT globally as well, but using private torrents already is fine :)

**Comment by PixelEater** [comment]
Sounds great. Are you planning at any point to add a 'create torrent' feature?

**Comment by vktr** [comment]
Yes, it's mentioned in #483 and is actually planned for either the next release or the one after :)

**Comment by Norcoen** [comment]
:heart:

**Comment by vktr** [comment]
@Norcoen Yes, it should be covered by this issue 😄 I'll add options for

- DHT
- PEX
- LSD/LPD
