### ISSUE TITLE
Poll all announce URLs in torrent

### ISSUE THREAD

**Issue by Paukan777** [picotorrent/picotorrent#538]
For now announce polling stops on first working url found. This is no good because "working" doesn't means "have enough peers". First working tracker may return 1 slow peer, but other ones having hundreds of fast peers will be never accessed. So we need an option to poll all trackers in torrent, regardless of returned peers and tracker status.

**Comment by vktr** [comment]
I'm currently improving the tracker list view and will make sure this gets added.

**Comment by bb010g** [comment]
This still isn't implemented; exposing libtorrent's [`lt::settings_pack::announce_to_all_trackers`](https://www.libtorrent.org/reference-Settings.html) in the session settings should work? In addition, `active_tracker_limit` should probably be wired up to the UI, as it's currently only accessible by manually modifying `PicoTorrent.sqlite`.

https://github.com/picotorrent/picotorrent/blob/3ffaa83ea48fd8fdbd584e2f00bdccb001c518a9/src/picotorrent/session.cpp#L126-L133

**Comment by vktr** [comment]
Hi! There's a big rewrite in the works, and there's a lot of settings which will be exposed in the preferences dialog. These two among them.

I'll reopen this to keep track of it,
