### ISSUE TITLE
Missing taskbar icon

### ISSUE THREAD

**Issue by PixelEater** [picotorrent/picotorrent#546]
It seems PicoTorrent's cute icon doesn't actually register on the Windows 10 taskbar, even though the system tray, start menu and window icons work well. Maybe this is something easy to fix during the build process.

![capture2](https://user-images.githubusercontent.com/10372471/37260405-b345c220-2560-11e8-8aa3-d592e99456d5.PNG)

**Comment by vktr** [comment]
Odd, can you try with the latest installer? https://ci.appveyor.com/project/picotorrent/picotorrent

**Comment by PixelEater** [comment]
Is there a certain trick to downloading this? I haven't used AppVeyor before.

**Comment by vktr** [comment]
https://ci.appveyor.com/project/picotorrent/picotorrent/build/job/hlt4s1h1t09umx10/artifacts

The exe file in this list is the latest beta installer. You might have to
uninstall your current version first.

**Comment by kbalint** [comment]
I think the problem returned with Windows 11:
(installed latest via choco)

![image](https://user-images.githubusercontent.com/4146263/157848354-7c93a116-45dc-4cf4-a40c-c278a7906d01.png)

![image](https://user-images.githubusercontent.com/4146263/157848787-c15c0374-287a-4be3-946b-a9d5e2349a5d.png)

it somehow fails to register the icon file. If I manually recreate the shortcut, everything is OK.
