### ISSUE TITLE
Omit 'stalled' in status column

### ISSUE THREAD

**Issue by PixelEater** [picotorrent/picotorrent#547]
This is a minor recommendation, but I think most prefer not to see the word 'stalled' unless a torrent isn't working. It became a bit of a running joke with qBittorrent at one point. I really think rather than Stalled (seeding), just Seeding would be nice. Stalled makes me think of a torrent that isn't working, even if it's technically applicable in some sense. Also for what it's worth, I'm not entirely sure Resume (force) is working, as the torrent remains paused, even though the plain Resume option visibly works. It's not entirely clear what force does.

**Comment by vktr** [comment]
Sounds reasonable.
