### ISSUE TITLE
"Remaining" Column

### ISSUE THREAD

**Issue by AFaustini** [picotorrent/picotorrent#548]
Please insert a remaining column in the torrent list

**Comment by vktr** [comment]
Remaining time? Data? If data, would it be OK to put it in the Size column?
Like “100mb (of 324mb)” for example.

**Comment by AFaustini** [comment]
Data.
It's fine for me.
But i think some people does not like this mix and will prefer two fields (Total Download and Remaining Size) for organization purposes.

**Comment by vktr** [comment]
Sure! I’ll fix it tonight :)

**Comment by vktr** [comment]
Added in #672.
