### ISSUE TITLE
character handling 

### ISSUE THREAD

**Issue by jnsl** [picotorrent/picotorrent#554]
Certain characters in torrent/folder names like ampersand (&) or phi (φ) are broken.

En dashes (–)  are broken and result in picotorrent re-downloading preexisting torrents.
In folder names fetched by a older version, en dash is prefaced by a left-to-right mark (LRM), which the re-downloaded folders lack. 

Behavior is observed when upgrading picotorrent from ≤ 0.13 to current (wxWidget) builds including the latest 666.

**Comment by vktr** [comment]
Thanks for the report! Can you expand on the LRM issue?

**Comment by vktr** [comment]
@jnsl can you try the latest builds from https://ci.appveyor.com/project/picotorrent/picotorrent/build/669?
