### ISSUE TITLE
File name can't show.

### ISSUE THREAD

**Issue by bestpika** [picotorrent/picotorrent#564]
When I update to v0.14.
Some file name can't show.
(e.g. CHT, CHS, JPN)
And it can't **Open in Explorer**.
(v0.13 without this problem.)

![image](https://user-images.githubusercontent.com/5698157/38687643-b9f30f76-3ea9-11e8-8001-989ab9de27d0.png)
![image](https://user-images.githubusercontent.com/5698157/38687661-c2839fac-3ea9-11e8-83af-43663c558a26.png)

**Comment by vktr** [comment]
Hello!

Can you attach the torrent file? Or send it to me at
viktor@viktorelofsson.se.

**Comment by bestpika** [comment]
This is magnet link: `magnet:?xt=urn:btih:eb5842c2dfe06220499adcb36bf64929f1fd8bcc`

**Comment by bestpika** [comment]
[eb5842c2dfe06220499adcb36bf64929f1fd8bcc.zip](https://github.com/picotorrent/picotorrent/files/1903914/eb5842c2dfe06220499adcb36bf64929f1fd8bcc.zip)

**Comment by bestpika** [comment]
@vktr Thank you.
