### ISSUE TITLE
Error: tracker sent a failure message

### ISSUE THREAD

**Issue by swedejesus** [picotorrent/picotorrent#572]
Using the latest client.

I get this error message no matter which tracker I use.
Also tried different ports.

![image](https://user-images.githubusercontent.com/2523049/38765701-dc2e852a-3fc6-11e8-8907-87f336f6eb06.png)

**Comment by vktr** [comment]
Strange.. Does the download still work?

**Comment by vktr** [comment]
I'll see what I can find, sorry about that!

**Comment by dalecarlian** [comment]
@vktr If you want me to try something specific just highlight me. I will try some more later this evening.

It's so strange that any other client works out of the box. Do you know if the client is banned or something from specific trackers?

**Comment by vktr** [comment]
Many trackers use a whitelist of allowed clients. It might be that
PicoTorrent is not whitelisted. In that case, a dialogue with the tracker
maintainers to get it whitelisted is the way forward.
