### ISSUE TITLE
List files for magnet link.

### ISSUE THREAD

**Issue by jamboree** [picotorrent/picotorrent#577]
In the previous release (0.13), there used to be a dialog showing the files before start downloading.
This was the feature why I prefer picotorrent to utorrent...

In new release, after the magnet link is added, the "Add torrent(s)" shows nothing so I can't select which files to download beforehand.

**Comment by jamboree** [comment]
I guess you can add a checkbox in the magnet link dialog:

- [x] Pre-load metadata.

So the users can choose to wait or not. It'd be better to remember this option.

**Comment by ArtexJay** [comment]
I prefer preloading since I do not  want to download everything in the magnet torrent

**Comment by vktr** [comment]
This has been added in #672 and was also discussed in #608 😄 It will be released with v0.16.
