### ISSUE TITLE
Parsing torrent files with cyrillic filenames

### ISSUE THREAD

**Issue by nxrighthere** [picotorrent/picotorrent#582]
PicoTorrent 0.14.1 unable to parse torrent files that contain cyrillic characters. For example `(Pop, Dance-Pop) Estradarada - Дискотека Века (2017), MP3, tracks, 320 kbps`.

**Comment by nxrighthere** [comment]
[Sure](https://github.com/picotorrent/picotorrent/files/1913152/Torrent.zip).

**Comment by vktr** [comment]
#583 will work. I'll make a release later today with that fix as well as other small fixes. Sorry!

**Comment by nxrighthere** [comment]
Thank you Viktor!
