### ISSUE TITLE
Warn and pause downloading torrent when disk space below a set size

### ISSUE THREAD

**Issue by ltGuillaume** [picotorrent/picotorrent#585]
In order to prevent other programs from not being able to save their settings to disk, random crashes etc. as soon as a disk is full, it would be great if PicoTorrent checks whether free space is below a set amount and warn + pause the downloading torrents until the user responds.

**Comment by vktr** [comment]
I've added this feature in #672 with a fixed (for now) percentage at 5% disk space. It's in the config but not adjustable in the UI at the moment.

**Comment by ltGuillaume** [comment]
Very cool, thank you! :-) Personally I think a fixed amount of megabytes makes more sense than a percentage, but this'll do just fine.

**Comment by vktr** [comment]
Yeah, the plan is to further enhance it in the upcoming versions. This is just a simple fix for the immediate problem :)
