### ISSUE TITLE
Link "listen interface" to specific adapter

### ISSUE THREAD

**Issue by ltGuillaume** [picotorrent/picotorrent#586]
Some VPN services allow for port mapping. PicoTorrent allows to bind to a specific interface by IP manually, but this is only useful if you have a static IP. Could it perhaps bind to an interface by letting the user choose which interface to exclusively use and then automatically set up the appropriate outside IP?

Also, in order to be sure that no traffic is allowed outside of a VPN connection, I'm not exactly sure if this would be enough for those systems that have two or more interfaces running (e.g. wired LAN and wireless LAN, or systems with dual LAN). Maybe some extra steps should be taken to really exclusively bind to an interface/adapter.

**Comment by ltGuillaume** [comment]
qBittorrent apparently knows its way to work around that, because after selecting the interface from a drop-down list, qBittorrent automatically converts that into an ip:port format to pass onto libtorrent.

**Comment by ltGuillaume** [comment]
Yeah I guessed that would be what you meant, but still I think it's quite a security improvement: without the extra feature, any user with a VPN, someone who is using different networks or someone with a dynamic IP address would have to use 0.0.0.0, allowing PicoTorrent to get data via the listening port from any adapter.

**Comment by vktr** [comment]
This is now fixed in #672 - you can bind PicoTorrent to a specific network adapter.

<img width="442" alt="image" src="https://user-images.githubusercontent.com/1491824/54600064-3f2e4180-4a3c-11e9-8694-ef73f63c31f5.png">
