### ISSUE TITLE
Enter key does not confirm and close the Add torrent(s) dialog

### ISSUE THREAD

**Issue by ltGuillaume** [picotorrent/picotorrent#587]
When the Add torrent(s) dialog pops up and everything's ok, I think simply hitting the Enter key should confirm adding the torrent and close the dialog (no matter what element is focused at that moment).

**Comment by ltGuillaume** [comment]
I was thinking about suggesting to just put focus on the OK button as you now have implemented (that was fast!), but I thought that if you maybe decides to implement labels + linked download folder specifications (see https://github.com/picotorrent/picotorrent/issues/531), then it would make more sense to focus the drop-down list of the labels and pressing Enter after selection would also confirm and close the dialog. That's why I said _"(no matter what element is focused at that moment)"_.

**Comment by vktr** [comment]
Yes, when presets are implemented we can revisit this and see how we can improve usability 😄 Right now the OK button is only the default.
