### ISSUE TITLE
The main window always starts in double width

### ISSUE THREAD

**Issue by dertuxmalwieder** [picotorrent/picotorrent#592]
I keep my PicoTorrent (latest release) centered on my main screen and I minimize it to the taskbar most of the time. However, every time I reboot my machine, PicoTorrent starts with a two-screen width, basically taking all available screen space. I would consider that a bug.

Win10 x64.

**Comment by vktr** [comment]
Are you running a high DPI display?

**Comment by vktr** [comment]
I see. Strange - I'll see if I can reproduce it.

**Comment by andreysaksonov** [comment]
it is 100% reproducible on my dual Dell 1920x1080 setup

**Comment by StoyanDimitrov** [comment]
Dual 1920x1080 here too. The main display is standalone Dell, the extended one is a laptop physically located to the left of the main. The application starts on the main and is significantly wider than it.
```
[ 1 ][ 2 ] - the monitor setup. 1 - extended, laptop display, 2 - the main - standalone Dell
[ 1 ][ pico  ] - how the application starts
```

**Comment by TechnoGreg** [comment]
Confirmed here too, latest build is concerned.

**Comment by robotbroken** [comment]
Confirmed. I have three 4k monitors (Samsung UH750 + 2 Samsung UE590D) side-by-side. When the picotorrent application opens it covers at least 2 of the screens and goes off even further. It is pretty annoying.

PicoTorrent 0.15.0.
Windows 10 Version 10 17134
nVidia GeForce 1080 Ti w/ latest drivers

**Comment by vktr** [comment]
Closing this since v0.16 has been released and this should be fixed.
