### ISSUE TITLE
View -> Preferences pops up window on other monitor

### ISSUE THREAD

**Issue by Eldaw** [picotorrent/picotorrent#593]
If I've moved the PicoTorrent main application window to my secondary monitor, then when I go to View -> Preferences, the window pops up on my primary monitor (i.e. the wrong monitor). 

All of the other dialogs, e.g. Help -> About, and Help -> Check for Update appear correctly on the same monitor where the main application window is.

**Comment by vktr** [comment]
Closing this since v0.16 has been released and this should be fixed.
