### ISSUE TITLE
Show/hide torrent columns and details panel

### ISSUE THREAD

**Issue by zmni** [picotorrent/picotorrent#604]
Can you (re-)add that functionality? Thanks.

**Comment by zmni** [comment]
Oh, I mean the details panel. Please also add an option or shortcut to toggle show/hide.

**Comment by rvalles** [comment]
I'd rather have the details window back, too. I see the new details panel below as just clutter.

**Comment by vktr** [comment]
Both torrent columns and the details panel can be shown/hidden in #672 which will be released as v0.16. I'm closing this one.
