### ISSUE TITLE
Magnet links issue

### ISSUE THREAD

**Issue by ArtexJay** [picotorrent/picotorrent#608]
Does not fetch data from magnet links, until I add it to my downloads.

**Comment by ArtexJay** [comment]
When you add a magnet link to the torrent client a window pops up, usually with what files the magnet contains. For Pico, everything is blank, no size of the file, no information on what the files are, nothing. Until I click "ok" adding it to the downloads, then it starts downloading the metadata.

**Comment by vktr** [comment]
Yes, that is because the magnet link doesn't contain that information. Previously we pre-fetched this but that would block the UI until the torrent was fetched. There is a similar issue in #577.

**Comment by ttengine** [comment]
That is not true, qBitTorrent displays the contents after it reads the metadata & lets you choose what you want or don't want to download!

**Comment by ttengine** [comment]
> What I see is that it takes a really long time for the metadata to be retrieved. qBitTorrent also exhibits this behavior.

qBittorrent takes about 5 - 10 seconds to show me that information from the magnet link, there are some other sites -- and I think it's a site issue -- that makes it take much longer to display it.

**Comment by vktr** [comment]
qBittorrent searches the DHT for the torrent based on the info hash in
the magnet link. We used to do that as well but opted out since we
didn’t have a good solution that didn’t block the UI.

**Comment by ttengine** [comment]
Clearly someone is not a good programmer!  And who cares if it blocks the UI in the background for a bit, you can always cancel it by clicking the download button!

**Comment by vktr** [comment]
Thanks for the kind words! You are free to use whatever client meets
your needs :)

**Comment by smaragdus** [comment]
@ttengine 

> Clearly someone is not a good programmer! And who cares if it blocks the UI in the background for a bit, you can always cancel it by clicking the download button!

You are an idiot for sure. If there are no seeders retrieving info may last for eternity.

**Comment by ttengine** [comment]
If someone is stupid enough not to see there are no seeders showing for the listing on the trackers site, they are the stupid ones!

**Comment by ArtexJay** [comment]
I just hope  you manage to find a solution in due time, Pico is very promising torrent client.

**Comment by ArtexJay** [comment]
Just the fact that it does not fetch the metadata until you add it for download makes it a very cumbersome thing to have especially if you do not want to download the all the files in the torrent. Hope the issue gets solved .
I dont mind the UI being blocked till it's fetched especially since previously you could cancel the fetching and use the UI.

**Comment by StoyanDimitrov** [comment]
Here is the workaround that I use:
1.Clear the Start torrent checkbox in the magnet add dialog;
2. When torrent added rightclick on it in the list of all torrents and select Recheck.
This seems to be enough to trigger metadata download (if enough seeders) w/o UI blocking.

**Comment by vktr** [comment]
Hey everyone involved in this thread 😄 I've finally gotten around to fixing this issue once and for all. The new behavior is implemented in #672 and will be released with v0.16.

It now works as follows,

 * Paste your magnet links in the textarea.
 * Click *Ok*.
 * The Add torrent dialog will now open with only the information visible from the magnet link (ie. if it specifies a display name, it is shown here, etc). No files or sizes at this point.
 * In the background, the DHT is queried for the torrent, and once found, it will update the Add torrent dialog with the new information.
 * If you add the torrents before the query is complete, the query will cancel and the torrents will be added with the status Downloading metadata.

This will solve the issues and/or complaints with how it worked before. I think uTorrent works this way also, which I always thought was nice 😄 

Thanks for the patience!
