### ISSUE TITLE
Cannot Remove Columns & 1 Other Issue

### ISSUE THREAD

**Issue by ttengine** [picotorrent/picotorrent#616]
I like the ability to remove columns I don't really need to see when I'm using other torrent apps, but I cannot do this in PT, which is annoying, as I like to be able to have more control over that part of the window with sizing other columns.

Someone has already mentioned that when you start up PT it opens double the size, it is also annoying, but I've also found that when clicking on the icon in the systray and reopening PT, it doesn't open to fill the screen, it opens sitting somewhat lower and a little offscreen.

**Comment by vktr** [comment]
This is fixed in #672.
