### ISSUE TITLE
Error when opening 2+ .torrent files simultaneously 

### ISSUE THREAD

**Issue by MrX-at-GitHub** [picotorrent/picotorrent#621]
Select two or more .torrent files associated with PicoTorrent, obviously.
Run all of them at once.
Just one of them actually opens normally.
Second one or more throws this error:

![p](https://user-images.githubusercontent.com/16800851/39769053-abde315c-52b0-11e8-9790-f1b38f337871.png)

**Comment by vktr** [comment]
I can't reproduce this. Is this with cyrillic file names or some other case? I've tried with up to four torrents without issue.

**Comment by Dyras** [comment]
Does it work if you're not running it inside Sandboxie?

**Comment by vktr** [comment]
@MrX-at-GitHub is this inside Sandboxie?

**Comment by Dyras** [comment]
@vktr The [#] shows that it's inside Sandboxie. I doubt we'll ever hear from him again though, seeing as it's been 3 months.

**Comment by MrX-at-GitHub** [comment]
Yes, your doubt is correct. It was 12 days from May 8 to May 20 for me to get a reply, so no thanks. I'll pass on this torrent client. Development's too slow.

**Comment by vktr** [comment]
Sorry to hear that - I've been doing my best at managing real life as well as the various spare-time projects I run.

Anyways, I'll take a look at the issue this week. Perhaps there's someone else who might benefit from a fix 🙂

**Comment by aselwyn1** [comment]
who cares if he took a almost 2 weeks to reply its a free program that he is doing on the side

**Comment by MrX-at-GitHub** [comment]
I do care.

Thanks for you concern @vktr
