### ISSUE TITLE
Picotorrent : No downloaded to uploaded ration shown

### ISSUE THREAD

**Issue by Uzer1** [picotorrent/picotorrent#626]
Hello. I started this client today for the first time. I imported all my torrents. It seeds, but shows no downloaded to uploaded ratio. This is very important to know when to stop seeding based on this parameter. I see the rating column, but it stays at 0.000. Is it only me or this program shows no ratio?

**Comment by Uzer1** [comment]
**Update**
I have just discovered this. For torrents that I reloaded/rehashed from the HDD, the rating stays at 0.000. 
But I took a magnet link from PirateBay, put it in this program, and it began downloading. After that it commenced seeding, and the rating began growing. **I see it shows no rating, but only for torrents importand from the hard drive.**

**Comment by vktr** [comment]
Hi!

Have you actually downloaded anything or just started seeding? It’s
hard to calculate a ratio between upload/download if you haven’t
downloaded anything.

**Comment by Uzer1** [comment]
I just started seeding the files I had previously downloaded.

**Comment by vktr** [comment]
Did you download them with PicoTorrent or another client? PicoTorrent only tracks the data it downloads.

**Comment by Uzer1** [comment]
Yes, I could figure that out. I downloaded them with utorrent before that. Then imported into Picotorrent by rehashing. Now I understand how it works. I am closing this issue.
