### ISSUE TITLE
Picotorrent crashes all the time

### ISSUE THREAD

**Issue by xtemp09** [picotorrent/picotorrent#634]
Almost every time I add torrent, PicoTorrent crashes. I press "Send crash report".

Did the author receive them?

Windows 7 x64 Ultimate

**Comment by vktr** [comment]
Hi! Sorry you're seeing crashes. Yes, we receive the crash dumps and are continuously using them to improve PicoTorrent :) Can you attach or send me the torrent file which makes the app crash? viktor@viktorelofsson.se

**Comment by Bonobo79** [comment]
[This](magnet:?xt=urn:btih:d77f2554eeb912d8bd73a474751dd4cadbada2ef&dn=Serious+Sam%27s+Bogus+Detour+%5BGOG%5D&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969) torrent crashes pico whenever you try to select it inside the window.

**Comment by nxrighthere** [comment]
Torrent file for tests: [CrashTorrent.zip](https://github.com/picotorrent/picotorrent/files/2180871/CrashTorrent.zip)

**Comment by vktr** [comment]
Thanks! I’m on vacation right now but I’ll take a look when I get home.

**Comment by Urgarth** [comment]
> Thanks! I’m on vacation right now but I’ll take a look when I get home.

@vktr Hey! crashes still here. How we can fix it?
