### ISSUE TITLE
Help me building for XP

### ISSUE THREAD

**Issue by CardealRusso** [picotorrent/picotorrent#636]
Even after setting toolset for xp, i get an error when running on XP (sucess build) because some depedency or required file is not for XP. I need to figure out what is.

**Comment by vktr** [comment]
I think we use a few APIs that are not available on XP - and also the libraries that are pulled in from NuGet (wxWidgets, libtorrent, etc) are not compiled with the XP toolset.

If you're up for it you should start with building the libraries targeting the XP toolset and then build PicoTorrent against those.

**Comment by vktr** [comment]
Closing this as XP is not a target we will support.
