### ISSUE TITLE
WX rewrite broke reading with screen readers, making list views very difficult to use for blind users

### ISSUE THREAD

**Issue by pitermach** [picotorrent/picotorrent#638]
Steps to reproduce:

- Download a screen reader program. The one I use personally and  recommend is [NVDA](https://nvda-project.org/) because it's free and can be installed portably.
- Once NVDA is started and begins reading what's on the screen, start PicoTorrent, add a download and then try to navigate the main window with the keyboard (tab into the list of downloads, then use the arrow keys to highlight torrents)

Expected result: Just bring up the older version of PicoTorrent which does not use WX widgets and do the same steps. NVDA identifies the list as, well, a list, and when navigating with the arrow keys reads the columns in order.
Actual result: When you tab into the list, NVDA just says "wxdataviewctrlmainwindow" then reads bits and pieces of the text in the list at random, The highlight is not trracked when you move with the arrow keys, so acting on particular torrents is pretty much impossible.

This affects all lists in the main window, that is the list of torrents as well as the list of files, peers, and trackers. In addition, the standard keyboard shortcut to bring up the right click menu for an item (either shift+F10 or the applications key next to right control on most keyboards) don't work.
Most other parts of the app still work well. I can get to the menus and access the preferences, apart from the last section dealing with encrypting the settings file, which just says WXPropertyGrid, but no indication if the option is on or off.

I'm not sure why this issue is happening, as when it comes to cross platform user interface solutions, WX is by far the most screen reader friendly. I use many WX apps regularly that work very well with screen readers (IE NVDA itself, OBS Classic, Audacity, and TWBlue). I'm hopeful this can be resolved, I've been recommending PicoTorrent to my other blind friends because of its ease of use and accessibility, so I find it quite sad to see it regress in this area after this update.

**Comment by vktr** [comment]
That is very odd - thanks for the detailed report! 👍

**Comment by vktr** [comment]
Just tried in the ongoing branch for the next version (#672) and it works as it should. So stay tuned! And sorry for breaking screen reading.

**Comment by Flameborn** [comment]
Thank you for taking the time to fix this issue, it is very much appreciated.

**Comment by Danstiv** [comment]
Hello from 2023!
I just downloaded the latest release 0.25.0 and am experiencing the accessibility issues described above.
is it worth building the application from the latest commit and trying it out?, and should we expect accessibility issues to be fixed?

**Comment by Danstiv** [comment]
I tested 0.18 and 0.14, and in both the qt and wx versions I see accessibility issues.
@vktr are you interested in fixing accessibility?
I really like this client's idea and would like to use it 👍
