### ISSUE TITLE
Extra info bar

### ISSUE THREAD

**Issue by srinath-v** [picotorrent/picotorrent#64]
### Things we could display here
- Progress of individual files(if there are more than one files in the torrent)
- Option to include or exclude individual files after the torrent is added, as an extension to #60 
- A way to add more trackers
- Stats on trackers seeds peers etc.

**Comment by srinath-v** [comment]
When a torrent is selected this could be shown.

**Comment by srinath-v** [comment]
I know this is a bit much to ask, maybe somewhere down the line may be in 0.5.0

**Comment by vktr** [comment]
This is a good suggestion and I have something similar planned - it's not an information bar but a details dialog that opens when you activate a list item (double click or press Enter). It would show the details you mentioned.

**Comment by srinath-v** [comment]
:+1:
