### ISSUE TITLE
Failed to create connection to server 'PicoTorrent' on topic 'ApplicationOptions': a client's attempt to establish a conversation has failed.

### ISSUE THREAD

**Issue by Ruin0x11** [picotorrent/picotorrent#640]
Updating to the latest version causes this error on startup and the application exits. It seems to be a wxWidgets issue.

![2018-08-14 18_42_27-picotorrent error](https://user-images.githubusercontent.com/6700637/44127356-d311a518-9ff1-11e8-9aac-bc2da18faa61.png)

I did uninstall/reinstall, clear the AppData folder and settings, but the same message appears.

The operating system is Windows 7.

**Comment by vktr** [comment]
Are you running through Sandboxie?

**Comment by Ruin0x11** [comment]
No, just normally.

**Comment by wintercounter** [comment]
+1 Same issue for me. The client just freezed while downloading, now I cannot do anything with it.

**Comment by vktr** [comment]
This has been resolved with #672 which will be released as v0.16.

**Comment by StoyanDimitrov** [comment]
This one returned. It's not persistent as the OP, just one time.

Win7
