### ISSUE TITLE
Not all trackers are contacted when i added torrents

### ISSUE THREAD

**Issue by slrslr** [picotorrent/picotorrent#641]
PT 0.15.0

Hello,

i added torrent and on tracker tab i see on one torrent only one tracker was contacted and on other only ř trackers out of like 40. Rest trackers has nly "-" in all columns and clicking torrent or a tracker and selecting "Force reannounce" does nothing with it..

**Comment by vktr** [comment]
Hey @slrslr! Sorry for the late answer - I've reworked the Trackers tab to better show how the trackers are organized, and there's also new settings for announcing to all tiers and/or all trackers. It will be released in the next version, so I'm closing this. Feel free to open a new issue if you find anything wrong.
