### ISSUE TITLE
Search field to filter the torrent list

### ISSUE THREAD

**Issue by slrslr** [picotorrent/picotorrent#644]
Hello, it can be handy if there is a search field which would instantly filter out items which name matching the search query. Maybe the Ctrl+F would be sufficing, though quicker would be built in field.

Search case insensitive, all countries aphabets

If easy, thena dding also excluding operator, like:
linux -ubuntu

**Comment by parmeets834** [comment]
which software is used to import this project

**Comment by vktr** [comment]
Hey @slrslr! Late answer, but we added [a query language (PQL)](https://docs.picotorrent.org/en/master/pql.html) in the latest release to filter the torrent list :) Just hit View -> Console.
