### ISSUE TITLE
Open payload/downloaded file or folder by double click

### ISSUE THREAD

**Issue by slrslr** [picotorrent/picotorrent#645]
Hello, it can increase usefulness of the software if i can doubleclick torrent or double click folder/file (on Files tab) and it will either open particular file in an default application for that file type, or for the folder will open Windows explorer.

**Comment by ivanjaros** [comment]
Yeah, same here. I am missing the double-click on the torrent to open the directory and double-click on file to open/play the file.

**Comment by vktr** [comment]
Sorry for the delay on this one - the good news is I've planned it for the v0.16 release which will be out soon.

**Comment by vktr** [comment]
I've fixed this in #672. It won't directly open the file when double clicking it in the list, instead it will open explorer with the file selected.
