### ISSUE TITLE
Default remove should just remove torrent, not ask if you want to remove the files aswell. 

### ISSUE THREAD

**Issue by 4nderss** [picotorrent/picotorrent#66]
Would love if you could split the remove option up.
99% of the times I delete a torrent I want to keep my files. Quite annoying when I have to select that I want to keep the files every time I remove a torrent, with the risk of hitting the wrong one and removing the files. I'm used to having two delete options on dropdown, "Remove" and "Remove and delete files". Del button should bind to remove and keep files and shift+del should bind to remove and delete files. If possible :)

Love your work!

**Comment by vktr** [comment]
Great suggestion :) I've had this request from other users as well.

I'll add a checkbox to the remove dialog which you can mark to remember your choice. The default choice will also be editable in the preferences dialog.
