### ISSUE TITLE
Language not loading the numbers etc.

### ISSUE THREAD

**Issue by Andrewer11** [picotorrent/picotorrent#660]
In the hungarian version of PicoTorrent
the DHT, DL at the bottom statusbar not showing
and the pieces of a torrent
look the images what i uploaded....
First is the hungarian second one is the english
EDIT: i using the x64 portable version v0.15.0
![2018-11-17_17-17-28](https://user-images.githubusercontent.com/15068193/48663190-b0f57f00-ea8c-11e8-98db-8e57b3f3d35f.png)
![2018-11-17_17-16-33](https://user-images.githubusercontent.com/15068193/48663195-c9fe3000-ea8c-11e8-9430-a66ae6f639dd.png)

**Comment by Andrewer11** [comment]
btw may other langs are affected i did not check

**Comment by Andrewer11** [comment]
where can i find the `langs` dir?

**Comment by vktr** [comment]
@Andrewer11 Sorry, it was `lang`, it's located in the repository root, https://github.com/picotorrent/picotorrent/tree/develop/lang. I think this is the Hungarian translation file, https://github.com/picotorrent/picotorrent/blob/develop/lang/1038.json.

If so, you can compare it with the English one (1033.json) and see if anything is missing.

**Comment by DarkBasic86** [comment]
Version 0.15 still has this issue.
Its matches with the lang files of the outdated master branch and not the newer from the develop branch.

I'm not a developer, so I can't build on my own. (I don't have Visual Studio)
I tried to update the language resources with a programm called "Resource Hacker" but then the whole entry for e.g. German is missing in the drop-down menu.

Is there any other way to fix this for the current version - without compiling?

**Comment by vktr** [comment]
@DarkBasic86 Until v0.16 is released, you can always try to use the beta which got released a few days ago - it contains multiple fixes for most of the issues here on Github.

https://ci.appveyor.com/project/picotorrent/picotorrent/builds/27999986/job/vac2okpw5bdd7j6o/artifacts

**Comment by Ilya87** [comment]
![Снимок экрана (296)](https://user-images.githubusercontent.com/1446573/67463391-03023580-f64a-11e9-9536-30114cc2bd8f.png)
Russian language. Bug is still here.

**Comment by vktr** [comment]
It is an error in the translation file. All %d and %s should be changed to %1, %2 etc. I’ll see if I can adjust the language files.

**Comment by Ilya87** [comment]
Downloaded the latest commit's build c8c51afd47b08772601800d758b37ae841dc1f30 - in Tracker's tab the time of next announce is shown as 0h %2m %3s, Other localithation issues are fixed as I can see.

**Comment by vktr** [comment]
I'm closing this since I think most "issues" with the translations are resolved - we now fall back to English instead of the translation keys. Also, we use Crowdin to translate so it's easy to help - https://crowdin.com/project/picotorrent.
