### ISSUE TITLE
Download priority shortcut

### ISSUE THREAD

**Issue by itsarjunsinh** [picotorrent/picotorrent#662]
PicoTorrent 0.15.0 supports changing the download priority of a folder.  However it is not possible to the change download priority of multiple files within a folder at once. So it is required to manually alter the download priority of files which is a very tedious process. Shortcuts for changing download priority would make this process a lot easier.

**Comment by zeerorg** [comment]
The manager lacks the ability to select multiple torrent files in the pane. I was working on that feature. Will that feature be helpful in this scenario?

**Comment by itsarjunsinh** [comment]
Yes, I think the ideal solution would be the ability to change the download priority of multiple files at once. If that's possible then there's not a lot of use for download priority shortcuts.

**Comment by vktr** [comment]
@zeerorg Looks cool! I'm currently doing some big refactorings in preparation of the next version and this would be fixed by that as well.

I'd appreciate a PR but I don't think it will make it to release. Hit me up on Gitter if you want to discuss!

**Comment by vktr** [comment]
Closing this since v0.16 has been released and this should be fixed.
