### ISSUE TITLE
IP blocklists

### ISSUE THREAD

**Issue by Ishino0** [picotorrent/picotorrent#663]
Hi,

First, thanks for your pico, very powerfull & tiny torrent app, do the job, remember me the good old days with μT.
I love the gui integration w/ windows 10.

And, I wanted to know if you could add the ipfilter feature.
Like in Deluge, or just take into account the ipfiler file (dat etc..) like in μT, qB.. .

That's a small feature,  that can be very useful.
I use that for family pc's  to give an easy and simple minimum protection againt hadopi (fr), and it works so.

Thanks, best regards,
from a guy lost in France :)

ps: sorry for my english if i could some mistakes ^.-

**Comment by vktr** [comment]
Similar to #796
