### ISSUE TITLE
Crash when disk full & restart loosing all torrents

### ISSUE THREAD

**Issue by MrVhek** [picotorrent/picotorrent#664]
Hello,
Just got a problem with my torrent, not the first time it's happening for me. I have the 0.15 version so the last (as it seems).
The first problem is I set the download for the day and my diskspace went full, and it's seems that the client crashed when reaching the full space.
The second issue is that I losed all my download because of the crash (mostly magnet), are they saved ? It's not the first time that I loose my torrent due to crash.

Thanks for your work anyway, love it :)

**Comment by vktr** [comment]
Hi! Thanks for the report. I'll see if I can add a check for when the disk space gets below a certain threshold.

**Comment by vktr** [comment]
I've added this feature in #672 with a fixed (for now) percentage at 5% disk space. It's in the config but not adjustable in the UI at the moment.
