### ISSUE TITLE
[Feature Request] GeoIP Flags + Host name resolver

### ISSUE THREAD

**Issue by hvonw** [picotorrent/picotorrent#665]
Can you add these features If it will not have much effect on performance? (Default: Off)
I think these two features are already available in the lib picotorrent uses. (arvidn/libtorrent)

**Comment by vktr** [comment]
Hi! The version of libtorrent we use (recent `master`) does not include this - I know libtorrent previously had this functionality but it has been removed. It doesn't mean we shouldn't do it, though. I like the idea.

**Comment by hvonw** [comment]
Hi Viktor,
Thank you for all your hard work. Been using your client for a while. It's really great, lightweight client.

**Comment by vktr** [comment]
Closing this since v0.16 has been released and this is added.
