### ISSUE TITLE
Donation link page errors on website

### ISSUE THREAD

**Issue by blueshell1** [picotorrent/picotorrent#669]
Hi, just wanted to drop a note that it looks like the donation link on the PicoTorrent website seems to be broken at the moment. Possible you need to update your Stripe link?

This is on https://picotorrent.org/#/donate

In the Stripe pop-up when clicking on the Donate link this error appears:

    Expired API Key provided: pk_live_********************Axti

Just wanted to let you know :)

**Comment by vktr** [comment]
Hi! Thanks - yes I'm aware :) I had to roll the API keys since the donation form was a target of someone trying to make hundreds of donations with stolen credit card numbers. I just haven't had the time to put things back in order.

Thanks anyway!

**Comment by vktr** [comment]
Donation button is now available again 😄
