### ISSUE TITLE
Scaling text breaks with Windows causes blurry text

### ISSUE THREAD

**Issue by Siilwyn** [picotorrent/picotorrent#677]
Text in picotorrent seems to be blurry when changing the scaling for text under Window's display settings.

Example with the explorer open for comparison:
![image](https://user-images.githubusercontent.com/5701149/50966227-9c55c600-14d4-11e9-931a-c99679b28a71.png)

**Comment by vktr** [comment]
Does it work if you log out and back in again?

**Comment by Siilwyn** [comment]
@vktr thanks for the reply, do you mean log out of windows? If so: that doesn't resolve it, I've had multiple reboots since but this bug is always present.

**Comment by Siilwyn** [comment]
Oh I see the commit now! For posterity this issue is fixed by 1aefffe909ea3277214e49bded09a3117ed288d6.

Can't wait for the upcoming release!

**Comment by vktr** [comment]
Closing this since v0.16 has been released and this should be fixed.
