### ISSUE TITLE
Easier Partial Downloading (FR)

### ISSUE THREAD

**Issue by junh1024** [picotorrent/picotorrent#678]
Currently, you need to do 3 clicks to select files to DL
Click >  Priority > Do not download

You could make it easier to do Partial Downloading by:
- implementing checkboxes like utorrent & transmission
https://www.simplehelp.net/images/utorrent/ut10a.jpg
https://www.simplehelp.net/images/transmission/tm03.png

- Moving  "Do not download" up 1 level in menu hierarchy

**Comment by VideoPlayerCode** [comment]
+1

**Comment by vktr** [comment]
You can multi-select files in the list and set all of them to *Do not download* in one go, or you can select a folder (in case of a multi file torrent) and set the folder to *Do not download*. This will also set the files in that folder to *Do not download*.

**Comment by vktr** [comment]
There's now checkboxes in the list view when selecting files so I think it's quite straight forward to skip files now.
