### ISSUE TITLE
Will there be a Mac version?

### ISSUE THREAD

**Issue by gam-phon** [picotorrent/picotorrent#68]
Will there be a Mac version?

**Comment by vktr** [comment]
Hi, yes, without promising when :smile: The plan is to make PicoTorrent cross-platform, and OSX is the next OS to implement after Windows.

**Comment by gam-phon** [comment]
Thanks ^_^ and waiting for a Mac version.

**Comment by voldyman** [comment]
any update on this front?

**Comment by vktr** [comment]
@voldyman The only update so far is that PicoTorrentCore is cross platform, but we haven't started writing any GUI on top of it.

**Comment by voldyman** [comment]
@vktr thats nice to hear, i don't have mac GUI experience so sadly can't help but the code look pretty clean. great work!

**Comment by vktr** [comment]
An OSX version will probably not happen in the near future... Sorry. Closing this for now.
