### ISSUE TITLE
Remove taskbar progress indicator when no torrents are downloading

### ISSUE THREAD

**Issue by wkoncki** [picotorrent/picotorrent#680]
Hi

I currently have one torrent that finished downloading and is being seeded in Pico Torrent yet taskbar icon is still highlighted. It looks like this:
![taskbar](https://user-images.githubusercontent.com/9073427/51086315-b813d300-1745-11e9-826e-38526a1192d4.png)
It would be great if this green background was not displayed when there are no torrents currently downloading.

**Comment by vktr** [comment]
This is fixed in #672.
