### ISSUE TITLE
Unstarted torrent will disappear after restart

### ISSUE THREAD

**Issue by thumbsized** [picotorrent/picotorrent#682]
When I add new torrent and I don't start it and I restart picotorrent the torrent will no longer be shown in the list.

**Comment by vktr** [comment]
Strange - can you give me a step by step on how you reproduce it?

**Comment by vktr** [comment]
I can't reproduce it in #672 so I'm closing this for now.

**Comment by thumbsized** [comment]
Happened to me again. I think it is the same as #686
