### ISSUE TITLE
Dont' use %temp% as environment

### ISSUE THREAD

**Issue by beerisgood** [picotorrent/picotorrent#684]
I try start the PicoTorrent-0.15.0-x64.exe from D:\FOLDER\FOLDER\FOLDER\FOLDER which try to start from
C:\Users\USER\AppData\Local\Temp\{D6235002-0CDE-475E-BFEE-BA75E277B4B8}\.cr\PicoTorrent-0.15.0-x64.exe and got blocked by SRP.

Why the binary just can't start from the path i start it? Using %temp% isn't good choice, security wise

**Comment by vktr** [comment]
Hi! I’m not sure I follow. Are you using the installer or the zip file?

This looks like you are trying to run PicoTorrent.exe straight from the zip file (letting Windows extract it to a temp dir). Is that the case?

Otherwise, some further information on your environment and how you provoke the error would be nice! :)

**Comment by beerisgood** [comment]
I use the "PicoTorrent-0.15.0-x86.exe" from https://github.com/picotorrent/picotorrent/releases

Isn't that the binary which start without any installation? Otherwise the label "installer" would be better.
Then of course i would use PicoTorrent-0.15.0-x64.zip

**Comment by vktr** [comment]
Yeah, the `.exe` file is an installer - it probably tries to extract some temporary files to the directory you mentioned before it goes ahead with installation. I'll see if we can use a better naming scheme in the future- sorry about the confusion 😄 

And as you found out, the `.zip` files are portable versions which run directly from the folder you extract them to. Glad you got it working!

**Comment by beerisgood** [comment]
I guess the problem is then solved :D
