### ISSUE TITLE
Chinese/Japanese characters in magnets crash on 0.15.0 : "Total error when parsing"

### ISSUE THREAD

**Issue by taotien** [picotorrent/picotorrent#685]
Any magnet link that has Chinese and Japanese characters causes this error, resulting in an immediate crash. Works fine if the link is pure English or a .torrent file.

**Comment by vktr** [comment]
Hi! Can you attach a magnet link that causes a crash? Or email it to me at viktor@viktorelofsson.se if it’s sensitive!

**Comment by taotien** [comment]
Yeah, here's a random example:
magnet:?xt=urn:btih:39a05b618be58e85c59786d9f6c8b7b57b9c766a&dn=%E3%80%90%E5%9B%BD%E6%BC%AB%E3%80%91%5B%E8%90%8C%E5%A6%BB%E9%A3%9F%E7%A5%9E%5D%5BMeng%20Qi%20Shi%20Shen.2018%5D%5B01-12%5D%5B1080P%5D%5BCHD%5D&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce

It works when pasting directly into PicoTorrent.

Also, just tested with Edge browser, doesn't crash. Firefox does. Maybe it has to do with how FF converts the link?

**Comment by vktr** [comment]
Thanks! I'll see if I can reproduce it, and if so schedule a fix for the next release.

**Comment by taotien** [comment]
Great! Looking forward to next release~

Also just noticed the link I grabbed at random was something I was looking for lel

**Comment by vktr** [comment]
This has been fixed in a recent commit in #672 and will be released with v0.16 😄 Thanks for the report!
