### ISSUE TITLE
Torrents added via magnet link will disappear from download list if PicoTorrent is exited before meta data was downloaded

### ISSUE THREAD

**Issue by ecrvnr** [picotorrent/picotorrent#686]
If i add a torrent via magnet link and close PicoTorrent before the meta data information was downloaded, the torrent will be missing from the download list the next time i start PicoTorrent.

Steps to reproduce:

1. Add Magnet link torrent
2. Immediately close PicoTorrent
3. Start PicoTorrent again
4. Torrent added in Step 1 is missing from the download list.

I know this was already mentioned in #280 but that other issue was closed and that behaviour persists.

**Comment by vktr** [comment]
Hi! This is fixed in #672 which is the PR for the next release (v0.16). Sorry for the trouble!

**Comment by ecrvnr** [comment]
@vktr Oh hey that was quick! I was a bit worried because the other issue was from 2016, but glad to see it wasn't forgotten. Thanks!
