### ISSUE TITLE
Localization Docs

### ISSUE THREAD

**Issue by raspher** [picotorrent/picotorrent#688]
I see there are some languages, but there is no documentation how it should look like.

filename should contain only LCID - https://www.science.co.il/language/Locale-codes.php

those and more information should be readable from http://docs.picotorrent.org/en/master/

**Comment by vktr** [comment]
Thanks, yeah we're missing quite a lot of documentation sadly. I'll see if I can take some time to update it in preparation for the next release :)

**Comment by vktr** [comment]
We now use Weblate for translations which is a web tool which makes it way easier. So I think this issue can be closed, but I still agree we need better documentation in general :)

Weblate at https://translate.picotorrent.org
