### ISSUE TITLE
Pico Torrent constantly crashing 

### ISSUE THREAD

**Issue by blountb1** [picotorrent/picotorrent#697]
Pico Torrent is constantly crashing when I just click on it anywhere...I try to remove a finished download and that makes it crash as well. How Do I fix this?

I'm using PicoTorrent-0.15.0-x64 and have Windows 10 build 15063.

**Comment by vktr** [comment]
Odd - it seems like it has got stuck in an invalid state. You might need to remove some state data from the PicoTorrent application data folder - `%APPDATA%\PicoTorrent\Torrents`. The files in that folder should come in pairs, one `.torrent` and one `.dat` with the same base name. See if you can find a single `.dat` file and remove that.

**Comment by blountb1** [comment]
There was no folder in my C:\Users\defaultuser0.DESKTOP-RME0S0B\AppData\Roaming directory but there is a PicoTorrent folder in my

C:\Users\defaultuser0.DESKTOP-RME0S0B\AppData\Local\PicoTorrent directory.

I saw a session.dat file there and deleted it and then restarted Pico and I was able to remove a finished torrent but then just as soon as I tried to click *anywhere* (like last time) after that the program crashed like last time. Any other ideas? :)

**Comment by vktr** [comment]
If you feel adventurous you can delete the `Torrents` folder in the same directory. This will remove all torrents from PicoTorrent (but not the data).

**Comment by blountb1** [comment]
I actually deleted the torrents folder last night because some torrents weren't downloading then while ago downloaded more and everything seemed fine but then completely closed the program and reopened it just now to add more torrents and again like before just as soon as I tried to click *anywhere* (like last time) after that the program crashed.

**Comment by vktr** [comment]
Hi @blountb1! Can you try the latest version (0.19) and see if the issue has been resolved? Closing this for now but feel free to reopen or create a new issue if it's not.
