### ISSUE TITLE
Pico Torrent downloading file's meta is slow and most of the time not downloading at all

### ISSUE THREAD

**Issue by Alexdiff** [picotorrent/picotorrent#698]
Waited for like half an hour and nothing appeared, getting file's meta is extremely slow or not even getting it at all
![picotorrentissues](https://user-images.githubusercontent.com/46273530/64066255-7dfa3180-cc41-11e9-866e-6accec84998f.png)

**Comment by Alexdiff** [comment]
It was really annoyed since you cannot decide which files to skip downloading to save storage and download time until you click OK

**Comment by vktr** [comment]
This should be well fixed in 0.17.
