### ISSUE TITLE
[Feature Request] Ability to randomly change listening port

### ISSUE THREAD

**Issue by Alexdiff** [picotorrent/picotorrent#699]
In QBitTorrent, there's an option to randomly change listening port every time the program restart, doing that sometimes speed up download time

**Comment by VideoPlayerCode** [comment]
Well, I won't say the feature is bad. But, if you always change port, your known node on the DHT network will always be changing. This in turn means two things if you change port constantly:

1. Magnet (aka DHT) downloads will be extremely slow and will have trouble finding Metadata and peers. 
2. Your router will get DDOSed by thousands of DHT nodes attempting to connect to your old, closed port. 

The only benefit of port randomization would be for slight extra obscurity VS your ISP seeing that one specific port is doing all traffic. But most people (and ISPs) do not give a damn about that. 

Randomizing port is therefore mostly harmful and placebo.
