### ISSUE TITLE
Notification of the need to restart the application after changing the language

### ISSUE THREAD

**Issue by Rakleed** [picotorrent/picotorrent#702]
Please add a notification about the need to restart the application after changing the language. Since now after changing the language in the preferences, the application language does not change and there is no notification that you need to restart the application, this complicates the understanding of this setting.

**Comment by vktr** [comment]
I've added this to #672.

**Comment by Rakleed** [comment]
@vktr in versions 0.20 and 0.21, and possibly in 0.19, this notification disappeared when changing the language. Why?

**Comment by vktr** [comment]
It's probably a regression from the move to wxWidgets. Sorry about that. I'll fix it for the next version.
