### ISSUE TITLE
 keyboard shortcut

### ISSUE THREAD

**Issue by h5rdly** [picotorrent/picotorrent#707]
First of all, cheers. Finally, an open source utorrent replacement.

It looks like double clicking on torrent file from a file manager doesn't sit well with PicoTorrent - I get a "Could not parse torrent file" error.

From inside Pico, I can't use Ctrl+O, or whatever applicalbe shortcut, to open the "Add Torrent" menu.

Would it possible to add a predefined keyboard shortcut for that feature?

Thanks,
Eli

**Comment by vktr** [comment]
There's lot of new things in the upcoming v0.16, and I'll make sure keyboard shortcuts are included. The error when adding torrents shouldn't happen - would you mind sending me the torrent and I'll have a look? viktor@viktorelofsson.se

**Comment by h5rdly** [comment]
Hey,

Sounds awesome!

It's seems to be occuring with torrents that have non English characters - basically any torrent from rutracker.org who's name is not fully in English

**Comment by nxrighthere** [comment]
I have the same issues with 0.16.0, [DEL] hotkey doesn't work anymore on torrents. Also, torrents with non-English characters cannot be added, and the application's window position always reset at startup.

**Comment by vktr** [comment]
Keyboard shortcuts didn’t make it as I have a few ideas around that. 

I haven’t had any trouble with non-English torrents when I tested. Can you email me the torrent and I’ll have a look? viktor@viktorelofsson.se

**Comment by nxrighthere** [comment]
@vktr Torrent sent. 😉
