### ISSUE TITLE
VCRUNTIME140_1.dll is missing 

### ISSUE THREAD

**Issue by massic80** [picotorrent/picotorrent#708]
Hi,
I just received the update notification and i promptly moved here to download the latest (0.16) version.
The problem is that, once installed, when I attempt to run it, it says that `VCRUNTIME140_1.dll` is missing: I have different versions of Visual C++ installed, but none of them has the __1_ version of VCRUNTIME140.
How should I solve?

**Comment by massic80** [comment]
Solution:
I noticed in latest commits that you moved to Visual Studio 2019 for building.
I wondered whether installing the latest Visual C++ Redistributable from https://support.microsoft.com/it-it/help/2977003/the-latest-supported-visual-c-downloads (turns out it's 2015-2019) could solve the trouble, and looks like it did :)

**Comment by massic80** [comment]
I wonder whether also the link to VC++ 2017 for portable version in readme.md has to be updated...

**Comment by nonpcnpc** [comment]
yep, same issue.

**Comment by massic80** [comment]
@nonpcnpc I don't know whether it's the optimal solution, but I solved it ;)

**Comment by Darth-Carrotpie** [comment]
> Solution:
> I noticed in latest commits that you moved to Visual Studio 2019 for building.
> I had 2005, 2012, 2015 and 2017 but not 2019 and wondered whether installing the latest Visual C++ Redistributable from https://support.microsoft.com/it-it/help/2977003/the-latest-supported-visual-c-downloads (turns out it's 2015-2019) could solve the trouble, and looks like it did :)

Had the same error and this fixed it! Thanks! ;)
