### ISSUE TITLE
Only first torrent active

### ISSUE THREAD

**Issue by keithlatheron** [picotorrent/picotorrent#709]
I have just upgraded from version 0.15 to 0.16.  The previous version was working fine (apart from the odd crash), but the latest version only downloads from the first torrent in the list, even though my settings specify 5 active torrents.

Furthermore, if it can't download from the first torrent, it doesn't then try activating the next one, and so on.  All but the top torrent remain "Queued" until the top one is complete.

**Comment by vktr** [comment]
Sorry for the issues you’re having! I’ll have a look at both issues.

You might be able to force resume a torrent or move it up the queue to activate it in the meantime.
