### ISSUE TITLE
Missing Files 

### ISSUE THREAD

**Issue by ozonesn** [picotorrent/picotorrent#712]
![Untitled](https://user-images.githubusercontent.com/9211383/67454472-ec5bde80-f649-11e9-897a-820273ccbef7.png)

**Comment by vktr** [comment]
Hi! This was reported and fixed (but not released). You can try the installer from here and see if it solves the issue,

https://ci.appveyor.com/project/picotorrent/picotorrent/build/job/w4c6sb7svp44nsxr/artifacts
