### ISSUE TITLE
In que status

### ISSUE THREAD

**Issue by Ilya87** [picotorrent/picotorrent#713]
In version 0.16 most of my torrents are in status "In que" instead of seeding. Is it a normal behavior? Because they only start to upload when I choose force seeding.

**Comment by vktr** [comment]
Hi! It has been fixed but not released. You can try the build from AppVeyor and see if it solves the issue. 

https://ci.appveyor.com/project/picotorrent/picotorrent/build/job/w4c6sb7svp44nsxr/artifacts

**Comment by Ilya87** [comment]
Yes, it is fixed now.

**Comment by Ilya87** [comment]
Now this behavior repeated - the torrent starts to download, after getting to 3% (about 1 minute) it returned to "queued" status. After force start it downloads normally.

**Comment by vktr** [comment]
Odd - I can't seem to reproduce it. What is your settings for active downloads?

**Comment by Ilya87** [comment]
Maybe I was mistaken. If the bug won't appear in few days, I'll close the issue.
