### ISSUE TITLE
Missing Icon on Taskbar

### ISSUE THREAD

**Issue by canyon1991** [picotorrent/picotorrent#714]
Hi,

Since I upgraded to the new version 0.16.0 the Taskbar icon is gone. I am using Windows 10 and it is not pinned. I have also uninstalled it and installed it again as well as restarted Windows. 

Could it be a bug or is just me?

![image](https://user-images.githubusercontent.com/56959429/67475501-3e066800-f64e-11e9-8103-f5c76a474aec.png)

Thank you

**Comment by vktr** [comment]
I've tried to reproduce this but I can't. Using a clean Windows 10 machine, I installed v0.15 and then upgraded to v0.16 - the taskbar icon was still present. I'll do some more investigation...

**Comment by canyon1991** [comment]
After installing 0.16.1 the icon on the taskbar came back to normal.

**Comment by vktr** [comment]
Awesome! 😄
