### ISSUE TITLE
V0.16.0 hangs when a magnet link is being added on Windows 10 1909

### ISSUE THREAD

**Issue by erayrafet** [picotorrent/picotorrent#717]
Heres's the link. I haven't tested it extensively with other links or torrent types though. The problem is reproducible after a reinstallation of the app as well as directly updating from v0.15.0.

magnet:?xt=urn:btih:a2ff92007692d768ed60ce18cd0adc1535e59d68&dn=Can.You.Keep.A.Secret.2019.1080p.WEB-DL.H264.AC3-EVO[TGx]&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.uw0.xyz%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce

**Comment by vktr** [comment]
Thanks! I've fixed an issue related to this in #716 - it will be included in the next release. You can try the installer from the AppVeyor artifacts to see if it solved your problem as well,

https://ci.appveyor.com/project/picotorrent/picotorrent/builds/28359345/job/wy1uop0c8xixf7gs/artifacts

**Comment by erayrafet** [comment]
Still crashes.

**Comment by vktr** [comment]
I managed to reproduce it and also found a workaround - when you click add after pasting the magnet link and then select the torrent in the list view, it will crash the application. If you wait for the metadata to be fetched before selecting it, all will work OK.
