### ISSUE TITLE
Avg detect last update as "IDP.Generic" virus

### ISSUE THREAD

**Issue by Ziffax** [picotorrent/picotorrent#721]
Even adding the .exe  as exception i can't install  it ( i deleted it after the update went wrong,file blocked)

No idea what to do, i'll try an early version.
[PicoTorrent_20191024225439.log](https://github.com/picotorrent/picotorrent/files/3769439/PicoTorrent_20191024225439.log)

Log attached

**Comment by vktr** [comment]
Hi! Thanks for the report - I'll check if I can reproduce this in a clean Windows 10 VM.

**Comment by Ziffax** [comment]
Hey man, got the installation fixed after a quick restart, after that, when tryng to launch it, it says "VCRUNTIME140_1.dll" missing
Downloaded the .dll, placed in the directory, working (last update)
Probably an issue by my side, something blocking the installation but no idea, the anti virus seems "quiet" about it now

**Comment by vktr** [comment]
@Ziffax That's a known issue and has been fixed but not released (yet - I'm working on that release now). You can try the installer from the AppVeyor build until then.

https://ci.appveyor.com/project/picotorrent/picotorrent/builds/28361302/job/kxdpm79bb8ibr4v9/artifacts

**Comment by Ziffax** [comment]
NP all good now, thanks for your time, love your program.
