### ISSUE TITLE
Bad hash value when installing Picotorrent 0.16.1

### ISSUE THREAD

**Issue by TechnoGreg** [picotorrent/picotorrent#726]
Here is a log extract :
`[29E4:0844][2019-10-25T08:09:29]e000: Error 0x80091007: Hash mismatch for path: C:\ProgramData\Package Cache\.unverified\VC_redist.x64.exe, expected: 3B32BC4B8DEC32FD52A8F4BDA5648C3A8D999D7C, actual: 3155CB0F146B927FCC30647C1A904CD162548C8C`

**Comment by TechnoGreg** [comment]
More infos : the release on Appveyor is clean

**Comment by vktr** [comment]
I can't reproduce this in a clean Windows 10 install. I found another bug in VC redist version detection though, so thanks for making me look 😄 Can you try again?

**Comment by TechnoGreg** [comment]
I download again the website version, and it installs correctly. I haven't changed anything but tried the appveyor artifact.
