### ISSUE TITLE
VC_redist.x64.exe restarted PC without warning when installing v0.16.1

### ISSUE THREAD

**Issue by Eldaw** [picotorrent/picotorrent#729]
When installing v0.16.1 over v0.16.0, my computer restarted automatically during the installation. I was not asked whether it was OK to restart, and I was given no warning whatsoever. I had no chance to close any documents or any other running applications.

Looking in Event Viewer, I see that the culprit is VC_redist.x64.exe that initiated the automatic restart of my PC.

```
Event ID:      1074
The process C:\WINDOWS\Temp\{9B5B39E6-A845-4343-914F-417DDCED30CC}\.cr\VC_redist.x64.exe has initiated the restart of computer [redacted] on behalf of user [redacted] for the following reason: Application: Installation (Planned)
 Reason Code: 0x80040002
 Shut-down Type: restart

```

Please fix this, as it was very rude for the installation to just abruptly restart my PC without any warning.

**Comment by vktr** [comment]
Hi! Sorry about that - I thought the VC redist installer would prompt before any restart. I'll add the `/norestart` flag and see if that would solve the issue - hard to test though.
