### ISSUE TITLE
Memory overflow

### ISSUE THREAD

**Issue by Ilya87** [picotorrent/picotorrent#734]
I have 24 torernts (about 200-250 Gb Total) in PicoTorrent, Windows 10 x64, after about 12 hours of seeding Windows Task Manager shows that 76% of my RAM is used ( I have 16 Gb RAM), after I closed PicoTorrent Task Manager shows memory consumption dropped to 17%.
Also System Resources Monitor shows 24-33/sec physical memory pages errors
![Снимок экрана (328)](https://user-images.githubusercontent.com/1446573/67601640-87090a00-f77d-11e9-88c5-16377596c3c7.png)
.

**Comment by Ilya87** [comment]
![Снимок экрана (341)](https://user-images.githubusercontent.com/1446573/67757251-7b9f3280-fa4c-11e9-9b2c-13d2b7de0442.png)

**Comment by vktr** [comment]
Hi! Thanks for the report. I'll check!

**Comment by armpogart** [comment]
Same issue on the latest version (0.17.0). I have a feeling that PicoTorrent downloads the file to some sort of ramdisk, as as soon as I close the Pico, something is writing to HDD (haven't checked what process does it exactly) and the ram memory is being freed in parallel.

**Comment by armpogart** [comment]
I can also force the HDD writing by simply pausing the download, as soon as I do pause, the RAM is being freed and in Task Manager I see `System` process writing to HDD on max speed for some time.

**Comment by vktr** [comment]
I think libtorrent queues the disk operations in a separate write thread which could give the impression of the downloads filling up memory. I'll see if I can tune the libtorrent settings somehow.

**Comment by Ilya87** [comment]
> I think libtorrent queues the disk operations in a separate write thread which could give the impression of the downloads filling up memory. I'll see if I can tune the libtorrent settings somehow.

Check please if this bug can appear when seeding, not downloading torrents.

**Comment by vktr** [comment]
Hi @Ilya87! Can you try with the latest version to see if this is resolved?

**Comment by Ilya87** [comment]
I think it is fixed now.

**Comment by ericbruggema** [comment]
Still there, today i ran pico and after one hour it consumed over 70% of my memory...  when closed, it went back to 30% and that's normal for my doing....

**Comment by Rachid90** [comment]
The problem is still here in late 2023
