### ISSUE TITLE
Delete button no longer removed the torrent

### ISSUE THREAD

**Issue by rockernaap** [picotorrent/picotorrent#740]
The delete button (on your keyboard, AKA del) no longer removed the torrent from the list.

**Comment by Rakleed** [comment]
@rockernaap Do you have version [0.17.0](https://github.com/picotorrent/picotorrent/releases/tag/v0.17.0) installed? Because in this version the Del hotkey was just added to delete torrents, and it works for me.

**Comment by rockernaap** [comment]
It looks like I was on an older version. In 0.17.0 it is indeed fixed.
