### ISSUE TITLE
HCSC Employees time cards Missing for Oct'19

### ISSUE THREAD

**Issue by Computech123-Kirby** [picotorrent/picotorrent#752]
Hi Team,

We didn't see the employees time cards in Fieldglass for Oct'19 for Payment. Can you please Help us on this.

Please find attached the missing hours statement. 

Thank you,
 
Bala Suthari
Computech Corporation
100 W Kirby St. Detroit, MI 48202
p +313-202-0929 X 57004 f + 313-281-2211
bala.suthari@computechcorp.com
[Email Hours statement  for all clients (3).xlsx](https://github.com/picotorrent/picotorrent/files/3815320/Email.Hours.statement.for.all.clients.3.xlsx)

**Comment by vktr** [comment]
Hey! Below is actual footage of me looking through my TPS reports to find your missing hours. Thanks. 


![](https://thumbs.gfycat.com/ThirstyPotableLadybug-size_restricted.gif)
