### ISSUE TITLE
Select many on the list crashes the application

### ISSUE THREAD

**Issue by dawidgorczyca** [picotorrent/picotorrent#754]
When I'm trying to select many torrents on the list, using keyboard arrows and shift Pico crashes every time.
Windows 10, PicoTorrent 0.17.0

**Comment by Ilya87** [comment]
https://ci.appveyor.com/project/picotorrent/picotorrent/builds/28606172
Try to download build for your CPU architecture (x86 or x64) - choose artifacts tab.

**Comment by vktr** [comment]
@dawidgorczyca please try the latest version and see if this is resolved. Feel free to reopen och create a new issue if it's not!
