### ISSUE TITLE
The irrelevant version number of PicoTorrent is displayed on the download page

### ISSUE THREAD

**Issue by Rakleed** [picotorrent/picotorrent#755]
The irrelevant version number of PicoTorrent is displayed on the [download page](https://picotorrent.org/download/). Now 0.15.0 is displayed, although the current version is 0.17.0.

<details>
<summary>Screenshot</summary>

![screenshot-picotorrent org-2019 11 09-12_10_32](https://user-images.githubusercontent.com/19418601/68526156-f9372e00-02e9-11ea-8138-9e6059044452.png)

</details>

**Comment by VideoPlayerCode** [comment]
Oh hehe @vktr this one is an easy fix. :D

**Comment by Rakleed** [comment]
@vktr please take a look at this issue and add the desired label.

**Comment by Rakleed** [comment]
@vktr why is it a feature request, if it is actually a bug report?

**Comment by vktr** [comment]
![](https://media2.giphy.com/media/3zFcbgHoIXzykQc7vU/giphy.gif)

The site has been fixed 😃
