### ISSUE TITLE
Magnet links are crashing it AND can't expand fie tree

### ISSUE THREAD

**Issue by hl24a3** [picotorrent/picotorrent#758]
0.17 and 0.16 has the same issue for me, magnet links are crashing it, so I have to always download a file and drag and drop it

when torrent is running or even paused it won't allow to expand the file tree to disable some files from downloading

**Comment by vktr** [comment]
Hi! The file tree issue is fixed in the latest builds, here https://ci.appveyor.com/project/picotorrent/picotorrent/build/job/oq92fkr73ojxsrhh/artifacts

Is it all magnet links which causes a crash or specific ones?

**Comment by hl24a3** [comment]
All of them were crashing, I'm back on 0.15 now.

But also I couldn't select multiple torrents anymore, only one by one I could right click on them and do whatever action.

Back on 0.15 I can do everything now.

**Comment by vktr** [comment]
I see - the multi-selection has been fixed in the latest builds as well.

**Comment by hl24a3** [comment]
right, I'll give it a go later and see if this latest build is working fine, will let you know

**Comment by canyon1991** [comment]
I am having issues too with magnet links. It crashes when is "loading" the magnet link. I need to restart and then the magnet link works, if I wait a few second and add a second magnet link it crashes again and loses the "memory" so i need to start the downloads again.

**Comment by VideoPlayerCode** [comment]
@hl24a3 Any news of testing the latest build?

**Comment by hl24a3** [comment]
No I actually stayed on the old v0.15, it works well, I'll try it maybe when it officially gets released

**Comment by vktr** [comment]
Hey @hl24a3! We actually released v0.19 yesterday which is more similar to the old v0.15 in a lot of ways - your issues should be fixed in that release.
