### ISSUE TITLE
Language Issues

### ISSUE THREAD

**Issue by MillenniumAlpha** [picotorrent/picotorrent#760]
When I opened PicoTorrent instead of it being in English for some reason the language changed to Catalan, any ideas on how to fix it.
There's probably a button to change it but I don't understand Catalan at all.
![PicoTorrent_gxVy0J1Ya1](https://user-images.githubusercontent.com/44296791/69370568-1844a100-0c96-11ea-9d24-98a34308b7d1.png)

**Comment by Rakleed** [comment]
@MillenniumAlpha, to change the language to English, you should click on the top Veure - Preferències - General - Idioma - English (United States) and restart the app.

**Comment by vktr** [comment]
Hi @MillenniumAlpha, sorry for the late reply! Yeah, as @Rakleed mentioned, that's how you change the language. When I looked into this now I found a bug in how we use locales and languages when setting default language.

**Comment by MillenniumAlpha** [comment]
> 
> 
> @MillenniumAlpha, to change the language to English, you should click on the top Veure - Preferències - General - Idioma - English (United States) and restart the app.



> 
> 
> Hi @MillenniumAlpha, sorry for the late reply! Yeah, as @Rakleed mentioned, that's how you change the language. When I looked into this now I found a bug in how we use locales and languages when setting default language.

Thanks for the help!

**Comment by vktr** [comment]
I've fixed a few bugs in how we get the user language, so I think this issue is fixed. Please reopen if not, or file a new one!
