### ISSUE TITLE
Picotorrent can't remember download progress after restart

### ISSUE THREAD

**Issue by Tall-Lobster** [picotorrent/picotorrent#762]
Dear Picotorrent Developer,

I am facing an issue where picotorrent after restarting the computer and having run at startup where it forgots how far the download has gone through and ends up with 0% progress.

let me know if you already fixed this issue or not.

**Comment by Rakleed** [comment]
@Tall-Lobster you created a duplicate, because this problem is discussed in https://github.com/picotorrent/picotorrent/issues/407.

**Comment by vktr** [comment]
@Tall-Lobster Are you exiting PicoTorrent before restarting the computer? Or do you let Windows quit PicoTorrent?

**Comment by Tall-Lobster** [comment]
Dear @vktr, it was occuring in both restarting/quitting picotorrent. But so far with the new update it seems to have solved the problem, but I am also using picotorrent less. I will keep up updated about this issue.

**Comment by Tall-Lobster** [comment]
Dear @vktr , the error is still occuring even after the update to 0.18.0, but also this error occurs after one of the torrent files is updated to including the required files, and when you restart the applicaiton or restart the computer it goes to a view way before the latest download.
