### ISSUE TITLE
Pico torrent does not remember torrents that are not downloaded on restart/crash.

### ISSUE THREAD

**Issue by Theking1313** [picotorrent/picotorrent#764]
Whenever I add a bunch of torrent links that have not started downloading or a queued for download, they all disappear after a restart or crash. The torrent has to have add some percentage download for the Pico torrent to save the torrent files when you reopen the program. I've also on occasion had torrents that were downloading disappear from the torrent list. I'll also note that I use magnet links and not .torrent files.

I think the program needs to improve the background saving of torrent files and un-downloaded torrents in the program. If I add 5 magnet links to the program and then close it, it should remember the links I've added and not disappear.

**Comment by VideoPlayerCode** [comment]
I am not seeing this issue at all. I'm not saying it can't happen, but it doesn't happen to me. :S

**Comment by VideoPlayerCode** [comment]
I see the issue now. I went and grabbed an unpopular "magnet link" torrent. It was on "downloading metadata" when I exited PicoTorrent. Then when I started pico again, the torrent was forgotten by PicoTorrent.

**Comment by vktr** [comment]
Thanks for the report. I'll see if I can fix this for the next release.

**Comment by nonpcnpc** [comment]
yes, this is "old" issue. if you have no metadata before closing pt, you will lose the queued torrents. to prevent this, when the add dialogue popts up, wait for pt to fetch the metadata(it will shot list of files the torrent has) before clicking "ok".

**Comment by vktr** [comment]
Will be fixed in #787
