### ISSUE TITLE
Adding useful details to Overview tab

### ISSUE THREAD

**Issue by Bananaman** [picotorrent/picotorrent#772]
The Overview tab is a bit too bare-bones even for a "simplified client". These fields would be useful, and I think most are built into libtorrent already:

- **Comment**: This field is often used by tracker torrents for stuff like the web-link to the page that the torrent came from, for easily visiting the torrent page. (But to be useful, links in the comment need to be either clickable (most torrent clients do it that way), or a "Right-click and copy the comment text" action needs to exist.)
- **Size: 3.7 GB (2.3 GB selected)**: This kind of info is very useful. The ` (2.3 GB selected)` suffix would only show up if the person has selected less than 100% of all files (via "Do not download" priority on some files).
- **Privacy**: This may need to be named something newbie-friendly, but anyway it refers to the "Private" flag of Torrent files which indicate whether the file allows DHT peers or only per-tracker peers.
- **Last Activity**: Being able to see stats like "2 weeks ago" would be a helpful indicator to give up and delete a torrent.
- **Last Seen Complete**: How long ago you saw a 100% complete seeder (if ever).
- **Total Downloaded and Total Uploaded**: Currently there's only the "Ratio" column, but nothing saying how much data has actually been downloaded or uploaded. It's useful to quickly be able to see "Ah I have uploaded 300 GB, that's enough, I can stop seeding now".
- **Ratio**: Would be good to have it on the Overview tab too, like all other torrent clients, since it helps when gaining an at-a-glance overview of the torrent.

If you dislike showing all that useful data on the overview tab, there could be a Preferences option to "Show advanced overview information" for people who need it.

**Comment by Suncatcher** [comment]
Kudoz to that, I'd appreciate I can see the uploaded/downloaded stats of the torrent
