### ISSUE TITLE
The folder progress is always `-99`

### ISSUE THREAD

**Issue by Rakleed** [picotorrent/picotorrent#773]
The folder progress is always `-99`. Please fix this problem.

<details>
<summary>Screenshots</summary>

![2019-12-19_19-29-43](https://user-images.githubusercontent.com/19418601/71191910-5c789080-2298-11ea-8116-e8c1e53a4b40.png)

![2019-12-19_19-36-36](https://user-images.githubusercontent.com/19418601/71191914-5edaea80-2298-11ea-82df-9eb0730c4562.png)

![2019-12-19_19-45-06](https://user-images.githubusercontent.com/19418601/71191917-613d4480-2298-11ea-8ac3-1ead0f9485c7.png)

</details>

**Comment by vktr** [comment]
This is fixed in 26fe4a1890040292556fa644e1edd1ff26dd4540. The latest builds on AppVeyor contains this fix.

**Comment by Rakleed** [comment]
@vktr can you please give a link?

**Comment by vktr** [comment]
Sure - here's the x64 artifacts: https://ci.appveyor.com/project/picotorrent/picotorrent/builds/29476734/job/ycctoaj1be2x5qgk/artifacts
