### ISSUE TITLE
In other localizations, instead of valid names, variable names are displayed

### ISSUE THREAD

**Issue by Rakleed** [picotorrent/picotorrent#775]
In localizations, instead of valid names, variable names are displayed. This confuses the user and complicates the use of the program.

For example, in Russian localization:
<details>
<summary>Screenshots</summary>

![picotorrent-translation-1](https://user-images.githubusercontent.com/19418601/71265529-6dd4a200-2357-11ea-8815-14419308a811.png)
![picotorrent-translation-2](https://user-images.githubusercontent.com/19418601/71265539-72995600-2357-11ea-9135-2c1b91d62b27.png)
![picotorrent-translation-3](https://user-images.githubusercontent.com/19418601/71265543-762cdd00-2357-11ea-8c1a-6af8f1177a48.png)

</details>

The errors shown in the screenshots above are related to these commits: https://github.com/picotorrent/picotorrent/commit/1dd0048da82090575c5d3bc1547deb01a9b83b24#diff-c86d106827b3b3770e40c6af6bc88f6d, https://github.com/picotorrent/picotorrent/commit/d7d3c8e2734a5c09aea3835629bd97f917978f54#diff-c86d106827b3b3770e40c6af6bc88f6d, https://github.com/picotorrent/picotorrent/commit/a98d7e324dc99860f130d32c0c2f48ae70ef9e32#diff-c86d106827b3b3770e40c6af6bc88f6d, https://github.com/picotorrent/picotorrent/commit/f51a0651d25dbed304ebc80e30f7db346f45cda2#diff-c86d106827b3b3770e40c6af6bc88f6d, https://github.com/picotorrent/picotorrent/commit/6751084e37e97f846852c6874b0039fb164eddae#diff-c86d106827b3b3770e40c6af6bc88f6d.

This could have been avoided if you added new lines to all other localizations when updating English localization.

Most likely, I did not give a complete list of problems, and for other languages there will most likely be other errors, so I would like you to update all other localizations in accordance with English (that is, that in other localizations there would be the same variable names and the same number of lines as in English).

**Comment by nolddor** [comment]
English should be the fallback language in case the new introduced variables cannot be found on other localizations.

**Comment by vktr** [comment]
Hi! When a language is missing a translation key, the key is shown instead. This is by design to make it easier for anyone working on translations to know what key they need to add a translation for. Therefore, I'm probably not going to add English as the default fallback.

However - I'm working on a web tool to make it easier to manage translations.

**Comment by Rakleed** [comment]
@vktr are you doing something like Crowdin?

**Comment by vktr** [comment]
@Rakleed I've added Crowdin just now - https://crowdin.com/project/picotorrent. Also, English is now the fallback language.

**Comment by Rakleed** [comment]
@vktr can translators now only translate your app on Crowdin or will you also be accepting PR with language file changes on GitHub? And how will the process of adding new translations to the program from Crowdin be organized in general?

**Comment by vktr** [comment]
Translators can use either Crowdin or send regular pull requests on the JSON files - both ways are fine. I'm not 100% sure on Crowdin yet since the translator gets no attribution, all commits looks like they are from me.

What do you mean adding new translations - adding languages on Crowdin? Or adding them to PicoTorrent when building?

**Comment by Rakleed** [comment]
> What do you mean adding new translations - adding languages on Crowdin? Or adding them to PicoTorrent when building?

Second one.

**Comment by vktr** [comment]
Every translation file in the `lang/` folder will automatically be added as part of the build process - there's a new utility which builds the new translation database, which iterates through each translation file.

**Comment by vktr** [comment]
More specifically, here; https://github.com/picotorrent/picotorrent/blob/master/src/l10n/main.cpp
