### ISSUE TITLE
Drag and select multiple torrents with the mouse

### ISSUE THREAD

**Issue by Rakleed** [picotorrent/picotorrent#778]
Please add the ability to select multiple torrents by dragging and selecting with the mouse. Since it is now possible to select only using the keys on the keyboard Ctrl or Shift.

This is what I am talking about:
<details>
<summary>GIF</summary>

![drag-and-select](https://user-images.githubusercontent.com/19418601/71284893-e007af80-2374-11ea-9039-6a4b4caaafa3.gif)

</details>

**Comment by vktr** [comment]
I'll see if this could be added easy enough, but I'm not sure. The torrent list will select the items on mouse down (as it should) and I don't think a selection rectangle would work well in that kind of list (report style). The Control and Shift modifiers when clicking are standard Windows modifiers for doing exactly what you're describing.

**Comment by Rakleed** [comment]
@vktr I don’t know why I didn’t notice earlier that the function described by me is present. It’s just that when selecting, a translucent selection rectangle does not appear.

Then you can close my issue if it is difficult to implement a translucent selection rectangle (yes, I myself do not see this as a special need).

**Comment by Rakleed** [comment]
@vktr It looks like this function stopped working after switching to wxWidgets.
