### ISSUE TITLE
Allow different column sets in the torrent list view

### ISSUE THREAD

**Issue by vktr** [picotorrent/picotorrent#78]
The list view showing torrents should be able to handle configured column sets to allow users to switch between different views.

For example, the pre-specified column set `Pico` could show the columns *Name*, *Queue position*, *Progress* and *ETA*, and the set `Detailed` with the columns *Name*, *Queue position*, *Size*, *Status*, *Progress*, *ETA*, *DL*, *UL*.

The option to switch column sets would be in `View -> Column sets -> Pico/Detailed`.

**Comment by ismail** [comment]
Overall it would be also nice to be able to deselect some default columns (via right clicking to the column header for example).

**Comment by vktr** [comment]
Yes, that's a good suggestion which I believe has been mentioned elsewhere as well 😄
