### ISSUE TITLE
Bug when typing invalid disk paths

### ISSUE THREAD

**Issue by Bananaman** [picotorrent/picotorrent#783]
Try saving a torrent to `D:y\Downloads` which was my typo. It made picotorrent crash. And after restart, it showed "invalid disk path" as the torrent status. The path as seen inside PicoTorrent after that mistake ended up as `<the path to Google Chrome here>\D:y\Downloads` which is of course nonsense.

**Comment by vktr** [comment]
Thanks for reporting - I'll have a look.

**Comment by vktr** [comment]
I can somewhat reproduce the issue - I add a torrent with `C:y\temp` as the save path, and PicoTorrent doesn't crash however the torrent shows an error. If I then try to resume it, PicoTorrent will crash. Not ideal.

I'll add some sanity checking in the add torrent dialog.

**Comment by vktr** [comment]
Hey @Bananaman! I think the latest version has solved this issue. Closing this for now but if you run into the same issue again, feel free to reopen or create a new issue.
