### ISSUE TITLE
There are no variables in the localization file for DL/UL speed and remaining time

### ISSUE THREAD

**Issue by Rakleed** [picotorrent/picotorrent#784]
There are no variables in the [localization file](https://github.com/picotorrent/picotorrent/blob/master/lang/1033.json) for DL/UL speed and the remaining time (hour, minute, second, etc.).
<details>
<summary>Screenshots</summary>

![2019-12-22_15-25-05 (2)](https://user-images.githubusercontent.com/19418601/71321960-76051c80-24d2-11ea-92e5-a9ad89690dc1.png)
![2019-12-22_15-43-13](https://user-images.githubusercontent.com/19418601/71321961-78677680-24d2-11ea-86ad-6464c648cb53.png)

</details>

Because of this, it is impossible to completely localize the program to other languages. Please add variables to localize DL/UL speed and the remaining time.

**Comment by vktr** [comment]
Hi! We use `StrFormatByteSize64` from the Win32 API's to format the file size (and by extension the speeds). For download/upload rates we just add the `/s` suffix, which is what we can localize. I'll add a feature request for this.
