### ISSUE TITLE
Extend the configuration dialog

### ISSUE THREAD

**Issue by vktr** [picotorrent/picotorrent#79]
The configuration dialog needs some work to make it easier to use and also to provide the user with more settings.

Extending the configuration dialog should be done in two parts, one to separate configuration views into different pages which can be loaded from their own `DIALOGEX` resource identifiers, and another one to add more configuration options to the dialog.

The following new config settings should be exposed in the dialog,
- Encryption settings
- Proxy settings
- Anonymous mode
- Bind to specific IP address
- A button to test the connectivity of the network interface and port
- An option to move finished torrents to a specific path
- An option to set a custom extension on incomplete files (i.e `.incomplete`)

**Comment by enr00ted** [comment]
+1 To the proxy settings (HTTP proxy especially) !

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/issues/353

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/pull/355

**Comment by svnpenn** [comment]
https://github.com/picotorrent/picotorrent/issues/513
