### ISSUE TITLE
Double Click Completed Torrent To Open Containing Folder

### ISSUE THREAD

**Issue by anirudhgiri** [picotorrent/picotorrent#790]
Feature Request!
Double clicking a completed torrent should open it's containing folder instead of doing nothing. 
This functionality can be found in various other mainstream bittorrent clients and I believe it's addition is essential for a sleek experience as double clicking your torrent once it's finished downloading is the intuitive thing to do,

**Comment by Rakleed** [comment]
@anirudhgiri it seems to be implemented in version 0.16. Are you sure you are using the [latest version 0.17](https://github.com/picotorrent/picotorrent/releases/latest)? You can also try installing the [latest build](https://ci.appveyor.com/project/picotorrent/picotorrent/builds/29710681/job/3j5o7hiwdiqvm83i/artifacts) from AppVeyor.

**Comment by anirudhgiri** [comment]
@Rakleed I was indeed using the latest version but it seems the problem was at my end. A reinstall of the program seems to have fixed the issue and the double click to open the containing folder functionality works.

Thank you for the help and I apologize for any time wasted.
