### ISSUE TITLE
Won't Force Recheck loaded torrent with complete data on disk

### ISSUE THREAD

**Issue by kilves76** [picotorrent/picotorrent#791]
Testing PT for archive seeding but it won't check the data, after Recheck status stays Paused, a little disk activity but not much (~15 MB in 15 mins).
Is this because it tries to open the files with write rights and fails?

All files in my archive are with Read&Execute rights only, to avoid any unwanted corruption (in case of real corruption i'll temporarily change the rights manually, this is so rare it's feasible).

Tried the location both above the folder name and inside it, same result, so it shouldn't be a top folder location issue.

**Comment by kilves76** [comment]
Copied the torrent to another disk with RW attributes, still nothing happening. Tried with both T:\ and T:\Torrentname locations. The torrent size is over 1 TB, could this have something to do with the issue.

**Comment by kilves76** [comment]
I lost track which version this is, maybe About should tell the exact build number?
Windows properties says 0.17.0(1911a05).
So i tested with a smaller 4 GB torrent and it still won't recheck anything. Bug or what?

**Comment by kilves76** [comment]
Detailed, open torrent file with ctrl-o, select it's location as T:\ , torrent is a normal torrent with its own folder inside which are many data files with path T:\Thistorrent , click  [ ] Start torrent box off, click Ok.
Right click on torrent, select Force Recheck. Nothing happens, torrent stays Paused with Progress at 0%. There is some small disk activity by PicoTorrent.exe but nothing much, 160 kb after clicking Ok on the torrent selection.

**Comment by vktr** [comment]
Hi! I'll see if I can reproduce this.

**Comment by kilves76** [comment]
The issue is still there in 0.18.0 , add torrent downloaded with another client, it won't recheck it.
Made sure it's not a permissions issue by Everyone having Full Control of the torrent folder tree.

**Comment by vktr** [comment]
Hey! Sorry for the late answer. This issue should be fixed by the linked pull request and included in the next release.

**Comment by kilves76** [comment]
Great!
