### ISSUE TITLE
Set focus to textarea after opened "Add magnet link(s)" window

### ISSUE THREAD

**Issue by matchman72** [picotorrent/picotorrent#798]
It would be nice if focus is set to the textarea when we open the window, so we can paste the magnetic link into the box immediately. Now we require 2 tab presses or 1 mouse click to focus the textarea.

And additionally, some other torrent clients would read clipboard content, and paste clipboard content into the textarea when magent:? keyword found. It would be nice to be implemented too.

Thanks.

**Comment by vktr** [comment]
Hi! These are good suggestions!
