### ISSUE TITLE
Missing 'pause' option when a torrent is in 'queued' state

### ISSUE THREAD

**Issue by thec0mpler** [picotorrent/picotorrent#799]
This is my first issue.

When a torrent has the state 'queued' there is no 'pause' option in the context menu (which will set the state to 'completed' if the torrent is finished). When a torrent is in 'seeding' state, then there is a 'pause' option in the context menu.

![Queued with resume option](https://user-images.githubusercontent.com/4445369/72096052-c1645b00-3319-11ea-96af-865a1727896d.png)
![Seeding without pause option](https://user-images.githubusercontent.com/4445369/72096053-c1645b00-3319-11ea-9456-6834166413e9.png)

So if I want to pause a torrent, which is in 'queued' state', I have to use the context menu twice.

Could the 'pause' option added to the context menu when a torrent is in 'queued' state?

**Comment by vktr** [comment]
Hi! Thanks for the report! You are right, we should have a *Pause* option for queued torrents. It's an oversight from my end.
