### ISSUE TITLE
Import from µTorrent

### ISSUE THREAD

**Issue by arjendejong12** [picotorrent/picotorrent#800]
Hi, is there a way to import my current torrents in µTorrent into PicoTorrent?

**Comment by vktr** [comment]
We had that way back in 0.13. Unfortunately it got removed, however you might be able to import your torrents by running the 0.13 portable version, importing your torrents from µTorrent, and then running the portable version of 0.18 from the same directory. In theory, this would work.

Let me know if you decide to try it!

**Comment by arjendejong12** [comment]
The steps you gave me work! Any reason why it was removed?

**Comment by vktr** [comment]
Great! I initially pulled it since the plugin API went deprecated when we switched to wxWidgets. Now we have a JS API in the works and I'm thinking this should fit well in that when it's ready :)

**Comment by vktr** [comment]
Closing this since it seems resolved.
