### ISSUE TITLE
Trackers tab controls confused

### ISSUE THREAD

**Issue by DLslime** [picotorrent/picotorrent#810]
Version: v0.18.0

When I try to remove trackers in Trackers tab, it often remove the wrong track which not I selected. Copy tracker's URL and Force reannounce also have the same problem, so I have to copy and paste the tracker's URL to check if I'm controlling the correct tracker.

**Comment by vktr** [comment]
Hi, thanks for the report! Is there a consistent behavior in this or is it mostly random?

**Comment by DLslime** [comment]
I tested it again. It seems mostly random but I noticed trackers' reannouncement would change their queue and Tracker tab's display didn't update in time.
