### ISSUE TITLE
memory usage(working set) growing way too much

### ISSUE THREAD

**Issue by joshuatee** [picotorrent/picotorrent#811]
...and often way too fast. this is really visible when downloading bigger torrents(5-10GB+) and at relatively higher download speed(100 Mbits or so)

on an ancient 4GB machine I use to test stuff PT's working set grows to roughly about 3GB literally in minutes, lets say ~5 at which point the machine becomes totally unresponsible often for quite some time, 5 minutes or more, maybe up to 20. I think, depending on the torrent's size

picotorrent v0.18 amd64
windows 10 v1909

sadly I'm not sure if I had the issue pre 0.18 or it was introduced with it. I *think* it started with 0.17 or 0.18

offtopic, thanx for making a clean, lightweight torrent client
cheers

**Comment by vktr** [comment]
Hi! Thanks for the report. I know there are some other issues mentioning this as well, I'll def. have a look to see if we can fix this easily.

**Comment by armpogart** [comment]
Same as #734, I can confirm that the issue is introduced in 0.17. I have checked the older versions and they don't have the same issue.

**Comment by vktr** [comment]
@armpogart thanks for the additional data point!
