### ISSUE TITLE
Feature request: Add a pieces visualiser...

### ISSUE THREAD

**Issue by TechAdvancedCyborg** [picotorrent/picotorrent#820]
# Can you guys add a pieces visualiser like Flud or QBittorrent?

# Examples
![Flud](https://lh3.ggpht.com/lhSsbaZP4bpNJqcUypHGDP9O6vl5CTuwcA1WPubneLD9EtsEz11P_LIujcQTD9VgDA=h310)
![QBittorrent](https://user-images.githubusercontent.com/2133205/40149202-6177db7c-5940-11e8-84d8-c32d582cae33.png)

**Comment by vktr** [comment]
Hi! Yes, it it on the internal roadmap 😃 We’ll see when it lands exactly, but thanks for bringing it up!

**Comment by asvc** [comment]
Out of sheer curiosity, what is the purpose of this visualisation apart from an aesthetic pleasure?

In my very limited understanding it shows which parts of the torrent are being downloaded and optionally colours sections that have missing chunks.

**Comment by TechAdvancedCyborg** [comment]
Well it could be interesting to know what parts are downloaded, especially if at some points you make an option to download pieces at the end and at the start, you can track progress and see when you can start watching(example) a certain video file.

**Comment by TechAdvancedCyborg** [comment]
Btw @vktr when is the next release coming out?

**Comment by vktr** [comment]
Hey @TechAdvancedCyborg - I'm currently moving back to wxWidgets for the UI framework so as soon as that is done I'll make a feature release out of that, and then I can move on with requested features again 😃 Shouldn't be more than a few weeks.

**Comment by TechAdvancedCyborg** [comment]
Thanks! Good luck!

**Comment by TechAdvancedCyborg** [comment]
#996 closes this issue
