### ISSUE TITLE
PicoTorrent is getting under the Windows's taskbar

### ISSUE THREAD

**Issue by verlanmar** [picotorrent/picotorrent#821]
OS: Windows 10 | PicoTorrent v0.18

Hello,
When Windows's taskbar is located at the top of the desktop, as opposed to its default bottom position, then PicoTorrent is getting under the Windows's taskbar.

Screenshot attached below:
![screenshot](https://user-images.githubusercontent.com/38294552/75239846-0eb66200-57cc-11ea-9967-f6916a1469f2.png)

**Comment by vktr** [comment]
Hi! That is odd. You should be able to hover on the PicoTorrent icon in the taskbar to make it show the preview window. Right click the preview window and click *Move*, which should put your cursor where you can click and move the PicoTorrent window.

**Comment by StoyanDimitrov** [comment]
The issue is not related to the application.
