### ISSUE TITLE
Removing Last torrent from list crash picotorrent (simply close)

### ISSUE THREAD

**Issue by gruber123** [picotorrent/picotorrent#822]
Removing Last torrent from list crash picotorrent (simply close);
Next time launch it again the so-called removed torrent start download again;
and same circle of cases until it should work as expected

**Comment by vktr** [comment]
Hi! I can't reproduce the issue. Can you tell me what steps you're taking?

**Comment by vktr** [comment]
Hi again. This might be the same issue as #795 and if so, it has been fixed but not released. Can you try the latest installer from AppVeyor?

https://ci.appveyor.com/project/picotorrent/picotorrent/build/job/ee9n1kxhuxbumg0i/artifacts

**Comment by gruber123** [comment]
Hi Viktor,

I've tried your link from appveyor - it shows as 0.18 version so as already installed on my computer,
the link I've used https://ci.appveyor.com/api/buildjobs/ee9n1kxhuxbumg0i/artifacts/build-x64%2FRelease%2Fpackages%2FPicoTorrent-0.18.0-x64.exe

And I see same thing:

1st time I put 1 torrent - download it, remove torrent only, application doesn't exit;
2nd time I put 2 torrents - download them, remove them together only torrent, oops application exits; - Maybe I wrong but I see when doing this operation I've seen one of torrents on removing shows as 0 Kb and thus application exits.

Another thing: I don't know if this by design but I've think that add torrent can be also from url, and from browser not only from local torrent or magnet.
Lastly, can you make remember last used directory (1, or some amount of previous used) - It's will be better for seeking directories.

Thanks,

Igor

________________________________

**Comment by vktr** [comment]
@gruber123 you might need to uninstall your local version before installing the one from AppVeyor, or try the zip file.

The add torrent dialog will remember save path history in the next version!
