### ISSUE TITLE
A couple of missing lines in the greek translation

### ISSUE THREAD

**Issue by pitsi** [picotorrent/picotorrent#824]
As seen on the screenshots below, there are some lines of text that are missing from the greek translation of picotorrent and they show up as... weird text.
I offer to translate them, if you show me the right source, because I checked lang/1032.json and everything seems fine in there
  
![1](https://user-images.githubusercontent.com/5880037/76198425-b5e8bf80-61f6-11ea-9c05-29c8de40b1bc.jpg)
![2](https://user-images.githubusercontent.com/5880037/76198428-b6815600-61f6-11ea-8b2e-5d5f4099e639.jpg)
![3](https://user-images.githubusercontent.com/5880037/76198430-b719ec80-61f6-11ea-84a3-fccf7dc59ad3.jpg)

Tested on the x64 version of picotorrent, on w10 1909 and w7, both greek and both x64.
Thank you in advance.

**Comment by thec0mpler** [comment]
Thank you for offering help! You are right that the language file is 'fine'. There are only some lines (key/value pairs) missing at the end of the file. The English file has 254 lines vs 239 lines in the Greek version.

If you could translate and add the following lines to the file, that would be awesome! (do not forget to add a comma at the end of the 'encrypt_config_file' line)

```
"amp_details_panel": "&Details panel",
"s_of_s": "%1 (of %2)",
"downloaded_size": "Downloaded",
"amp_status_bar": "&Status bar",
"amp_filter": "&Filter",
"amp_none": "&None",
"filter_downloading_active": "Downloading (active)",
"filter_uploading_active": "Uploading (active)",
"size_remaining": "Size (remaining)",
"pause_on_low_disk_space": "Pause when disk space is low",
"pause_on_low_disk_space_alert": "Torrent paused (low disk space)",
"enable_geoip": "Enable GeoIP lookups",
"enable_automatic_crash_reporting": "Enable automatic crash reporting",
"network_adapter": "Network adapter",
"kb_s": "KB/s"
```

If you have any questions, let me know ;)

**Comment by pitsi** [comment]
Although those "&" in front of some words confuse me, here is the translation. Feel free to add them yourself
```
"amp_details_panel": "Λεπτομέρειες",
"s_of_s": "%1 (από %2)",
"downloaded_size": "Μέγεθος ληφθέντων",
"amp_status_bar": "Μπάρα κατάστασης",
"amp_filter": "Φίλτρο",
"amp_none": "Κανένα",
"filter_downloading_active": "Λήψη (ενεργά)",
"filter_uploading_active": "Αποστολή (ενεργά)",
"size_remaining": "Μέγεθος (που απομένει)",
"pause_on_low_disk_space": "Παύση όταν υπάρχει λίγος χώρος στο δίσκο",
"pause_on_low_disk_space_alert": "Torrent σε παύση (λίγος χώρος στο δίσκο)",
"enable_geoip": "Ενεργοποίηση αναζητήσεων GeoIP",
"enable_automatic_crash_reporting": "Ενεργοποίηση αυτόματης αναφοράς σφαλμάτων",
"network_adapter": "Προσαρμογέας δικτύου",
"kb_s": "KB/s"

```

I need some help or confirmation on these
- the translation on "amp_details_panel" translates to "details" only (one word instead of two), there is no translation for "panel" because there is no equivalent work in greek with similar meaning. The closest one I can think is "πίνακας", which translates to "chart", but I do not think it is suitable. Then there is "πλαίσιο", which translates to frame.
- for the ones on "filter_downloading_active" and "filter_uploading_active" I used the words "Λήψη" and "Αποστολή" respectively because I think they are better than "Μεταφόρτωση" and "Αναφόρτωση", which are the nouns for the verbs used on lines 169 and 170. They make more sense in greek and they are more commonly used. To be honest, I have never heard that translation for "upload"...
- (continuation of the above) on both those translations, singular was used. "Ληψη" translates to "Download" and "Αποστολή" translates to "Upload". If you need them in plural, please tell me to change them.
- the translation on "size_remaining" translates to "size (**that** remains)". I hope that it is ok.
- the one on "enable_geoip" translates to "enable geoip **lookup**"

**Comment by thec0mpler** [comment]
Thanks for the translations! I have added them to the file.

I think it is best if @vktr answers your questions, because it is his project. I also have the question about the `&` character in front of some translations.

**Comment by vktr** [comment]
@pitsi @thec0mpler The ampersand (`&`) prefix is used for menus to show the legend (underline) when pressing Alt. So `&File` would show as `File` with the `F` underlined.

**Comment by pitsi** [comment]
Thank you for accepting my work :)
For uniformity reasons, i.e. using the same noun or verb in all iterations of "download" and "upload", I think that the lines 169 and 170 should be changed to
```
"downloaded": "Λήφθηκαν",
"uploaded": "Απεστάλησαν",
```
As I have said above, the translation for "downloaded" is good enough. Actually, it is just acceptable nowadays, because 10-15 years ago some idiots wanted to translate every tech word to greek, so they just made a combo-word from the translations of "down" and "load" and this... frankenword came up. I do not know if it mentioned in the dictionary today, but this is how things were.
And the same applies to "uploaded", but its frankenword translation is simply unacceptable, and I doubt it exists in the dictionary.
In my translation, the one for "downloaded" is the greek work for "received" and the one for "uploaded" is the greek word for "sent". Simple and similar words that make sense and not some invented words.

Just to give you an example of what garbage this idea has caused, the greek word for pixel (made from "picture + element") is the translation of picture emelemt... combined in one word (εικονοστοιχειο = εικονα + στοχειο = picture + element). And I do not recall the one for "bit", which is the ultimate monstrosity.
Thank you for listening :)
