### ISSUE TITLE
Crashes when selecting multiple torrents and right click and remove

### ISSUE THREAD

**Issue by andreborud** [picotorrent/picotorrent#828]
Picotorrent crashes every time I select multiple torrent, right click on one and select remove torrent. After wards it doesn't recover what has been downloaded and not. And Restarts download everything from scratch, even if it was fully downloaded. 

Happens on windows 10 with all the latest updates and the latest version of Pico.

**Comment by vktr** [comment]
Thanks for the report! Can you reliably reproduce the issue? If so, would you mind comparing the save path of the torrent (per the details tab) before and after it restarts downloading from scratch. It might be that it loses the save path and then downloads it to another path.

**Comment by andreborud** [comment]
Yes, I can reproduce it all the time. This issue has been here in the last three versions, so its not something new introduced in the latest one. 

The save path does not change after it restarts. 

I had two things downloading and when both where at 100% I removed them like described above. No crash. 

Then when having 6 things downloading, only two of them where at 100%. In the screenshot it was the first and the fifth item. I removed those two by selecting both and using right click - remove. And it crashed. Restarting the app the fifth item recovered and the first one started downloading again. The files are still in the download folder and has not been removed. 

If it helps the checking which happens at startup was only visibly started at the fifth and the sixth item. Never saw it on the first which just started downloading again.

![PicoTorrent 2020-03-17 16_47_39](https://user-images.githubusercontent.com/5594437/76874364-6138ea80-686f-11ea-8bce-4f28acc38c2f.png)

**Comment by vktr** [comment]
That helps a lot! If I understand correctly - the items you are removing (which causes a crash) will be added back to PicoTorrent when you restart? And begin downloading?

I'm speculating but it seems PicoTorrent crashes after it has removed the first item but before it has removed the second. It just removes the data and crashes before it can remove the torrent from the session. So when you start it the next time, the first item has no data at all and restarts downloading, and the second item will recheck and find all its data intact.

**Comment by andreborud** [comment]
>  the items you are removing (which causes a crash) will be added back to PicoTorrent when you restart?
Hard to say if they are removed or not as they are still there after the crash, I never seem them disappear before the crash. 

> And begin downloading?
Yes. I never select remove torrent and files, only remove torrent. 

As it doesn't seem to happen when all files are full downloaded, or when only selecting one, my first thought is that some loop crashes when some of the files are still downloading, even though they aren't selected?

**Comment by vktr** [comment]
I'll have a look tonight and see if I can reproduce it. Thanks for the clarifications!

**Comment by andreborud** [comment]
Just tried to remove with all six downloads at 100% and no problem. So it only seems to happen when at least one torrent is still downloading.

**Comment by vktr** [comment]
I just remembered - you may be running into #795 (which has been fixed but not released). Can you try the latest binaries from AppVeyor and see if your problem still exists?

https://ci.appveyor.com/project/picotorrent/picotorrent/build/job/ee9n1kxhuxbumg0i/artifacts

**Comment by andreborud** [comment]
Sorry for the delay. I just managed to test the new version 0.18.0 and it still happens for me there.

**Comment by vktr** [comment]
Thanks @andreborud I'll do some more digging and see if I can reproduce it!

**Comment by elexor** [comment]
Happens for me 0.18.0 windows 10.

**Comment by vktr** [comment]
Hi @elexor, sorry you're seeing the same issue. I'm in the middle of a big push for the next release and I'm quite certain it's fixed there.

**Comment by mmocz** [comment]
FYI Im having the exactly same issue on 0.18.0.
