### ISSUE TITLE
Documentation cannot be reached via Web

### ISSUE THREAD

**Issue by NikoGrano** [picotorrent/picotorrent#829]
Documentation url of http://docs.picotorrent.org/ is not valid due CNAME Cross-User Policy on Cloudflare.

![image](https://user-images.githubusercontent.com/4658966/76865016-bb837c80-686a-11ea-8d1b-a5f35c1acf77.png)

**Comment by vktr** [comment]
Hi! Thanks for the report, I'm aware but I just haven't had the time. I'll keep this issue to track progress though.

**Comment by vktr** [comment]
Should be available now (but out of date)
