### ISSUE TITLE
Add magnet dialog does not receive cursor focus upon load

### ISSUE THREAD

**Issue by vurghus-minar** [picotorrent/picotorrent#835]
Running latest 0.18 portable binaries on Windows 10.

### Steps to reproduce:
1. Open "Add magnet link(s)" dialog.
2. Using keyboard, cursor does not focus on textarea unless tabbed twice.

### Expected:
Cursor should focus on "Add magnet link(s)" dialog textarea upon load to allow keyboard paste (CTRL+V) as was the case with the previous versions.

Unsure whether this is a feature or a bug?

**Comment by vktr** [comment]
Hi! Thanks for the report! I'll label it as a feature and remember to implement it for the next version.
