### ISSUE TITLE
Download page header and links are not matching

### ISSUE THREAD

**Issue by vatonbero** [picotorrent/picotorrent#837]
Hi there,

I went to downloads page to obtain latest picotorrent and i have noticed that header states v0.15 and yet the download links are for 0.18.

Image:
![Screenshot from 2020-05-03 01-44-02](https://user-images.githubusercontent.com/59034981/80894942-191b3d80-8ce0-11ea-895c-5ca22372b243.png)

**Comment by vktr** [comment]
Hi! Thanks for reporting! I think we already have an issue reported on that, but thanks for reminding me 😃 I'll get that sorted out.

**Comment by Rakleed** [comment]
Yes, I already created such an issue - https://github.com/picotorrent/picotorrent/issues/755

**Comment by vktr** [comment]
Knew this felt familiar 😃 Closing this and keeping progress in #755. Thanks @Rakleed.
