### ISSUE TITLE
Integrate libcurl to allow HTTP(s) file downloads

### ISSUE THREAD

**Issue by asvc** [picotorrent/picotorrent#839]
Would you consider integrating libCurl/[cpr](https://whoshuu.github.io/cpr/) to allow users download via HTTP(s) with resume support?

**Comment by vktr** [comment]
You mean regular HTTP(s) downloads not related to BitTorrent? If so, then no, there is no such plans, sorry.

**Comment by asvc** [comment]
Totally understandable. Thank you for the reply.
