### ISSUE TITLE
New language - slovenian

### ISSUE THREAD

**Issue by matejbolko** [picotorrent/picotorrent#840]
I like this program so i decided to participate. I took english file and translated it to slovenian language.
here is the file: https://www.dropbox.com/s/wx673kptseggcnx/1060.json?dl=0 
What are the steps to add this file/language to official distribution and all new releases?

**Comment by vktr** [comment]
Hi! If you fork this repository, then add the JSON file in the `lang` folder as well as add a line in the `src/picotorrent/resources.rc` file for your language, it will be added to all new releases 😃 I think you can do all this from the GitHub web interface but I'm not sure. Let me know if you need assistance!

**Comment by vktr** [comment]
Hi @matejbolko! We've added Crowdin to make it easier for translators to work with the files :) Head over to https://crowdin.com/project/picotorrent if you're interested!
