### ISSUE TITLE
Implement anonymous mode like in qBittorrent

### ISSUE THREAD

**Issue by Dyras** [picotorrent/picotorrent#842]
Greetings! qBittorrent has an option to enable an anonymous mode that hides some info about the client, to prevent fingerprinting. I think this could be something really important for PicoTorrent, seeing as it currently has modest user shares.

https://github.com/qbittorrent/qBittorrent/wiki/Anonymous-Mode

> The peer-ID will no longer include the client's fingerprint
> The user-agent will be reset to an empty string
> Other identifying information will not be exposed to the public directly, such as IP, listening port, etc.

**Comment by vktr** [comment]
We had that back in the day, I can't remember why it was removed. I'll add it as a feature.
