### ISSUE TITLE
Expose all libtorrent settings

### ISSUE THREAD

**Issue by kilves76** [picotorrent/picotorrent#844]
Could it be possible to expose all libtorrent settings? If nowhere else then in the database? There's a lot an advanced user might want to change. If there's something PT absolutely needs to function these could be overrided from another table; existence of that table would be enough documentation.

And a default settings table so it'll be easy to return to PT install default settings if something's not right. Maybe an UI button to reset (if someone messed around the db maybe more messing around is not what's needed).

**Comment by vktr** [comment]
There's been requests for this before - and while I like the idea it also makes it extremely easy to break the client in unexpected ways 😄 As you said we definitely need a Reset to defaults button somewhere for this. I'll see if I can make something happen in a future version.

**Comment by vktr** [comment]
I'm closing this in favor of #667 which is the same issue reported.
