### ISSUE TITLE
Ratio doesn't update for imported torrents

### ISSUE THREAD

**Issue by kilves76** [picotorrent/picotorrent#847]
Already downloaded torrents imported to PT don't update their ratio when seeding. Is there some trouble increasing ratio stats if actually downloaded bytes is zero? Could it be solved by setting bytes downloaded to torrent size when importing then. Anything but a permanent Ratio 0.000 which is completely useless and should make any responsible torrenter cry.

And what does PT report to tracker in cases like these? Private trackers will ban PT if stats are not proper and truthful.

This has been posted already [#626](https://github.com/picotorrent/picotorrent/issues/626) but withdrawn by user. I'd consider it important.

**Comment by vktr** [comment]
Hi @kilves76! I'll see what we do for calculating the ratio in the UI.

Reporting stats to trackers is done by libtorrent, and I agree it is important to do it proper and truthful, which libtorrent does. So no worries there :)

**Comment by vktr** [comment]
Hi again! After thinking about this for a while, here's how it works; PicoTorrent will correctly display download/upload ratio for torrents it has transferred data for. If you download torrents in another application and then add the same torrents in PicoTorrent with the same save path, we still have no way of knowing how much data was downloaded/uploaded in the previous application.

As for reporting stats - PicoTorrent will report the correct stats as seen by PicoTorrent - i.e if you download 1GB in another application, then add the torrents to PicoTorrent and download 5MB, PicoTorrent will report 5MB. As it should be. The first 1GB would be reported by the previous application.

While we might add some way of adjusting the ratio for imported torrents in the future, it is currently not on the roadmap, sorry. I'm closing this for now, but will either open a new issue or reopen this if we revisit this.

**Comment by kilves76** [comment]
>  If you download torrents in another application and then add the same torrents in PicoTorrent with the same save path, we still have no way of knowing how much data was downloaded/uploaded in the previous application.

I think we have a miscommunication here. I'm not asking for setting stats to whatever they were in some other app, that's pretty much impossible since that data is not exported in a .torrent file.

What I am asking is that the Ratio update properly - when seeded - for imported torrents just as well as for any other torrents. As they currently stay at zero, and that is very uninformative to say the least. It's a very important measure and to have Ratio stay at 0 no matter how much a torrent is seeded should be considered a serious bug.

I'm currently testing PT 0.24 with 3600 torrents and the Ratio is 0 for all of them. I'm seeding all the time but don't know what and don't know where. It's nothing short of absolutely terrible. Delete torrents nobody wants? Oh sure I'll just select all with Ratio 0... 🥇

**Comment by vktr** [comment]
Yes, seems like a miscommunication 😄 Sorry.

I'm just walking through the scenario here. Lets say you add a torrent you have already downloaded - it checks the files and all is good. Currently, the ratio is calculated by dividing uploaded bytes with downloaded bytes. In case of no downloaded bytes, we set the ratio to 0. But perhaps we should to things differently.

If downloaded bytes is 0, and uploaded bytes is the same as torrent size - then the ratio should be 1? If downloaded bytes is half of torrent size, and uploaded size is same as torrent size, ratio is 0.5? Then, if downloaded bytes is same as torrent size, and uploaded bytes is same as torrent size, what is the ratio then? 1? Or 0?

**Comment by kilves76** [comment]
It should go right if downloaded bytes is initialized to torrent size, and uploaded bytes counter as ratio against this? 
Ratio starts at 0 and when uploaded bytes=torrent size then ratio shows 1.000, and onwards. 
Or you could make a special case fix for downloaded=0, see below.

Utorrent does this so that if downloaded bytes = 0, then it calculates ratio according to torrent size.
But if there was some small file missing, let's say README.TXT of 1000 bytes, which was then downloaded after initial recheck, then it does the actual calculation, and this is terrible:

With an 8 million bytes torrent, it will then report ratio as 8,000 when torrent has been seeded its own size (real ratio 1.000). Please do not do it like this! 
For Utorrent there's a workaround fix by editing resume.dat and setting downloaded=0 for the torrent, then ratio will be calculated properly.

**Comment by thec0mpler** [comment]
`ratio = uploaded bytes / torrent size` could also be an option?

**Comment by vktr** [comment]
> `ratio = uploaded bytes / torrent size` could also be an option?

Yes, I also thought about this. Maybe we could have one column for each data point - i.e one for *Transfer ratio* which is `uploaded bytes / downloaded bytes`, and then one for *Seed ratio* which is what @thec0mpler mentions, `uploaded bytes / torrent size`.

Thoughts?

**Comment by kilves76** [comment]
Better not call the Transfer Ratio even "ratio", sooner or later someone takes a screenshot of that as Ratio Proof (after getting it sky high with some creative partial redownloading) and then it's all bad rap for PT from there. Relative Transfer Stats or something. Rate? Quota? Ratio is just such a loaded word at private trackers.
I'm all thumbs up for realizing Seed Ratio urgently.

**Comment by thec0mpler** [comment]
Is the *Transfer ratio* interesting? If not, you could drop it and only keep *Ratio* for `uploaded bytes / torrent size`. If the transfer ratio is interesting, I would call it just that if @kilves76 agrees.

Personally I think that transfer ratio is not interesting and using two different ratio's can be confusing.

**Comment by kilves76** [comment]
Really please if just possible only have one "ratio" in the GUI, and that is the seed ratio.
Call the transfer ratio just UpDown, or just about anything else, but not "ratio". If anybody is even interested in it.

I don't think anybody wants to see the worst case scenario of someone getting creative with TR and then PT gets a bad reputation as the client that shows "fake ratios". This is all about the human dimension and how ugly it can get.

Remember Utorrent and the cryptominer? People still refer to it. It was 5 years ago.

**Comment by vktr** [comment]
That makes sense - I'm liking the `uploaded bytes / torrent size` more than the current one. It's an easy fix so I'll plan it for the 1.0 milestone if no one objects 😄
