### ISSUE TITLE
Small quality of life improvements

### ISSUE THREAD

**Issue by vinajuliette** [picotorrent/picotorrent#852]
- Clicking magnet links from Chrome (any version) does not open PicoTorrent
- "Open File" and "Open Magnet Link(s)" under the File menu should have control key bindings e.g. Control-O and Control-U (U for URL as the mnemonic)
- Opening the magnet link popup should focus the text box first, not the OK button

**Comment by vktr** [comment]
Hey @vinajuliette! Thanks for the report! We're getting close to the next release but these are good suggestions, and some are already fixed, so I will make sure to fix the rest of them as well.
