### ISSUE TITLE
UI stutters every second

### ISSUE THREAD

**Issue by szmarczak** [picotorrent/picotorrent#856]
The list looks like:

![image](https://user-images.githubusercontent.com/36894700/91300999-7f9efc80-e7a4-11ea-9879-ffaa3a3fe92e.png)

when I'm moving the window it stutters every second. The program doesn't feel responsive when opening a context menu. I'm on Windows 10 x64bit 2004.

**Comment by vktr** [comment]
Hey @szmarczak! Thanks for the report. I'll definitely try to reproduce this in the upcoming version.

**Comment by szmarczak** [comment]
Thanks for a very quick response! I'm running PicoTorrent v0.18. Here you can see exactly what happens: https://www.youtube.com/watch?v=HKPR-E2Ih8w

**Comment by vktr** [comment]
Awesome, thanks for the video! If you can, would you mind trying the latest binaries at https://ci.appveyor.com/project/picotorrent/picotorrent/build/job/22ovf5t3cdcufwbl/artifacts? The zip file has a portable version which you can use. Perhaps just add the torrents with a different save path to see if the update issue still occurs.

**Comment by szmarczak** [comment]
Yep, the issue is resolved there! Many thanks!

**Comment by szmarczak** [comment]
Also I want to report that you cannot sort by Status anymore there. Otherwise everything is great.

**Comment by vktr** [comment]
Great! Thanks for the quick responses :D
