### ISSUE TITLE
picoTorrent crashes more than before

### ISSUE THREAD

**Issue by phalox** [picotorrent/picotorrent#867]
Hi there!

I've just updated to the most recent version, but picotorrent crashes more than it did before (I used to have crashes deleting multiple torrents at once). Now it crashes when I added a magnet link (in the preview window) and also when I stopped seeding.

I sent you the crash report of the former.

Good luck and thanks for your work!

**Comment by phalox** [comment]
I also sent you the 2nd one. Even when I just click on the seeding torrent it crashes. Makes it pretty tough to use right now :-(

**Comment by vktr** [comment]
Hi @phalox! The crash report server is down at the moment 😅 Can you email me the crash report at viktor@viktorelofsson.se?

It's located at `C:\Users\<you>\AppData\Local\PicoTorrent\Crashpad\db\reports` IIRC. It's a `.dmp` file.

**Comment by birkoffe** [comment]
Send my dumps on selecting one of torrent.

**Comment by vktr** [comment]
@birkoffe I've identified the issue from the reports you sent, it should already be fixed in the latest `master` builds. I dunno why it didn't make the v0.19 release but I'm planning a patch release soon which will have this fix

**Comment by phalox** [comment]
> 
> 
> Hi @phalox! The crash report server is down at the moment 😅 Can you email me the crash report at [viktor@viktorelofsson.se](mailto:viktor@viktorelofsson.se)?
> 
> It's located at `C:\Users\<you>\AppData\Local\PicoTorrent\Crashpad\db\reports` IIRC. It's a `.dmp` file.

Should have arrived in your mailbox :)

**Comment by vktr** [comment]
> Should have arrived in your mailbox :)

Yes! I got it :)

**Comment by ivanjaros** [comment]
i just got the 0.19.0 and immediately the UI is more responsive, less laggy/slow, or whatever you want to call it. so far no crash :D

**Comment by vktr** [comment]
Great to hear! I'm planning a release later tonight which will I hope will fix this issue.

**Comment by vktr** [comment]
Hey thread! I've just released v0.20 which I believe fixes the issues in here. Closing this for now, but if the issues still persist - feel free to reopen or create a new issue. Thanks!
