### ISSUE TITLE
UX regression: easily open containing folders of transfers

### ISSUE THREAD

**Issue by vinajuliette** [picotorrent/picotorrent#870]
This is a UX regression though a small issue: in the previous (Qt) version, after a torrent was completed (and probably before, but I had not tested that) a user could double-click a transfer in the transfer list and it would open the containing folder in Explorer, but this no longer works.

An improved version would repeat this old functionality, but also
1) support hitting the Enter key to open the containing folder, and
2) allow the user to select multiple transfers from the list then hit the Enter key to open the containing folders for each transfer

**Comment by vktr** [comment]
Hey @vinajuliette! Thanks for reporting - we'll get it sorted for the next release.
