### ISSUE TITLE
Small width of preferences list

### ISSUE THREAD

**Issue by birkoffe** [picotorrent/picotorrent#871]
0.19.0

Small width of preferences list for Russion translation and/or English on 2k monitor with 125% scaling.

![изображение](https://user-images.githubusercontent.com/828228/92298595-dced3780-ef74-11ea-83cb-ae896051a36a.png)

**Comment by vktr** [comment]
I've seen it but haven't found a real solution other than rewriting the preferences dialog completely. I'll see what we can do for the next version.

**Comment by vktr** [comment]
@birkoffe I pushed this to a future release since I wanted to time the 0.20 version with the libtorrent 2.0 release.
