### ISSUE TITLE
Italian translation incomplete - Missing strings

### ISSUE THREAD

**Issue by TruckerZer0** [picotorrent/picotorrent#876]
Hello, and thanks you very much for this little gem, day after day it's really becoming my torrent workhorse!

not knowing how to collaborate for the moment I will report the missing parts in the translation with the related missing text translated:

In the menu bar, the "Visualizza" (View) menu shows:
Visualizza -> amp_filter -> amp_none / filter_downloading_active / filter_uploading_active
|
Pannello dettagli
amp_status_bar
|
Preferenze

Instead should be like:
Visualizza -> Filtro -> Nessuno / In download (attivi) / In upload (attivi)
|
Pannello dettagli
Barra di stato
|
Preferenze

And also in the status bar's left corner there's some missing translated text:
[number] num_torrents | DHT: [number] dht_num_nodes

That should be like:
[number] torrent (without the "s") | DHT: [number] nodi

Sorry for my english, I hope I was helpful, I remain available for other things; Keep up the great work!

**Comment by vktr** [comment]
Hi! Thanks for the report! I'll see if I can add those specific changes or if we wait until someone can send a PR 😄

**Comment by vktr** [comment]
Head over to Crowdin if you want to help translate PicoTorrent :) https://crowdin.com/project/picotorrent
