### ISSUE TITLE
Simplify working with Russian translation file

### ISSUE THREAD

**Issue by birkoffe** [picotorrent/picotorrent#879]
For easy to translation I want make line to line keys between 1033 and 1049 files.
In the process of working on #878 I found that 1049.json have keys not contained in original 1033.json

So,
1. 1033 now contain all elements for translations?

2. These phrases are no longer needed?
`remote
options
enable_websocket_api
security
access_token
certificate_public_key
statistics
show_qr_code
config_error_s
config_error_title
dht_i64d_nodes
i64d_torrents
encrypt_config_file
s_of_s`

**Comment by vktr** [comment]
Yeah, the original `1033.json` contains all translations. It is correct that it has some keys that we don't use anymore and should be removed.

I can probably manage to remove the unused keys myself, but I would like to make it easier for translators to work with the files as well. Do you have any suggestions on how I can make it easier for you?

**Comment by birkoffe** [comment]
Weird.

For example,
`s_of_s` missing in `1033.json`, but there is in `1049.json` and his result in torrent list such as `%s (из %s)` without current numbers.

![изображение](https://user-images.githubusercontent.com/828228/92312114-07c4a380-efe8-11ea-888b-b2062c690959.png)

Can you check original file.

Ideally wanted alphabet ordered keys in original json file.

**Comment by birkoffe** [comment]
Except checking `remote options enable_websocket_api security access_token certificate_public_key statistics show_qr_code config_error_s config_error_title dht_i64d_nodes i64d_torrents encrypt_config_file s_of_s`, need add to `1033` phrases from 
announces panel

![изображение](https://user-images.githubusercontent.com/828228/92312458-f204ad80-efea-11ea-8a7b-5ae3eb69353f.png)

**Comment by vktr** [comment]
Here's a list of all the keys used,

```
address
advanced
availability
bottom
browse
cancel
client
comment
commitish
component
connection
copy
dl
down
downloaded
downloads
edit
encryption
eta
fails
file
files
flags
general
hidden
host
http
ip
language
leeches
limits
low
maximized
maximum
minimized
miscellaneous
move
name
no
none
normal
ok
overview
password
pause
peers
pieces
port
preferences
priority
privacy
private
progress
proxy
queuing
ratio
remove
resume
scrape
seeds
size
socks4
socks5
status
storage
top
torrent
trackers
transfers
type
ul
unknown
up
updating
url
username
version
yes
```

Regarding the advanced settings and phrases - the idea there was to just copy the libtorrent comment for each setting to make it easy, and not have to translate everything... There's a lot of phrases to come 😄

**Comment by vktr** [comment]
Closing this since I think Crowdin meets the need.
