### ISSUE TITLE
Display download progress on Windows taskbar

### ISSUE THREAD

**Issue by wiktor-k** [picotorrent/picotorrent#88]
I'd be great if progress was also displayed on Windows taskbar button so that I don't have to open PicoTorrent to see what's going on.

I'm talking about something like this: http://www.codeproject.com/Articles/42345/Windows-Goodies-in-C-Taskbar-Progress-and-Status

Thanks for PicoTorrent! :)

**Comment by vktr** [comment]
Totally! I've had the same idea but never remembered to open an issue for it :smile:

**Comment by wiktor-k** [comment]
Cool! Can't wait to see it! Thanks a lot :)
