### ISSUE TITLE
PicoTorrent saves to Temp instead of Save Path.

### ISSUE THREAD

**Issue by S2F0amEgS2xvdmVy** [picotorrent/picotorrent#889]
While "Save Path" in Preferences->Downloads was set to "C:\Users\Computer\Downloads\QB" the download appears in "C:\Users\Computer\AppData\Local\Temp".

Steps I took:

1. scoop install vcredist
2. scoop install picotorrent
3. picotorrent -> change preferences
4. restart picotorrent; verify save path
5. add magnet link
6. torrent -> open in explorer

**Comment by vktr** [comment]
What preferences did you change?

If you select the torrent in the list view, which save path does it show in the Overview tab?

**Comment by S2F0amEgS2xvdmVy** [comment]
@vktr Just this setting, vktr.
![Capture](https://user-images.githubusercontent.com/25454644/92528166-96276800-f228-11ea-8d9d-7e55eddc4a59.PNG)

**Comment by vktr** [comment]
> If you select the torrent in the list view, which save path does it show in the Overview tab?

And also, did the correct save path show in the add torrent dialog?

**Comment by S2F0amEgS2xvdmVy** [comment]
> > If you select the torrent in the list view, which save path does it show in the Overview tab?
> 
> And also, did the correct save path show in the add torrent dialog?

In the Overview tab it says "C:\Users\Computer\AppData\Local\Temp".

And yes the add torrent dialog shows (...)\Downloads\QB as a correct file path, as does Explorer, and as does Qbittorrent.

**Comment by vktr** [comment]
I haven't seen similar behavior. Let me check

**Comment by S2F0amEgS2xvdmVy** [comment]
Sorry, forgot to mention: running on Windows 1809.

**Comment by S2F0amEgS2xvdmVy** [comment]
I haven’t been able to replicate this issue, so I will close it unless someone is able to replicate it again.

Thanks for the attention, vktr!
