### ISSUE TITLE
Wrong icon on taskbar

### ISSUE THREAD

**Issue by Tranberry** [picotorrent/picotorrent#895]
I'm experiencing an odd issue, windows 10 shows the wrong icon for PicoTorrent in the taskbar. I've tried `ie4uinit -show` in cmd/run but that doesn't solve the issue.

 ![Image of taskbar icon](https://i.imgur.com/Z5DBEOG.png)

Afaik this only happens for picotorrent.

**Comment by vktr** [comment]
There is a similar issue here - #761

If you try to run PicoTorrent from the zip file instead, does that instance have an app icon in the taskbar?

**Comment by Tranberry** [comment]
I solved this by replacing the shortcut `picotorrent.ink` located in `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\PicoTorrent.lnk` which didn't have `target` filled.


![](https://i.imgur.com/T9JO7C4.png)

**Comment by vktr** [comment]
Odd, that link is created by the installer. I wonder why it wasn't created correctly on your machine. Which version of Windows 10 are you running?

**Comment by Tranberry** [comment]
OS Name:	Microsoft Windows 10 Pro
Version:		10.0.18363 Build 18363

Are the version.

**Comment by Tranberry** [comment]
![image](https://user-images.githubusercontent.com/16529/93690903-4ffebe00-fade-11ea-978e-6715b64deaf1.png)

PicoTorrent version 0.21.08b2572c

**Comment by vktr** [comment]
Thanks for the update - I haven't had the opportunity to look at this yet. Did it reset when you upgraded?

**Comment by Tranberry** [comment]
I downloaded the 64bit installer and it reverted.

**Comment by vktr** [comment]
That's not good. I'll see what I can do to fix this in the installer rewrite I'm working on. Thanks for reporting!

**Comment by SimoneG97** [comment]
I had this exact problem today and was able to solve it the same way @Tranberry did.
PicoTorrent Version: 0.25.0 (commit c2ad8e2)

Windows 10 Home
Version: 21H1
OS Build: 19043.1165

Reporting it here cause looks like this was marked as solved, but maybe something has slipped by and it came back from the grave 👀
