### ISSUE TITLE
Bind to IP does not fully work

### ISSUE THREAD

**Issue by chris11c** [picotorrent/picotorrent#902]
I love the application and created an account here just to post this, thank you for an awesome app!

I start my VPN then set the Listen Interface to my VPN IP.  I check the connection to ensure it is using the VPN by using an ip leak testing magnet link (another issue, sometimes ip leak testing magnet links do not load) and checking the connected IP.  

If I disconnect the VPN connection, the torrents slow to a stop as expected, but then they start back up on my unprotected connection.  

Expected action is application uses VPN connection, if the selected connection drops, application does not jump connections and the data transfer stops to prevent leaks.

**Comment by vktr** [comment]
I think I fixed this issue by proxy when doing #899. Can you download the latest build from AppVeyor and check? Available here https://ci.appveyor.com/project/picotorrent/picotorrent/builds/35224502/job/nwcqkyi0acn32hme/artifacts

**Comment by chris11c** [comment]
Looks like that version fixed it!  

Though if I go to:
Preferences>Connection>Click old IP>Edit  The popup shows Network Adapter box as empty, if I click OK without changing anything, it crashes the application.  If I choose a working IP/Adapter, it works fine.  Just a heads up!

**Comment by vktr** [comment]
Great - can confirm the network adapter issue you found. I'll open a new issue for that :)
