### ISSUE TITLE
Crash when adding magnet link

### ISSUE THREAD

**Issue by phalox** [picotorrent/picotorrent#904]
v 0.20.0

When adding a magnet link, I believe that when I confirm the download before the magnet link has been fully processed (aka, when the files are visible), that picotorrent crashes.

It's a bit hard to reproduce, because you need to click fast. I submitted the crash report.

**Comment by vktr** [comment]
Hey @phalox! Thanks for the report. I found some issues and have put up a PR with the fixes.

**Comment by TechAdvancedCyborg** [comment]
Same!
