### ISSUE TITLE
Translation on Weblate

### ISSUE THREAD

**Issue by comradekingu** [picotorrent/picotorrent#911]
I want to help translate picotorrent, but any way of doing so now leaks into the translation memory over at Crowdin. Could you set up shop at Hosted Weblate instead?

**Comment by vktr** [comment]
Hey @comradekingu! I'm not really pleased with how Crowdin turned out either - one reason being the one you mention, the other one being the attribution where everything will be attributed to me due to how they have set up the GitHub integration.

I'm working on a tool to do this The Right Way - but I'll checkout Weblate as well. Thanks for the tip!

**Comment by vktr** [comment]
Hi again! I've set up a Weblate at https://translate.picotorrent.org - feel free to check it out :)

@birkoffe, @TechAdvancedCyborg you might be interested in this as well. Might shut down Crowdin due to various reasons. What's your opinion?

**Comment by comradekingu** [comment]
@vktr That was quick. I am not getting the registration e-mail for it.
It is possible to set up https://docs.weblate.org/en/latest/admin/auth.html#social-authentication for login.

**Comment by vktr** [comment]
I'm certain - I'll dive into it 😃 

Re: registration e-mail - did you check the spam folder? I'm using my own mail servers and they might not have the reputation needed :)

**Comment by comradekingu** [comment]
No such luck even trying a Gmail account

**Comment by vktr** [comment]
Odd. I'll see what I can find.

**Comment by comradekingu** [comment]
@vktr Works now

**Comment by vktr** [comment]
Sweet - did the email arrive?

**Comment by comradekingu** [comment]
@vktr Yes. https://translate.picotorrent.org/languages/nb_NO/ done.
I found some errors, but mostly things that could be improved. Will submit a PR for those.
https://translate.picotorrent.org/zen/picotorrent/application/nb_NO/?q=state%3A%3Ctranslated these ones (those some are things I am unsure about in Norwegian Bokmål)

**Comment by vktr** [comment]
Awesome! 😃 I haven't worked with Weblate before, but is it you or me that clicks Commit and Push in Weblate?

**Comment by comradekingu** [comment]
@vktr You do that, but you can also set up webhooks https://docs.weblate.org/en/latest/admin/continuous.html#automatically-receiving-changes-from-gitlab

**Comment by vktr** [comment]
I see! I have set up a webhook for GitHub but that is only to trigger a sync in Weblate when this repo changes. I'll have to look into if it can send changes automatically somehow so nothing is forgotten.

**Comment by comradekingu** [comment]
I incapacitated myself, but I added PicoTorrent to https://github.com/WeblateOrg/weblate/wiki/References
Hopefully the Crowdin integration can be shut down, so that nothing enters their closed source translation memory.

**Comment by TechAdvancedCyborg** [comment]
Gonna check it out

**Comment by TechAdvancedCyborg** [comment]
Looks nice!

**Comment by vktr** [comment]
I'll stop the automatic sync for now - I ju
