### ISSUE TITLE
0.21 just crashes after a torrent is completed

### ISSUE THREAD

**Issue by rolka-men** [picotorrent/picotorrent#917]
Just updated and upon completing a torrent download it crashes. Also is it possible to have % for progress back?

**Comment by vktr** [comment]
Hi! Can you either email me (viktor@viktorelofsson.se) or attach the crash dump located at `C:\Users\<you>\AppData\Local\PicoTorrent\Crashpad\db\reports`? It's a .dmp file.

**Comment by rolka-men** [comment]
Hey, dropped an email to you.

**Comment by vktr** [comment]
Thanks!

**Comment by rolka-men** [comment]
![image](https://user-images.githubusercontent.com/71606194/93877990-abe16680-fcd9-11ea-9374-c2987ea8597d.png)
that's what I get on starting a new magnet torrent now.

**Comment by vktr** [comment]
@rolka-men Yeah, I got the email with the dumps so I'll have a look. Thanks!

**Comment by MaikuMori** [comment]
Same issue

**Comment by vktr** [comment]
Hi! Can you try the latest CI build and see if it fixes it? I refactored a few things related to this a few days ago.

https://ci.appveyor.com/project/picotorrent/picotorrent/build/job/7x72eerubavuckvj/artifacts

**Comment by MaikuMori** [comment]
Still the same.

**Comment by vktr** [comment]
Did some digging - the crash dumps I got sent pointed to the same issue, an invalid JSON value for the settings key `move_completed_downloads_path`.. If you feel comfortable with SQLite, you can edit the PicoTorrent database manually with any SQLite editor. I'm putting up a PR to fix this soon.
