### ISSUE TITLE
Columns size, order and status

### ISSUE THREAD

**Issue by TechnoGreg** [picotorrent/picotorrent#920]
Hi there,

I just found out that every time I start Picotorrent all columns are reset to original size, order and showed/hidden status.
I remember @vktr saying something concerning that but just after a fresh install.
I'm available to produce Screenshot and more informations if needed.

**Comment by vktr** [comment]
Odd, I'll have to check. The column state is stored in the database and should be restored at startup.

**Comment by vktr** [comment]
Can confirm this

**Comment by TechnoGreg** [comment]
Duplicate of #916
