### ISSUE TITLE
Bad display of special character

### ISSUE THREAD

**Issue by TechnoGreg** [picotorrent/picotorrent#922]
Hi there,

on last build, there is some missing translation (eta_format) and some bad display of accented character.
Seems to be the same on many localization.

And the error messages are displaying in system language (French in my case) whatever the PicoTorrent selected translation.
As well as the languages list.

![Capture d’écran 2020-09-23 215225](https://user-images.githubusercontent.com/22304655/94062754-5eebb600-fde7-11ea-943f-227a88f8906b.png)

**Comment by vktr** [comment]
Thanks for the report! The eta_format must be a miss when I rewrote the translation system. 

The French error you see comes from the OS and not from PicoTorrent. It will always be in the default user language.

**Comment by TechnoGreg** [comment]
Ok for the default language displaying errors.

But the accented character is still displayed by PicoTorrent, do you think its an unsupported ISO format or something like that ?

And concerning the languages character selection list ? Don't you think you must display each language in its current language ?

Like English for english,
Deutsch for german
Français for French
etc...

**Comment by vktr** [comment]
The question mark symbols is an issue and bug, yes 😊

The names of languages is also taken from the default user language in Windows. I’m guessing now but I think it’s unlikely that a user runs Windows in a language they do not know which means that they either run their native language or English. The only thing I’m not quite pleased with there is the inconsistency, but I think it’s quite nice to let Windows handle that part.

I’m happy to be proven wrong though! 😀

**Comment by TechnoGreg** [comment]
I'm pretty sure you're right on that part too, that was kind of a suggestion. 
Happy to have found a bug thought, what making PicoTorrent better is pleasing me :)

**Comment by TechnoGreg** [comment]
Here are the missing parts (translations seems ok but not displaying) in yellow :

The View drop menu :
![Pico02246_preferencesmenu](https://user-images.githubusercontent.com/22304655/94836681-8c51e880-0413-11eb-82ca-5416d037cee2.png)

The Preferences main menu : 
![Pico02246_preferencesmenu](https://user-images.githubusercontent.com/22304655/94836817-b4d9e280-0413-11eb-9eed-f5193ae4e690.png)

The preferences new labels menu : 
![Pico02246_preferenceslabelsmenu](https://user-images.githubusercontent.com/22304655/94836957-e652ae00-0413-11eb-946d-0c77a1ae6b8b.png)

**Comment by vktr** [comment]
Hey @TechnoGreg! Is anything in this issue still relevant?

**Comment by TechnoGreg** [comment]
Hey @vktr, I don't currently have torrents downloading with some errors in the tackers tab. But I still have "eta_format" occurence.
