### ISSUE TITLE
Add portable .zip to torrent

### ISSUE THREAD

**Issue by johnrichardrinehart** [picotorrent/picotorrent#932]
# Summary

I respect bandwidth costs and like using P2P whenever possible. Can you please add the portable .zip to the torrent or make a separate torrent for it?

Thanks!

**Comment by vktr** [comment]
I'm not sure I follow. To which torrent? The portable zip is added to each release both here on GitHub and on FOSSHub

**Comment by johnrichardrinehart** [comment]
:facepalm: This issue was meant for [OBS](https://github.com/obsproject/obs-studio/). Sorry, @vktr. Great job with `picotorrent`.
