### ISSUE TITLE
Installer hash mismatch

### ISSUE THREAD

**Issue by Cereal-Killa** [picotorrent/picotorrent#938]
`Error 0x80091007: Hash mismatch for path: C:\ProgramData\Package Cache\.unverified\VC_redist.x64.exe, expected: 75F1AEE6DCCF3D6E6AC49926563737005B93BA13, actual: 3155CB0F146B927FCC30647C1A904CD162548C8C`

![image](https://user-images.githubusercontent.com/25939765/94842196-7c291180-03f1-11eb-9eb6-12dcabc956ce.png)

[Log.txt](https://github.com/picotorrent/picotorrent/files/5313786/Log.txt)

**Comment by vktr** [comment]
Thanks for the report! We have a similar issue reported here #894. Closing this as duplicate but feel free to follow the other.
