### ISSUE TITLE
Port is limited to 4 nums

### ISSUE THREAD

**Issue by DoumanAsh** [picotorrent/picotorrent#95]
While port can be up to 65k, config allows you to enter only 4 num.
Funny thing is that you can enter some non-numeric character :)

p.s. manual edit of config works of course :)

**Comment by zp** [comment]
Which version are you using? v0.4 appears to handle 5 digit ports fine via preferences window.

It does let you input values higher than 65535 though, not sure how the back-end handles that. (it crashes for me if i attempt to use letters)

**Comment by vktr** [comment]
Thanks for reporting! Are you running a retina display? I believe I've seen this with retina displays, that they size the input a bit too small (even though I do DPI scaling) and then only accept four digits.

Input validation is missing, though :sweat_smile:

**Comment by DoumanAsh** [comment]
Example
http://i.imgur.com/EmBhLxg.png

Well not sure what is type of display i'm having :D
