### ISSUE TITLE
Bug: Maximized Windows Reverts to Minimized State When Clicked from System Tray.

### ISSUE THREAD

**Issue by indiuscartha** [picotorrent/picotorrent#953]
If I have the PicoTorrent windows maximized, and I exit (file>exit) and restart it maintains it's full size.

However, if I click on close to system tray, and then click on the
 system tray icon to relaunch, it returns to a minimized size (whatever minimized site I had previously).

![Max](https://user-images.githubusercontent.com/57152701/95005566-2cfdff00-05f2-11eb-931c-37aa111a78b3.png)

**Comment by t1jani** [comment]
I think that is the normal behavior, I you like you can explain further on what you think is a bug.
