### ISSUE TITLE
Bug: Position of Name / Size / Status / Progress ect Returns to Default Position on Restart

### ISSUE THREAD

**Issue by indiuscartha** [picotorrent/picotorrent#954]
When PicoTorrent restarts, the positions / selection of Name / Size / Status / Progress / ETA , returns to default position(s). 

![position](https://user-images.githubusercontent.com/57152701/95005587-81a17a00-05f2-11eb-832a-c5ad0f62837f.png)

**Comment by vktr** [comment]
This was fixed in #927, is available in the latest CI builds, and will be released with the next version. Thanks for reporting, though!
