### ISSUE TITLE
File structure is not displayed during torrent adding.

### ISSUE THREAD

**Issue by DoumanAsh** [picotorrent/picotorrent#96]
All files are added without taking into account directory structure.
I.e. if you have torrent with directories pico will ignore it and just adds only files.

Example of torrent: http://www.nyaa.se/?page=download&tid=776448
It's structure:
```
CD1/*.flac
CD2/*.flac
```

**UPD:**
Actual issue is only the fact that file structure is not displayed correctly during torrent's adding

**Comment by vktr** [comment]
I can't seem to reproduce this with the example torrent. Here's the directory structure that PicoTorrent downloads to,

- Silverio_Vendeta
  - CD1
    - *.flac
  - CD2
    - *.flac

Is this not correct?

I do, however, notice that the add torrent dialog does not show a good representation of the final structure on disk.

**Comment by DoumanAsh** [comment]
Oh yes... i rechecked again and seems like i originally put it in wrong directory.
At first i was surprised by strange look of file structure preview and the fact that it couldn't find existing files in(presumably correct place)

I will correct title of issue, as preview of file structure should be correctly represented.

**Comment by vktr** [comment]
I'll add this as a feature request :smile: Great find!
