### ISSUE TITLE
Adding duplicate magnet link crashes client

### ISSUE THREAD

**Issue by phalox** [picotorrent/picotorrent#961]
When you add (I believe) a duplicate magnet link, it crashes the client.

Crash report should be with you!

**Comment by vktr** [comment]
Can you send them by email as well? I'm having issues with our Crashpad server still 😿

**Comment by Dyras** [comment]
Do you need more logs? This is also happening for me

**Comment by vktr** [comment]
Hey @Dyras! No, I can reproduce it as well, I just haven't had the time or energy to fix it, sorry.
