### ISSUE TITLE
Crash reports are having missing function names

### ISSUE THREAD

**Issue by DoumanAsh** [picotorrent/picotorrent#97]
To improve further debug it would be better to have some way to enable stripped debug info so that there would no missing elements in callstack:
![pic](http://i.imgur.com/ztZkqUr.png)

~~P.s. having file+lines would be great also~~

**Comment by zp** [comment]
You need to grab the .pdb file from the corresponding installer version of PicoTorrent (portable zip omits them)

Perhaps next release @vktr can add a zip file containing the .pdb files for the portable releases.

**Comment by DoumanAsh** [comment]
I suppose it would be great improvement to portable versions be shipped with debug symbols.

**Comment by vktr** [comment]
Yeah, sorry about the mix in quality of the portable zips, I pack them manually and seem to have forgotten the debug symbols this time.

I'll label this as a feature request and make sure it is fixed for the next release :)
