### ISSUE TITLE
Feature Request: Auto Save of Torrent infos

### ISSUE THREAD

**Issue by annomatik** [picotorrent/picotorrent#970]
I'm running PicoTorrent on a rather low-spec Laptop. Most of the time, this works well, sometimes it crashes though (I can try to give you logs if you tell me where to find them).

Long story short, when I start PicoTorrent again after a crash, it does not show all the torrents sometimes and also does not recognize, that it has already moved some finished torrents into the complete directory. Would it be possible to add a "auto save" or a similar function, that stores the current state of all torrents into a file which is checked during the next startup?

Thanks!

**Comment by vktr** [comment]
The latest version (0.22) added an auto save interval to limit the issues you describe. Does it not work for you, or do you mean something else entirely?

**Comment by annomatik** [comment]
I'm still on 0.18 :-D Will try it, thanks!

**Comment by annomatik** [comment]
This seems to be exactly the stuff. Thanks, Ticket closed!
