### ISSUE TITLE
Question about Label - Save path

### ISSUE THREAD

**Issue by annomatik** [picotorrent/picotorrent#971]
Just installed 0.22 -- and hey, it can do labels! Very happy.

One question about the save path. Will this be the directory, picotorrent is moving the finished download to ("completed directory")? Or is this a "downloading" directory, where the file downloads to?

My use case would be using this directory for tools like Medusa, which looks into that directory, takes what's there and automatically moves it to a different directory. This would of course mean, that I couldn't use that feature with incomplete files.

**Comment by annomatik** [comment]
Also, one enhancement request -- I can make a dedicated issue for that, if you prefer. Would it be possible to have some sort of a "label torrent directory", too? With that, I mean a directory, that is automatically monitored. If there is a new .torrent in it, picotorrent would automatically download that torrent and automatically assign that label.

![image](https://user-images.githubusercontent.com/28311452/95665989-a8613280-0b55-11eb-8ec0-207834d57fab.png)

**Comment by vktr** [comment]
The label save path is the "downloading" directory as you describe it. We are adding moving completed downloads to labels in the upcoming releases as we're improving label functionality and support throughout :)

And for monitoring directories, that is planned as well, and it will be integrated with the label support also.

**Comment by annomatik** [comment]
perfect. Your replies make me very happy :-)
