### ISSUE TITLE
0.22.0 prefixes all over the place

### ISSUE THREAD

**Issue by ivanjaros** [picotorrent/picotorrent#975]
I just downloaded the x64 windows zip version and replaced all files in C:\Program Files\PicoTorrent that had the previous version. When I opened up PT everything in main menu had "amp_" prefix and all statuses in the status column had "state_" prefix. When I manually selected english language in the preferences and restarted PT, all was good. Looks like there is default case missing in language switch select somewhere in the code :)

**Comment by vktr** [comment]
Hi! Did you also place the `coredb.sqlite` file in the same folder? That file contains all translations :)

**Comment by ivanjaros** [comment]
yes

**Comment by vktr** [comment]
Odd. Is there any reason why you use the zip file and not the installer? The zip-file works best in a folder that you have write permissions on since it needs to create some files, such as the settings database and such.

Can you try to run the application from a folder with write permissions?

**Comment by ivanjaros** [comment]
> Odd. Is there any reason why you use the zip file and not the installer?

this was the first time, i used it because it is faster than installer

> the zip-file works best in a folder that you have write permissions

i know, i gave permissions when overwriting old files

maybe it was just a fluke, who knows. no biggie. but there still should be some default case if language cannot be found.

**Comment by nero-0** [comment]
Same here when I select pt language, no problems in English. 
Also, folder contains write permissions. The necessary files are created without a problem.

I'm using the .zip version too (aka portable), much more practical for my needs (btw thanks for providing it! :)).

**Comment by vktr** [comment]
@nero-0 Can you check the log file? It should contain some information about language matching.

**Comment by nero-0** [comment]
Here's the lastest log if you want to take a look
[PicoTorrent.20201123060146.log](https://github.com/picotorrent/picotorrent/files/5581856/PicoTorrent.20201123060146.log)

**Comment by nero-0** [comment]
An update regarding this:
I noticed that it's not exactly a bug, but a bad behavior. I mean, if the selected language is not fully translated, instead of the untranslated space being taken up by the default language (English, I suppose), a key is put in place, e.g. amp_console.

I have no more problems here using pt-BR. Maybe OP uses pt-PT, which is not fully translated atm.

I also want to say that there is no difference indicating which is pt-BR or pt-PT, both are listed only as ''Portuguese''.
I think it would be a good idea to make it explicit. :p

**Comment by vktr** [comment]
Thanks for the info @nero-0! There is an issue in how we select the English locale which is mentioned in #1020. I'd say fixing this would resolve both of these.
