### ISSUE TITLE
Graphical glitch with the details panel

### ISSUE THREAD

**Issue by SViN24** [picotorrent/picotorrent#990]
![2020-10-19-23-14-06](https://user-images.githubusercontent.com/51864332/96506762-ddaa0680-1260-11eb-9aa5-5dd571f5780c.gif)
There seems to be graphical glitch in the newest release (0.22) when making the details panel bigger or smaller

**Comment by vktr** [comment]
Hey @SViN24! Thanks for the report, and I appreciate the GIF. I've seen that behavior as well and I believe it's something in wxWidgets. I'll see what I can do to remedy it.
